nuxeo-drive-client/nxdrive/client/base_automation_client.py
nuxeo-drive-client/nxdrive/client/remote_file_system_client.py
nuxeo-drive-client/nxdrive/engine/activity.py
nuxeo-drive-client/nxdrive/engine/engine.py
nuxeo-drive-client/nxdrive/engine/processor.py
nuxeo-drive-client/nxdrive/engine/queue_manager.py
nuxeo-drive-client/nxdrive/engine/watcher/remote_watcher.py
nuxeo-drive-client/nxdrive/engine/workers.py
nuxeo-drive-client/nxdrive/osi/windows.py
nuxeo-drive-client/nxdrive/tests/test_remote_deletion.py

Fix nxdrive 258 interrupt on delete

---

README.md

Unfortunately I could not get it fully running yet, as my server does not use uid/pwd credentials, but certificate/SSO.
However the basic installations commands are not difficult to translate. I hope I will be able to report successful running on Scientific Linux and Fedora soon.

Add RPM specific actions to README.md

---

tools/posix/deploy_jenkins_slave.sh
tools/windows/deploy_jenkins_slave.ps1

It speedup downloads by a factor of 10-20. And now we can trust the server, it is much more reliable.

NXDRIVE-753: Use S3 buket server to deliver packages

---

nuxeo-drive-client/tests/test_remote_move_and_rename.py
requirements.txt
tools/linux/deploy_jenkins_slave.sh
tools/osx/deploy_jenkins_slave.sh
tools/posix/deploy_jenkins_slave.sh

Also:
- Fix GNU/Linux installation on "static" slave

NXDRIVE-757: Mark new GNU/Linux random bug

---

tools/checksums.txt
tools/linux/deploy_jenkins_slave.sh
tools/osx/deploy_jenkins_slave.sh
tools/posix/deploy_jenkins_slave.sh
tools/windows/deploy_jenkins_slave.ps1

It should help to prevent failure at setup step. I added a MD5 checksum and 5 download tries.

NXDRIVE-758: Add integrity checks and several download tries

---

requirements-mac.txt
requirements-tests.txt
requirements.txt
tools/posix/deploy_jenkins_slave.sh
tools/windows/deploy_jenkins_slave.ps1

Few interesting updates, espacially from py2app which fix 2 bugs on Python 2.7. I do not know implications, but it *could help* with our auto-update issues.

NXDRIVE-775: Upgrade requirements

---

nuxeo-drive-client/nxdrive/manager.py

This will reduce false errors in the console like this one:
ERROR    nxdrive.manager    Error retrieving PAC url from system: WindowsError(2, 'The system cannot find the file specified')

NXDRIVE-774: PAC - Do not print an error if not needed

---

tools/jenkins/beta.groovy
tools/jenkins/prod.groovy
tools/release.sh

Much better now. If the triggered job fails, the current job will too.

NXDRIVE-571: Remove use of "triggerRemoteJob" for "build"

---

tools/jenkins/beta.groovy

NXDRIVE-571: Use SSH agent to be able to push to GitHub

---

tools/changelog.py
tools/jenkins/beta.groovy
tools/jenkins/packages.groovy
tools/jenkins/prod.groovy
tools/jenkins/tests.groovy
tools/release.sh

NXDRIVE-571: Fix syntax errors

---

nuxeo-drive-client/nxdrive/client/rest_api_client.py
nuxeo-drive-client/tests/test_group_changes.py
nuxeo-drive-client/tests/test_local_copy_paste.py
nuxeo-drive-client/tests/test_synchronization.py

Functional tests for [NXP-14830](https://jira.nuxeo.com/browse/NXP-14830): Removing a user from a group (or deleting the group) for which the Read permission is granted on a folder synchronized for the given user is not detected as a deletion by Drive

task-NXDRIVE-779-group-change-tests

---

nuxeo-drive-client/nxdrive/client/remote_file_system_client.py
nuxeo-drive-client/nxdrive/manager.py
nuxeo-drive-client/nxdrive/wui/application.py

Nothing fixed here, just logging purgation. I was testing proxies for a customer and did a cleanup at the occasion.

NXDRIVE-724: PEP8, cleanup

---

nuxeo-drive-client/nxdrive/engine/processor.py
nuxeo-drive-client/tests/test_local_changes_when_offline.py
nuxeo-drive-client/tests/test_shared_folders.py
setup.py

NXDRIVE-645 : Add the test case (fixed by NXDRIVE-822)
NXDRIVE-686: Add several tests + fix (thanks to @mkeshava)
Tests were green but we lost the trace with the Jenkins restart ...

NXDRIVE-645-686 Fixes

---

nuxeo-drive-client/nxdrive/__init__.py
nuxeo-drive-client/nxdrive/report.py
nuxeo-drive-client/tests/common_unit_test.py

Also:
- NXDRIVE-860: Do not compress reports from older version of Drive

NXDRIVE-859: Generate valid pictures for test files

---

nuxeo-drive-client/nxdrive/__init__.py
nuxeo-drive-client/nxdrive/client/local_client.py
nuxeo-drive-client/nxdrive/debug/wui/engine.py
nuxeo-drive-client/nxdrive/engine/engine.py
nuxeo-drive-client/nxdrive/engine/processor.py
nuxeo-drive-client/nxdrive/engine/watcher/local_watcher.py
nuxeo-drive-client/nxdrive/engine/watcher/remote_watcher.py
nuxeo-drive-client/nxdrive/engine/workers.py
nuxeo-drive-client/nxdrive/manager.py
nuxeo-drive-client/nxdrive/notification.py
nuxeo-drive-client/nxdrive/osi/darwin/darwin.py
nuxeo-drive-client/nxdrive/report.py
nuxeo-drive-client/nxdrive/updater.py
nuxeo-drive-client/nxdrive/wui/application.py
nuxeo-drive-client/nxdrive/wui/authentication.py
nuxeo-drive-client/nxdrive/wui/conflicts.py
nuxeo-drive-client/nxdrive/wui/dialog.py
nuxeo-drive-client/nxdrive/wui/metadata.py
nuxeo-drive-client/nxdrive/wui/settings.py
nuxeo-drive-client/nxdrive/wui/systray.py
nuxeo-drive-client/tests/test_report.py
tools/changelog.py

And NXDRIVE-873: Fix report generation with a standard (non administrator) user on Windows.
More details in commits messages.

NXDRIVE-858: Review all log.exception() calls

---

nuxeo-drive-client/nxdrive/__init__.py
nuxeo-drive-client/nxdrive/data/ui5/templates/conflicts-content.html
nuxeo-drive-client/nxdrive/data/ui5/templates/settings-about.html
nuxeo-drive-client/nxdrive/engine/engine.py
tools/jenkins/tests.groovy

A lot of changes are formatting, the revelant one is [here](https://github.com/nuxeo/nuxeo-drive/pull/238/files#diff-98dc04dfcaea905f186315bbd5309da1L23) where `ng-show="pair.duplication_enabled"` was hiding all choices.

NXDRIVE-878: Re-enable conflict resolution

---

nuxeo-drive-client/nxdrive/commandline.py
nuxeo-drive-client/nxdrive/engine/engine.py
nuxeo-drive-client/nxdrive/engine/watcher/local_watcher.py
nuxeo-drive-client/nxdrive/engine/workers.py
nuxeo-drive-client/nxdrive/logging_config.py
nuxeo-drive-client/nxdrive/wui/dialog.py
nuxeo-drive-client/nxdrive/wui/settings.py
nuxeo-drive-client/tests/test_remote_document_client.py
nuxeo-drive-client/tests/test_synchronization_suspend.py

Also:
- Fixed 3 regressions introduced with NXDRIVE-858.

NXDRIVE-680: Fix unwanted local upload on network connection lost

---

nuxeo-drive-client/nxdrive/__init__.py
nuxeo-drive-client/nxdrive/client/local_client.py
nuxeo-drive-client/nxdrive/engine/watcher/local_watcher.py
nuxeo-drive-client/nxdrive/manager.py
nuxeo-drive-client/nxdrive/osi/__init__.py
nuxeo-drive-client/nxdrive/osi/darwin/__init__.py
nuxeo-drive-client/nxdrive/osi/darwin/darwin.py
nuxeo-drive-client/nxdrive/osi/windows/__init__.py
nuxeo-drive-client/nxdrive/osi/windows/windows.py
nuxeo-drive-client/nxdrive/utils.py
nuxeo-drive-client/tests/test_direct_edit.py

And some cleanup here and there.

NXDRIVE-890: Cleanup Windows XP specific code

---

ftest/itests.xml
ftest/pom-8.10.xml
tools/jenkins/tests-8.10.groovy

The job will be launched every night.

NXDRIVE-837: Ready to launch tests againt Nuxeo 8.10

---

nuxeo-drive-client/nxdrive/client/common.py
nuxeo-drive-client/nxdrive/commandline.py
nuxeo-drive-client/nxdrive/engine/watcher/remote_watcher.py
nuxeo-drive-client/nxdrive/wui/dialog.py
nuxeo-drive-client/nxdrive/wui/systray.py
nuxeo-drive-client/tests/test_remote_file_system_client.py

The issue was introduced with NXDRIVE-744 and a simple fix is to get values from the DTB without trying to contact those URLs.  If one is wrong, it is the user fault and he will need to provide a good URL.
And little cleanup too.

NXDRIVE-895: Systray menu blocked when the update website is unreachable

---

tools/jenkins/tests-8.10.groovy
tools/jenkins/tests.groovy
tools/posix/deploy_jenkins_slave.sh
tools/windows/deploy_jenkins_slave.ps1

- Use `pip --upgrade` on Windows.
- Prevent the re-download/re-installation of already satisfied requirements.
- Remove quiet arguments to know what is it currently done and help _future eventual_ debugging sessions.

NXDRIVE-917: Enhance deploy scripts

---

nuxeo-drive-client/nxdrive/wui/settings.py

Any parameters will be forwarded to the Nuxeo login page.

NXDRIVE-908: Support parameters in Nuxeo URL

---

docs/changes.md
docs/technical_changes.md
nuxeo-drive-client/nxdrive/client/common.py
nuxeo-drive-client/nxdrive/engine/engine.py
nuxeo-drive-client/nxdrive/utils.py
nuxeo-drive-client/nxdrive/wui/settings.py
nuxeo-drive-client/tests/test_utils.py

We can now enter these values:
- IP
- IP:port
- IP:port/path
- domain.name
- full URL as usual

NXDRIVE-934: Try to guess the server URL

---

docs/changes.md
ftest/itests.xml
ftest/pom-8.10.xml
ftest/pom.xml
nuxeo-drive-client/nxdrive/client/base_automation_client.py
nuxeo-drive-client/nxdrive/client/remote_document_client.py
nuxeo-drive-client/nxdrive/client/rest_api_client.py
nuxeo-drive-client/nxdrive/direct_edit.py
nuxeo-drive-client/nxdrive/engine/engine.py
nuxeo-drive-client/tests/common.py
nuxeo-drive-client/tests/common_unit_test.py
nuxeo-drive-client/tests/test_bulk_remote_changes.py
nuxeo-drive-client/tests/test_direct_edit.py
nuxeo-drive-client/tests/test_remote_document_client.py

I also backpoted some methods to the Python cient.

NXDRIVE-731: Remove nuxeo-jsf-ui package dependency

---

docs/changes.md
docs/technical_changes.md
nuxeo-drive-client/nxdrive/__init__.py
nuxeo-drive-client/nxdrive/client/remote_document_client.py
nuxeo-drive-client/nxdrive/engine/processor.py
nuxeo-drive-client/nxdrive/engine/watcher/local_watcher.py
nuxeo-drive-client/nxdrive/utils.py
nuxeo-drive-client/tests/common.py
nuxeo-drive-client/tests/common_unit_test.py
nuxeo-drive-client/tests/manual/nxdrive-904.py
nuxeo-drive-client/tests/test_group_changes.py
nuxeo-drive-client/tests/test_local_move_and_rename.py
nuxeo-drive-client/tests/test_manager_dao.py
nuxeo-drive-client/tests/test_permission_hierarchy.py
nuxeo-drive-client/tests/test_remote_document_client.py
nuxeo-drive-client/tests/test_remote_move_and_rename.py
nuxeo-drive-client/tests/test_shared_folders.py
nuxeo-drive-client/tests/test_sync_roots.py
nuxeo-drive-client/tests/test_volume.py

I also moved several `RemoteDocumentClient` methods in tests as they were only used there. And PEP8 too, as always :)

NXDRIVE-904: Renaming folders and removing files does not sync while not running

---

docs/changes.md
nuxeo-drive-client/nxdrive/gui/folders_dialog.py
setup.py
tools/jenkins/packages.groovy
tools/posix/deploy_jenkins_slave.sh
tools/windows/deploy_jenkins_slave.ps1

- NXDRIVE-977: Drive-packages should fail on error
- NXDRIVE-983: Windows pip installation failure because of inexistant DLL
- NXDRIVE-985: The pyjs module is missing from the final package

Several packaging fixes

---

tools/windows/deploy_jenkins_slave.ps1

Also:
- Added verbose argument

NXDRIVE-983: Fix DLL destination

---

tools/windows/deploy_jenkins_slave.ps1

NXDRIVE-983: Ensure DLL are copied

---

docs/changes.md
nuxeo-drive-client/nxdrive/__init__.py
nuxeo-drive-client/nxdrive/engine/processor.py

Updated changes and version from #299.

NXDRIVE-990: "Other docs" folder is deleted after disconnect and reconnect with same user

---

docs/changes.md
nuxeo-drive-client/nxdrive/data/ui5/js/ndrive-systray.js
nuxeo-drive-client/nxdrive/manager.py

I removed obsolete JS code too.

NXDRIVE-978: Wrong resume/suspend icon after pause and disconnect/reconnect

---

docs/changes.md
docs/technical_changes.md
nuxeo-drive-client/nxdrive/engine/processor.py
nuxeo-drive-client/nxdrive/engine/watcher/remote_watcher.py
nuxeo-drive-client/nxdrive/report.py
nuxeo-drive-client/tests/common_unit_test.py
nuxeo-drive-client/tests/mac_local_client.py
nuxeo-drive-client/tests/test_nxdrive_903.py
nuxeo-drive-client/tests/win_local_client.py
tools/posix/deploy_jenkins_slave.sh
tools/release.sh
tools/windows/deploy_jenkins_slave.ps1

Also:
- Tests: Report is generated on failure only
- Tests: Less verbosity

NXDRIVE-903: Renaming folders/files does not sync while offline

---

docs/changes.md
nuxeo-drive-client/nxdrive/commandline.py

By setting the default level to DEBUG.

NXDRIVE-968: Improve logs disk space usage

---

docs/changes.md
nuxeo-drive-client/nxdrive/engine/engine.py
nuxeo-drive-client/tests/test_remote_deletion.py
nuxeo-drive-client/tests/test_remote_move_and_rename.py
nuxeo-drive-client/tests/test_synchronization.py

Tests are finally green!
I removed test_synchronize_remote_deletion_local_modification as it was skipped for a long time.

NXDRIVE-1049: Better use of Mock objects in tests

---

README.md
docs/changes.md
docs/deployment.md
nuxeo-drive-client/nxdrive/manager.py
nuxeo-drive-client/nxdrive/wui/systray.py
nuxeo-drive-client/tests/manual/common.py
nuxeo-drive-client/tests/manual/nxdrive-844.py
nuxeo-drive-client/tests/manual/nxdrive-881.py
tools/posix/deploy_jenkins_slave.sh

Alos, add manual test for NXDRIVE-844.

NXDRIVE-755: Update deployment documentation

---

docs/changes.md
nuxeo-drive-client/nxdrive/engine/engine.py
nuxeo-drive-client/nxdrive/engine/processor.py
nuxeo-drive-client/nxdrive/engine/watcher/remote_watcher.py
nuxeo-drive-client/nxdrive/engine/workers.py
nuxeo-drive-client/nxdrive/wui/application.py
nuxeo-drive-client/tests/common_unit_test.py
tools/posix/deploy_jenkins_slave.sh

NXDRIVE-1054: Smart remote changes handling

---

docs/changes.md
nuxeo-drive-client/nxdrive/__init__.py
nuxeo-drive-client/nxdrive/options.py
nuxeo-drive-client/tests/test_options.py

NXDRIVE-1059: Wrong URL for the beta channel

---

ftest/itests.xml

This reverts commit b58c1269befb52f1e2a66f1f1fe3bba91d30fa8b.

task-NXDRIVE-1044-enable-stream-audit-for-tests

---

docs/changes.md
docs/technical_changes.md
nuxeo-drive-client/nxdrive/__init__.py
nuxeo-drive-client/nxdrive/engine/engine.py
nuxeo-drive-client/nxdrive/gui/folders_dialog.py
nuxeo-drive-client/nxdrive/gui/folders_treeview.py
nuxeo-drive-client/nxdrive/wui/settings.py
nuxeo-drive-client/tests/test_bulk_remote_changes.py

Also:
- Re-enable the possibility to uncheck a root in the filters window

NXDRIVE-1069: Show filters window on account creation

---

docs/changes.md
docs/technical_changes.md
nuxeo-drive-client/nxdrive/engine/engine.py
nuxeo-drive-client/nxdrive/options.py
nuxeo-drive-client/nxdrive/updater.py
tools/checksums.txt
tools/posix/deploy_jenkins_slave.sh
tools/windows/deploy_jenkins_slave.ps1

* Added Options.server_info
* Updater: Skip exception on 404 errors
* Upgraded SIP from 4.19.6 to 4.19.7

NXDRIVE-940: Release 3.0.4

---

docs/changes.md
docs/technical_changes.md
nuxeo-drive-client/nxdrive/commandline.py
nuxeo-drive-client/nxdrive/direct_edit.py
nuxeo-drive-client/nxdrive/manager.py
nuxeo-drive-client/nxdrive/wui/application.py
tools/jenkins/beta.groovy
tools/jenkins/packages.groovy
tools/jenkins/prod.groovy
tools/jenkins/tests-8.10.groovy
tools/jenkins/tests.groovy

We do not support Nuxeo < LTS2015.
Also:
- Jenkins: Discard old builds

NXDRIVE-1087: Remove backward compatibility code for Nuxeo <= 5.8

---

docs/changes.md
docs/technical_changes.md
nuxeo-drive-client/nxdrive/autolocker.py
nuxeo-drive-client/nxdrive/client/base_automation_client.py
nuxeo-drive-client/nxdrive/client/local_client.py
nuxeo-drive-client/nxdrive/commandline.py
nuxeo-drive-client/nxdrive/direct_edit.py
nuxeo-drive-client/nxdrive/engine/blacklist_queue.py
nuxeo-drive-client/nxdrive/engine/processor.py
nuxeo-drive-client/nxdrive/utils.py
nuxeo-drive-client/tests/test_blacklist_queue.py
nuxeo-drive-client/tests/test_direct_edit.py
nuxeo-drive-client/tests/test_utils.py
tools/posix/deploy_jenkins_slave.sh
tools/windows/deploy_jenkins_slave.ps1

Also, a lot of cleanup:
- Framework: do not create test folder for case sensitivity in the Drive folder but in a temporary one
- Remove a debug line from InvalidBatchException
- `DirectEdit._url` -> `.url`
- Better logic when using DE if Drive is already running
- Review DirectEdit class
- Add utils.py::`simplify_url()` and refactor test_utils.py to use pytest format
- Removed `LocalClient.make_tree()`

NXDRIVE-1098: Auto-Lock does not work when there are orphans

---

docs/changes.md
nuxeo-drive-client/nxdrive/client/base_automation_client.py
nuxeo-drive-client/nxdrive/client/local_client.py
nuxeo-drive-client/nxdrive/client/remote_file_system_client.py
nuxeo-drive-client/nxdrive/direct_edit.py
nuxeo-drive-client/nxdrive/engine/dao/sqlite.py
nuxeo-drive-client/nxdrive/engine/engine.py
nuxeo-drive-client/nxdrive/engine/next/processor.py
nuxeo-drive-client/nxdrive/engine/next/simple_watcher.py
nuxeo-drive-client/nxdrive/engine/processor.py
nuxeo-drive-client/nxdrive/engine/watcher/local_watcher.py
nuxeo-drive-client/nxdrive/engine/watcher/remote_watcher.py
nuxeo-drive-client/nxdrive/engine/workers.py
nuxeo-drive-client/nxdrive/logging_config.py
nuxeo-drive-client/nxdrive/manager.py
nuxeo-drive-client/nxdrive/osi/__init__.py
nuxeo-drive-client/nxdrive/wui/dialog.py
nuxeo-drive-client/nxdrive/wui/settings.py
tools/posix/deploy_jenkins_slave.sh
tools/windows/deploy_jenkins_slave.ps1

- Force unicode in string comparisons
- Add -W error pytest option

NXDRIVE-1062: Fix macOS warnings

---

docs/changes.md
nuxeo-drive-client/nxdrive/direct_edit.py
nuxeo-drive-client/nxdrive/engine/activity.py
nuxeo-drive-client/nxdrive/engine/next/simple_watcher.py
nuxeo-drive-client/nxdrive/engine/processor.py
nuxeo-drive-client/nxdrive/engine/watcher/local_watcher.py
nuxeo-drive-client/nxdrive/engine/watcher/remote_watcher.py

Use @tooltip('Doing something') to surround a method with an action (displayed in the systray).

NXDRIVE-1091: Use Actions with a decorator

---

docs/changes.md
nuxeo-drive-client/nxdrive/engine/tracker.py

New dimensions sent to Google Analytics:
- Server hostname
- Server URL
- Server version
- Username

 NXDRIVE-1114: Add server information to analytics

---

docs/changes.md
nuxeo-drive-client/nxdrive/options.py
nuxeo-drive-client/nxdrive/updater.py
nuxeo-drive-client/nxdrive/utils.py
nuxeo-drive-client/nxdrive/wui/application.py
nuxeo-drive-client/tests/test_utils.py
requirements.txt
tools/deploy.sh
tools/jenkins/beta.groovy
tools/jenkins/packages.groovy
tools/jenkins/prod.groovy
tools/release.sh

I also modified jobs and scripts for the 3.0.6 beta + release.

NXDRIVE-1132: Security fix in the Crypto module (move to PyCryptodome)

---

docs/changes.md
tools/jenkins/tests.groovy
tools/posix/deploy_jenkins_slave.sh
tools/windows/deploy_jenkins_slave.ps1

For now our best solution is to purge the working directory everytime.

NXDRIVE-1173: Fix pip installation on Windows

---

docs/changes.md
docs/technical_changes.md
nuxeo-drive-client/nxdrive/engine/dao/sqlite.py
nuxeo-drive-client/nxdrive/engine/engine.py
nuxeo-drive-client/nxdrive/engine/processor.py
nuxeo-drive-client/nxdrive/engine/watcher/remote_watcher.py
nuxeo-drive-client/nxdrive/gui/folders_dialog.py
nuxeo-drive-client/nxdrive/gui/folders_treeview.py
nuxeo-drive-client/nxdrive/gui/status_dialog.py
nuxeo-drive-client/tests/test_model_filters.py

1/ There was an issue when selecting one document
at a given level: other docs at the same level
were synced too.
2/ There was another issue when the tree has more
than 3 levels. When selecting a document at the
level 4, its parents level 3 and level 2 were
updated correctly but not those of level 1 and
level 0.

NXDRIVE-1025: Filters issue with folders at the same tree level

---

nxdrive/manager.py
nxdrive/osi/darwin/darwin.py
nxdrive/utils.py
nxdrive/wui/application.py
tools/osx/drive/NuxeoFinderSync/FinderSync.swift
tools/osx/drive/NuxeoFinderSync/NuxeoFinderSync.entitlements
tools/osx/drive/NuxeoFinderSync/Socket.swift
tools/osx/drive/drive.xcodeproj/project.pbxproj

Getting FinderSync status through socket communication rather than a custom protocol URL

NXDRIVE-1179: Lost focus when FinderSync refreshes icons

---

docs/changes.md
nxdrive/updater/README.md
tools/deploy.sh
tools/jenkins/beta.groovy
tools/jenkins/packages.groovy
tools/release.sh
tools/versions.py

And add missing `SIGNTOOL_PATH` for Windows code signing (NXDRIVE-1204).

 NXDRIVE-1162: Update deploy scripts according to the new auto-update framework

---

nxdrive/data/i18n/i18n-de.json
nxdrive/data/i18n/i18n-es-ES.json
nxdrive/data/i18n/i18n-fr.json
nxdrive/data/i18n/i18n-he.json
nxdrive/data/i18n/i18n-id.json
nxdrive/data/i18n/i18n-it.json
nxdrive/data/i18n/i18n-ja.json
nxdrive/data/i18n/i18n-nl.json
nxdrive/data/i18n/i18n-sv-SE.json

NXDRIVE-1128: Automatic update of translations from Crowdin (all)

---

.gitignore
README.md
docs/changes.md
docs/deployment.md
ftest/custom/nuxeo.defaults
ftest/custom/nxserver/config/disable-libreoffice-config.xml
ftest/custom/nxserver/config/disable-picture-listener-config.xml
ftest/custom/nxserver/config/disable-renditions-config.xml
ftest/custom/nxserver/config/disable-several-converters-config.xml
ftest/custom/nxserver/config/disable-validation-config.xml
ftest/itests.xml
ftest/pom-8.10.xml
ftest/pom.xml
nxdrive/__init__.py
nxdrive/__main__.py
tools/linux/pom-debian.xml
tools/osx/README.md

Huge win on macOS only.
GNU/Linux, the win is almost nothing and on Windows we won between 10-20 minutes.

NXDRIVE-1212: Disable all server converters, enabled on-demand

---

docs/changes.md
docs/technical_changes.md
nxdrive/client/proxy.py
nxdrive/engine/engine.py
nxdrive/engine/queue_manager.py
nxdrive/engine/workers.py
nxdrive/manager.py
nxdrive/wui/dialog.py
requirements.txt
tests/test_proxy.py

About the clean-up: I checked the Sharp CPO source tree and removed slots will not impact them.

NXDRIVE-1068: Upgrade PyPAC from 0.8.1 to 0.9.1

---

nxdrive/data/qml/FileCard.qml
nxdrive/data/qml/NuxeoPopup.qml
nxdrive/data/qml/ShadowRectangle.qml
nxdrive/data/qml/Systray.qml
nxdrive/data/qml/SystrayMenu.qml

Also make the icon in the bottom right of the systray rotate when a sync is ongoing.

NXDRIVE-1289: The Qt5 QtGraphicalEffects plugin is missing after packaging

---

docs/changes.md
nxdrive/utils.py
requirements-tests.txt
tests/test_utils.py
tools/changelog.py
tools/osx/deploy_jenkins_slave.sh
tools/posix/deploy_jenkins_slave.sh

NXDRIVE-1294: Fix send2trash packaging error on macOS

---

docs/technical_changes.md
nxdrive/data/qml/GeneralTab.qml
nxdrive/data/qml/NuxeoSwitch.qml
nxdrive/gui/api.py
nxdrive/gui/application.py
nxdrive/manager.py
nxdrive/osi/windows/windows.py

Also allow to disable switches.

NXDRIVE-1249: Add "start on boot" option on windows

---

nxdrive/data/qml/AccountsTab.qml
nxdrive/data/qml/ConfirmPopup.qml
nxdrive/data/qml/IconLabel.qml
nxdrive/data/qml/Main.qml
nxdrive/data/qml/Systray.qml
nxdrive/gui/application.py
nxdrive/gui/systray.py

- Cursor changes shape when it is supposed to.
- Settings and conflicts windows are correctly brought to the front, even if already open.

NXDRIVE-1321: Small UI improvements

---

docs/changes.md
nxdrive/commandline.py

Usefull to override `is_frozen` for instance.

NXDRIVE-1339: Handle boolean parameters

---

docs/changes.md
requirements-dev.txt
requirements-tests.txt
requirements.txt

* Updated pyinstaller from the develop branch to 3.4.0
* Updated pypac from 0.10.1 to 0.11.0
* Updated pytest from 3.7.4 to 3.8.0
* Updated pytest-cov from 2.5.1 to 2.6.0
* Updated watchdog from 0.8.4 to 0.9.0 (removed watchdog3)

Ugraded pyinstaller, pypac, pytest, pytest-cov and watchdog

---

docs/changes.md

NXDRIVE-1342: Add the changelog entry

---

docs/changes.md
requirements-tests.txt
requirements.txt
tests/test_pytest_random.py
tools/jenkins/packages.groovy
tools/windows/deploy_jenkins_slave.ps1

Also:
- NXDRIVE-1391: Revert PyQt 5.11.3 upgrade

NXDRIVE-1390: Revert pytest 3.9.2 upgrade

---

docs/changes/4.0.1.md
nxdrive/client/local_client.py
nxdrive/engine/engine.py
nxdrive/objects.py
nxdrive/options.py
nxdrive/osi/darwin/darwin.py
nxdrive/report.py
nxdrive/translator.py

NXDRIVE-1431: Replace Try, Except, Pass with contextlib.suppress()

 NXDRIVE-1430: Use SHA256 for Note checksum

---

docs/changes/4.0.2.md
docs/configuration.md
nxdrive/commandline.py
nxdrive/data/i18n/i18n.json
nxdrive/gui/application.py
nxdrive/gui/systray.py
nxdrive/gui/view.py
nxdrive/osi/__init__.py
nxdrive/osi/darwin/darwin.py
nxdrive/osi/windows/registry.py
nxdrive/osi/windows/windows.py
nxdrive/translator.py
nxdrive/utils.py
tests/test_utils.py
tests/test_windows.py
tools/osx/drive/NuxeoFinderSync/FinderSync.swift
tools/windows/setup-admin.iss
tools/windows/setup-common.iss
tools/windows/setup.iss

Register the contextual menu with Python on Windows, to be able to modify it when the language settings change.

NXDRIVE-1385: Missing translations

---

docs/changes/4.0.3.md
nxdrive/engine/engine.py
nxdrive/manager.py
tests/test_behavior.py

Also:
- Fix a potential `manager.db` database corruption

NXDRIVE-1464: Fix a crash when the engine database is removed

---

nxdrive/__main__.py
nxdrive/client/local_client.py
nxdrive/engine/dao/sqlite.py
nxdrive/engine/processor.py
tests/__init__.py
tests/test_autolock.py
tests/test_options.py
tests/test_report.py
tests/test_synchronization.py
tests/test_utils.py

A first clean-up/bugfix PR. Will open one or more later.

NXDRIVE-1500: Review exception handling mechanisms (part 1)

---

docs/changes/4.1.0.md
nxdrive/engine/tracker.py
tools/posix/deploy_jenkins_slave.sh

Fixes https://sentry.io/nuxeo/nuxeo-drive/issues/854242407/

NXDRIVE-1520: Always send statistics, even if there is no engine

---

docs/changes/4.1.0.md
docs/deployment.md
nxdrive/client/local_client.py
nxdrive/direct_edit.py
nxdrive/engine/engine.py
nxdrive/engine/processor.py
nxdrive/engine/workers.py
nxdrive/gui/application.py
tests/conftest.py
tools/jenkins/packages.groovy
tools/linux/deploy_jenkins_slave.sh
tools/osx/deploy_jenkins_slave.sh
tools/posix/deploy_jenkins_slave.sh
tools/windows/deploy_jenkins_slave.ps1

And several fixes, see specific commits for details.

NXDRIVE-1530: Handle PermissionError when trashing documents

---

docs/changes/4.1.0.md
nxdrive/objects.py
tests/test_direct_edit.py

…llow direct edit on folderish documents

NXDRIVE-1519: Allow DirectEditing documents with the Folderish facet

---

docs/changes/4.1.0.md
nxdrive/__main__.py

NXDRIVE-1561: Display the fatal error screen only when necessary

---

nxdrive/__main__.py
nxdrive/engine/watcher/local_watcher.py

NXDRIVE-1563: Mypy fixes

---

.pre-commit-config.yaml
nxdrive/direct_edit.py
nxdrive/engine/tracker.py
nxdrive/osi/linux/linux.py
requirements.txt
tests/functional/test_tracker.py

Clean-up and little fixes not directly related to NXDRIVE-1542 but found when working on it.

NXDRIVE-1542: Part 1

---

ftest/custom/nuxeo.defaults
tools/jenkins/tests.groovy

This is far from optimal, but I prefer take time on JenkinsX (or OpenShift) instead of losing more time in a local version launched from maven with no possibility of improvements.

NXDRIVE-1565: Tweak the Nuxeo instance to handle more connections

---

nxdrive/engine/dao/sqlite.py
nxdrive/engine/processor.py
tests/__init__.py
tests/functional/test_db_backup.py
tests/old_functional/__init__.py
tests/old_functional/test_synchronization.py

* Moved `ensure_no_exception()` to the tests/ root.

NXDRIVE-1574: DAO has no lock when Drive attempts to restore a db backup

---

docs/changes/4.1.0.md
nxdrive/osi/windows/extension.py
nxdrive/osi/windows/windows.py

* Removed now usuned `get_filter_folders()` from `osi/windows/extension.py`.

NXDRIVE-1588: Fix folders watch on Windows

---

docs/changes/4.1.1.md
nxdrive/client/remote_client.py
nxdrive/engine/activity.py
nxdrive/gui/api.py
nxdrive/gui/application.py
tests/unit/test_action.py

* Add `Action.export()`.
* Remove all class attributes but 2 required ones.
* Add `tests/unit/test_action.py`.
Ultimately, this error should be gone forever:
```python
Fix AttributeError: 'FileAction' object has no attribute 'size'
```

NXDRIVE-1614: Improve the Action class implementation

---

docs/changes/4.1.1.md
docs/configuration.md
nxdrive/client/remote_client.py
nxdrive/options.py
requirements.txt

NXDRIVE-1613: Handle None chunk_size during upload

NXDRIVE-1611: Add chunk upload options

---

docs/changes/4.1.3.md
nxdrive/engine/dao/sqlite.py
tools/posix/deploy_jenkins_slave.sh
tools/windows/deploy_jenkins_slave.ps1

Also include:
* NXDRIVE-1634: Handle pair state moved-created as a conflict

NXDRIVE-1606: Publish ZIP'ed version of packages

---

tools/jenkins/beta.groovy
tools/jenkins/cleanup.groovy

Also trigger the cleanup job everyday at 08:00am.

NXDRIVE-1646: Remove 'ssh://' in URLs

---

nxdrive/data/i18n/i18n-de.json
nxdrive/data/i18n/i18n-es-ES.json
nxdrive/data/i18n/i18n-fr.json
nxdrive/data/i18n/i18n-he.json
nxdrive/data/i18n/i18n-id.json
nxdrive/data/i18n/i18n-it.json
nxdrive/data/i18n/i18n-ja.json
nxdrive/data/i18n/i18n-nl.json
nxdrive/data/i18n/i18n-sv-SE.json

Following c493311a4e3a6a91918d7f7464b2ed467a3f1a53.

NXDRIVE-1623: Automatic update of translations from Crowdin

---

.gitignore
docs/changes/4.1.3.md
nxdrive/__main__.py
nxdrive/data/i18n/i18n.json
nxdrive/gui/application.py
nxdrive/options.py
requirements-dev.txt
tools/windows/deploy_jenkins_slave.ps1

* Move private functions out of `MetaOptions`.
* Introduce `Application.add_qml_import_path()`.
* Added `Options.freezer`.
Also reverted the capture of STDIN and STDERR as there were encoding issues. It is not helpfull finally as we cannot see the console output in real time.

NXDRIVE-1632: [Windows] Prepare Nuitka switch

---

docs/changes/4.1.3.md
nxdrive/client/local_client.py
nxdrive/direct_edit.py
nxdrive/engine/activity.py
nxdrive/engine/engine.py
nxdrive/engine/processor.py
nxdrive/engine/watcher/local_watcher.py
nxdrive/exceptions.py
tests/cleanup.py
tests/integration/windows/conftest.py
tests/integration/windows/test_cli.py
tests/integration/windows/test_cli_sub_command.py
tests/integration/windows/utils.py
tests/old_functional/__init__.py
tests/old_functional/local_client_darwin.py
tests/old_functional/local_client_windows.py
tests/old_functional/test_direct_edit.py
tests/old_functional/test_local_changes_when_offline.py
tests/old_functional/test_local_creations.py
tests/old_functional/test_nxdrive_903.py
tests/old_functional/test_readonly.py
tests/old_functional/test_shared_folders.py
tests/old_functional/test_special_characters.py
tests/old_functional/test_synchronization_dedup.py

And NXDRIVE-1677: [Windows] Copy-paste and rename a local file while Drive is running does not work.

NXDRIVE-1670: [Windows] Fix failing tests

---

docs/changes/4.1.3.md
docs/dep/2019-01 Generate a unique test environment during the setup.md
mypy.ini
tests/conftest.py
tests/functional/conftest.py
tests/integration/windows/conftest.py
tests/unit/conftest.py
tests/unit/test_proxy.py
tools/posix/deploy_jenkins_slave.sh
tools/windows/deploy_jenkins_slave.ps1

NXDRIVE-1678: Re-run failed tests

---

.coveragerc
nxdrive/client/remote_client.py
tests/old_functional/test_direct_edit.py
tests/old_functional/test_local_changes_when_offline.py
tests/unit/test_utils.py
tools/jenkins/tests.groovy
tools/posix/deploy_jenkins_slave.sh
tools/windows/deploy_jenkins_slave.ps1

* Fix `test_direct_edit.py`
* Fix `test_group_changes.py`
* Fix `test_guess_server_url()`
* Mark `test_copy_paste_normal()` as random on Windows
Also:
* NXDRIVE-1686: Improve testing of `guess_server_url()`
* Re-reun failed tests at the end
* Fix coverage with xdist

NXDRIVE-1626: The CI is now back to blue!

---

docs/changes/4.1.3.md
nxdrive/commandline.py
nxdrive/data/qml/NewAccountPopup.qml
nxdrive/engine/blacklist_queue.py
nxdrive/gui/api.py
nxdrive/manager.py
nxdrive/utils.py
tests/unit/test_blacklist_queue.py
tools/posix/deploy_jenkins_slave.sh
tools/windows/deploy_jenkins_slave.ps1

Also renamed the function to the more generic `NXDRIVE-1674: Lower logging level of get_default_local_folder()`.

NXDRIVE-1674: Lower logging level of get_default_nuxeo_drive_folder()

---

docs/changes/4.1.4.md
nxdrive/client/local_client.py
nxdrive/direct_edit.py
nxdrive/engine/blacklist_queue.py
nxdrive/engine/dao/sqlite.py
nxdrive/engine/processor.py
tests/old_functional/test_local_creations.py
tests/unit/test_blacklist_queue.py

Also:
* Improved the `repr(FileInfo)` that I used to track the error.
* Finally fixed `test_blacklist_queue.py`.

NXDRIVE-1392: Processor loops when a file is not found and locally created

---

docs/changes/4.1.4.md
nxdrive/engine/activity.py
nxdrive/gui/application.py
nxdrive/utils.py
tests/functional/test_direct_edit.py
tests/old_functional/test_local_deletion.py
tests/old_functional/test_special_characters.py
tests/unit/test_action.py
tests/unit/test_pid_lock_file.py
tests/unit/test_proxy.py

NXDRIVE-1707: Set the UTF-8 encoding while opening/reading/writing text files.

NXDRIVE-1697: Expand test_action.py to cover 100% of activity.py

---

tools/jenkins/junit/merge.py
tools/jenkins/tests.groovy
tools/jenkins/tests_os.groovy
tools/posix/deploy_jenkins_slave.sh
tools/windows/deploy_jenkins_slave.ps1

NXDRIVE-1702: Disable concurrent builds on the same branch

NXDRIVE-1687: Handle reruns

---

.pre-commit-config.yaml
nxdrive/constants.py

Also use Python 3.7 for pre-commit (black).

NXDRIVE-1736: Refactor constants.py to update the set based on the OS

---

docs/changes/4.1.4.md
nxdrive/commandline.py
nxdrive/direct_edit.py
nxdrive/engine/engine.py
nxdrive/engine/tracker.py
nxdrive/gui/api.py
nxdrive/gui/application.py
nxdrive/gui/view.py
nxdrive/manager.py
nxdrive/osi/darwin/extension.py
nxdrive/osi/extension.py
nxdrive/osi/windows/windows.py
nxdrive/poll_workers.py
nxdrive/report.py
nxdrive/updater/base.py
tests/functional/conftest.py
tests/functional/test_behavior.py
tests/functional/test_direct_edit.py
tests/old_functional/__init__.py
tests/old_functional/test_local_creations.py
tests/old_functional/test_synchronization.py

* NXDRIVE-1740: Remove unpopular `Engine.get_errors()`

NXDRIVE-1735: Make Manager's engines public

---

docs/changes/4.1.4.md
nxdrive/client/remote_client.py
nxdrive/logging_config.py
nxdrive/utils.py
requirements.txt

* NXDRIVE-1774: Filter out urllib3 logging about "Certificate did not match..."

NXDRIVE-1773: Check the parent exists before trying to retrieve its details

---

docs/changes/4.1.4.md
nxdrive/client/remote_client.py
nxdrive/data/qml/SystrayTransfer.qml
nxdrive/direct_edit.py
nxdrive/engine/dao/sqlite.py
nxdrive/engine/engine.py
nxdrive/engine/processor.py
nxdrive/engine/watcher/local_watcher.py
nxdrive/gui/api.py
nxdrive/gui/view.py
nxdrive/objects.py
tests/old_functional/__init__.py
tests/old_functional/test_transfer.py

E.g: "10.0 MiB / 42.0 MiB [24%]" will be printed next to the (down|up)load icon in the system tray menu.
- The pause/resume icon is now hidden when checking the file integrity after a blob download.

NXDRIVE-1781: Display size details on progress of a download/upload

---

docs/changes/4.1.4.md
tools/posix/deploy_jenkins_slave.sh
tools/windows/deploy_jenkins_slave.ps1

NXDRIVE-1793: Update pip before installing dependencies

---

docs/changes/4.1.4.md
nxdrive/client/remote_client.py
nxdrive/data/qml/SystrayTransfer.qml
nxdrive/engine/engine.py
nxdrive/engine/watcher/local_watcher.py
tests/old_functional/test_direct_edit.py

Also:
- Tweak the upload 2nd step wording.
- Remove the upload lock to allow parallel uploads.

NXDRIVE-1714: Make the GUI responsive if too many FS events

---

docs/changes/4.1.4.md
tools/posix/deploy_jenkins_slave.sh
tools/windows/deploy_jenkins_slave.ps1

The change is not intended to win on the file sizes, but for information:
$ du -s dist-original
372216
$ du -s dist-stripped
369948

NXDRIVE-1760: Remove docstrings from packages

---

docs/changes/4.2.0.md
setup.cfg
tests/unit/test_pid_lock_file.py
tests/unit/test_utils.py

A second PR will follow with changes outside the tests.

NXDRIVE-1706: Expand utils.py tests coverage

---

docs/changes/4.2.0.md
nxdrive/utils.py

Improvements done while expanding `utils.py` tests.

NXDRIVE-1706: Improvements following new tests

---

docs/changes/4.2.0.md
docs/deployment.md
nxdrive/__main__.py
nxdrive/client/proxy.py
nxdrive/client/remote_client.py
nxdrive/constants.py
nxdrive/engine/activity.py
nxdrive/engine/engine.py
nxdrive/gui/api.py
nxdrive/gui/systray.py
nxdrive/notification.py
nxdrive/osi/__init__.py
nxdrive/osi/windows/windows.py
nxdrive/translator.py
nxdrive/updater/base.py
nxdrive/utils.py
requirements-tests.txt
setup.cfg
tools/posix/deploy_jenkins_slave.sh
tools/whitelist.py
tools/windows/deploy_jenkins_slave.ps1

First PR about code cleanup (Vulture).

NXDRIVE-1784: Code cleanup with Vulture

---

docs/changes/4.2.0.md
nxdrive/__main__.py
nxdrive/manager.py
nxdrive/options.py
tests/conftest.py
tests/functional/conftest.py
tests/integration/windows/conftest.py
tests/integration/windows/test_cli.py
tests/integration/windows/test_cli_sub_command.py

Also:
- NXDRIVE-1813: Fix missing f-string
- NXDRIVE-1814: Gracefull exit the application on CTRL+C

NXDRIVE-1741: [Windows] Add CLI sub-commands tests: bind-root and unbind-root

---

docs/changes/4.2.0.md
nxdrive/engine/engine.py

The sentence is not meant to frighten the user but only to give a hint for a potential fix on the server installation side.

NXDRIVE-1807: Improve startup SSL check wording

---

docs/changes/4.2.0.md
docs/deployment.md
docs/installer.md
tools/windows/deploy_jenkins_slave.ps1
tools/windows/setup-addons.iss
tools/windows/setup-admin.iss
tools/windows/setup-common.iss
tools/windows/unofficial_i18n/Swedish.isl

- NXDRIVE-1798: [Windows] Use the Inno Setup modern wizard style

NXDRIVE-1797: [Windows] Upgrade from Inno Setup 5.5.9 to 6.0.2

---

docs/changes/4.2.0.md
nxdrive/data/i18n/i18n-de.json
nxdrive/data/i18n/i18n-es-ES.json
nxdrive/data/i18n/i18n-fr.json
nxdrive/data/i18n/i18n-he.json
nxdrive/data/i18n/i18n-id.json
nxdrive/data/i18n/i18n-it.json
nxdrive/data/i18n/i18n-ja.json
nxdrive/data/i18n/i18n-nl.json
nxdrive/data/i18n/i18n-sv-SE.json
nxdrive/data/i18n/i18n.json
nxdrive/gui/application.py
nxdrive/manager.py
nxdrive/updater/README.md
nxdrive/updater/__init__.py
nxdrive/updater/base.py
nxdrive/updater/linux.py
tools/linux/deploy_jenkins_slave.sh
tools/scripts/check_update_process.py

And NXDRIVE-1821: Fix update from the systray after failing update.

NXDRIVE-1473: Add GNU/Linux support to the auto-updater

---

tests/old_functional/test_direct_edit.py

The bug was already fixed with NXDRIVE-1824, I just added a regression test.

NXDRIVE-1833: Add a test for multi editions of an unsynced document

---

tools/jenkins/packages.groovy
tools/linux/Dockerfile
tools/linux/deploy_jenkins_slave.sh
tools/linux/entrypoint.sh
tools/posix/deploy_jenkins_slave.sh
tools/windows/deploy_jenkins_slave.ps1

Also fixed artifacts retrieval from the docker image into the current Jenkins workspace.

NXDRIVE-1748: Fix branch name for alphas

---

docs/changes/4.2.1.md
nxdrive/engine/engine.py
nxdrive/utils.py

Related to e9ed5b658c9486ed0dd8f40a50fd36a9d1ffa991.

NXDRIVE-1867: Fix mypy issues following the update to mypy 0.730

---

docs/changes/4.2.1.md
nxdrive/client/local/base.py
nxdrive/client/local/darwin.py
nxdrive/client/local/linux.py
nxdrive/client/local/windows.py

And:
- NXDRIVE-279: Clean-up and add more comments

 NXDRIVE-1396: Update the changelog

---

nxdrive/data/qml/GeneralTab.qml
nxdrive/engine/engine.py
nxdrive/gui/application.py
tools/linux/deploy_jenkins_slave.sh

- NXDRIVE-1408: Use commit refs to fetch external files
- NXDRIVE-1807: Remove 2nd sentence if no exception printed

NXDRIVE-1408: Disable ineffective start on boot option on GNU/Linux

---

docs/changes/4.2.1.md
tools/windows/deploy_jenkins_slave.ps1

Apparently the move has to be done 2 days earlier ...

NXDRIVE-1884: [Windows] Update the timestamping service URL

---

docs/changes/4.2.1.md
nxdrive/client/remote_client.py
requirements.txt

- Upgraded nuxeo from 2.2.3 to 2.2.4

NXDRIVE-1871: Use the public Batch upload index

---

tools/jenkins/packages.groovy
tools/jenkins/test_volume.groovy
tools/jenkins/tests.groovy
tools/jenkins/tests_os.groovy
tools/osx/deploy_jenkins_slave.sh

That machine is old and very _very_ unstable for weeks.

NXDRIVE-1873: Remove TWANG from the QA/CI

---

docs/changes/4.2.1.md
docs/deployment.md
ftest/itests.xml
nxdrive/updater/base.py
tools/integration_tests_setup.py
tools/jenkins/packages.groovy
tools/posix/deploy_jenkins_slave.sh
tools/scripts/check_update_process.py
tools/windows/deploy_jenkins_slave.ps1

Check commit messages for details.

NXDRIVE-1710: Check the auto-updater before building a new version

---

docs/changes/4.2.1.md
tests/unit/test_utils.py
tools/integration_tests_setup.py
tools/whitelist.py

NXDRIVE-1905: [Windows] Fix test_normalize_and_expand_path()
It was failing due to the path alteration from cygwin.

NXDRIVE-1904: [Windows] Fix test_get_default_local_folder()

---

docs/changes/4.2.1.md
nxdrive/constants.py
nxdrive/direct_edit.py
nxdrive/engine/processor.py
tests/old_functional/common.py
tests/old_functional/test_local_move_folders.py

Also:
- Added a simple check for  NXDRIVE-987 (Unexpected full scans when synchronizing).

NXDRIVE-1886: Direct Edit should be robust against connection errors

---

docs/changes/4.4.1.md
nxdrive/constants.py
nxdrive/utils.py

A naive benchmark shows a 400% performance gain.

NXDRIVE-1981: Make safe_filename() more efficient

---

docs/changes/4.4.2.md
nxdrive/data/qml/AboutTab.qml
nxdrive/data/qml/AccountsComboBox.qml
nxdrive/data/qml/AccountsTab.qml
nxdrive/data/qml/Alert.qml
nxdrive/data/qml/ChannelPopup.qml
nxdrive/data/qml/Conflicts.qml
nxdrive/data/qml/DeletionPopup.qml
nxdrive/data/qml/FileCard.qml
nxdrive/data/qml/GeneralTab.qml
nxdrive/data/qml/IconLabel.qml
nxdrive/data/qml/Link.qml
nxdrive/data/qml/LogLevelPopup.qml
nxdrive/data/qml/NewAccountPopup.qml
nxdrive/data/qml/NuxeoButton.qml
nxdrive/data/qml/NuxeoComboBox.qml
nxdrive/data/qml/NuxeoInput.qml
nxdrive/data/qml/ProxyPopup.qml
nxdrive/data/qml/ScaledText.qml
nxdrive/data/qml/SettingsTab.qml
nxdrive/data/qml/Systray.qml
nxdrive/data/qml/SystrayFile.qml
nxdrive/data/qml/SystrayMenuItem.qml
nxdrive/data/qml/SystrayStatus.qml
nxdrive/data/qml/SystrayTransfer.qml
nxdrive/gui/application.py

Using a specified point size for every components eases how to deal with scaling everywhere.
Cleaner and proper patch that the previous one.

NXDRIVE-1900: Better patch to fix default zoom level (100%)

---

docs/changes/4.4.2.md
nxdrive/data/qml/AccountsTab.qml

NXDRIVE-1899: Make the account selection more obvious

---

nxdrive/utils.py
tests/conftest.py
tests/unit/test_utils.py

Also ignore socket leaks on macOS. It may need investigations.

NXDRIVE-1701: Use a LRU cache for pure functions

---

docs/changes/4.4.2.md
nxdrive/engine/watcher/local_watcher.py
nxdrive/engine/workers.py

"Such a small change for such a big impact."

NXDRIVE-2052: Optimize CPU consumption (and laptop batteries)

---

tools/jenkins/packages.groovy
tools/osx/deploy_jenkins_slave.sh
tools/osx/entitlements.plist
tools/osx/notarize.py

It works like a charm on my machine:
```bash
>>> [notarization] Uploading 'dist/nuxeo-drive-4.4.2.dmg'
(it may take a while)
>>> [notarization] Waiting status for 'c7634d12-fbdc-4178-bfc1-dd032a3e1224'
(it may take a while)
(new check in 30 seconds ... )
(new check in 30 seconds ... )
(new check in 30 seconds ... )
(new check in 30 seconds ... )
(new check in 30 seconds ... )
>>> Downloading the report to report-c7634d12-fbdc-4178-bfc1-dd032a3e1224.json
>>> [notarization] Done with success ᕦ(ò_óˇ)ᕤ
```

NXDRIVE-2041: Finalize the notarization process

---

docs/changes/4.4.2.md
nxdrive/data/qml/AccountsComboBox.qml
nxdrive/data/qml/AccountsTab.qml
nxdrive/data/qml/Systray.qml
nxdrive/engine/engine.py
nxdrive/gui/api.py
nxdrive/gui/view.py
tools/whitelist.py

- Update the account icon.
- Larger systray menu.
- Review the accounts dropdown name in Accounts.
- Smaller dropdown text in the systray menu.
- Add a left padding to the account icon in the systray.

NXDRIVE-2081: Several small UX improvements

---

tools/posix/deploy_jenkins_slave.sh
tools/windows/deploy_jenkins_slave.ps1

Updated `deploy_jenkins_slave.sh` and `deploy_jenkins_slave.ps1`.

NXDRIVE-1991: Fix pytest cache check script usage.

---

docs/changes/4.4.2.md
nxdrive/__main__.py
nxdrive/client/remote_client.py
nxdrive/direct_edit.py
nxdrive/engine/dao/sqlite.py
nxdrive/engine/dao/utils.py
nxdrive/engine/engine.py
nxdrive/engine/processor.py
nxdrive/engine/queue_manager.py
nxdrive/engine/watcher/local_watcher.py
nxdrive/engine/workers.py
nxdrive/fatal_error.py
nxdrive/gui/application.py
nxdrive/gui/folders_model.py
nxdrive/gui/folders_treeview.py
nxdrive/manager.py
nxdrive/objects.py
nxdrive/options.py
nxdrive/osi/darwin/files.py
nxdrive/osi/extension.py
nxdrive/osi/windows/windows.py
nxdrive/updater/base.py
nxdrive/updater/utils.py
tests/pytest_random.py
tools/changelog.py
tools/cleanup_application_tree.py
tools/osx/icon_extractor.py
tools/osx/notarize.py
tools/scripts/check_update_process.py

Something really new: all tests passed on the 3 Oses :)

NXDRIVE-2100: Clean-up code smells found by Sourcery

---

docs/changes/4.4.2.md
nxdrive/gui/application.py

I need it for NXDRIVE-2079. I separated the work to prevent a big "unreadable" PR :)

NXDRIVE-1640: Refactor simple QMessageBoxes

---

nxdrive/options.py

This change is trivial and just removes one indentation level.
Other PRs will come and use that part of the code.
I split PRs to ease reviews.

NXDRIVE-2079: Flatten MetaOptions.set()

---

docs/changes/4.4.2.md
nxdrive/feature.py
nxdrive/options.py
tests/functional/test_server_options.py

NXDRIVE-2103: [S3] Disable the feature until it is fully usable

NXDRIVE-2082: [Direct Transfer] Disable the feature until it is stable

---

nxdrive/direct_edit.py
tests/old_functional/test_direct_edit.py

NXDRIVE-1786: Remove the temporary file between attemps

---

.github/workflows/dead_code.yml
.github/workflows/lint.yml
.github/workflows/spell.yml
.github/workflows/style.yml
.github/workflows/translations.yml
.github/workflows/types.yml
.github/workflows/unit_tests.yml

Also set the desired Python minor version.

NXDRIVE-2169: Enforce Python 32-bit on the CI (it is Windows only)

---

docs/changes/4.4.4.md
nxdrive/data/qml/NewAccountPopup.qml
nxdrive/gui/api.py
nxdrive/utils.py

If the folder disappears like magic, just try all its parents.
Another small improvement: when selecting a folder on a different partition or moint point, the free disk space value is updated.

NXDRIVE-2162: Enforce disk space retrieval robustness

---

.github/workflows/crowdin.yml

See https://github.com/crowdin/github-action/issues/21 for details.

NXDRIVE-2175: Update the action to fix PR creation

---

docs/changes/4.4.4.md
nxdrive/constants.py
nxdrive/data/qml/SystrayMenu.qml
nxdrive/gui/application.py
nxdrive/gui/systray.py
nxdrive/state.py
tools/whitelist.py

It will be useful for the upcoming Direct Transfer refactoring.

NXDRIVE-2191: Introduce the State object

---

docs/changes/4.4.4.md
tests/old_functional/common.py
tests/old_functional/test_local_move_and_rename.py
tests/old_functional/test_local_move_folders.py
tests/old_functional/test_nxdrive_1033.py
tests/old_functional/test_nxdrive_947.py
tests/old_functional/test_special_characters.py

NXDRIVE-947 seems quite unstable though.

NXDRIVE-2200: Fix tests from test_special_characters.py

---

tests/old_functional/test_transfer.py

I focused on `test_direct_transfer.py` and completely forgot those ones ... So this is now done.

NXDRIVE-2190: Fix test_transfer.py

---

docs/changes/4.4.4.md
nxdrive/data/qml/DirectTransfer.qml
nxdrive/data/qml/IconLabel.qml
nxdrive/data/qml/Main.qml
nxdrive/data/qml/NuxeoProgressBar.qml
nxdrive/data/qml/TransferItem.qml
nxdrive/engine/dao/sqlite.py
nxdrive/gui/application.py
nxdrive/objects.py

- Change the cursor shape and icon color when it is disabled.
- Fix the synchronization when downloading files.
- Fix progress bars in the systray.
- Fix the Engine connection (it was connecting to the Conflicts window).

NXDRIVE-1926: Adjustments

---

docs/changes/4.4.4.md
nxdrive/engine/engine.py
nxdrive/engine/workers.py
nxdrive/gui/folders_dialog.py

FTR the GUI will still freeze. The next PR will help with that.

NXDRIVE-2220: Asynchronous planification of uploads

---

docs/changes/4.4.5.md
nxdrive/feature.py

The mix between `auto_updates` and `auto_update` was confusing.
Related question: https://answers.nuxeo.com/general/q/01628a2282ec4676b3b78a55dabbfc67/Nuxeo-Drive-Creating-config-ini-file

NXDRIVE-2248: Fix the Features documentation

---

nxdrive/data/i18n/i18n.json
nxdrive/data/qml/Systray.qml

The Nuxeo action icon tooltip has been updated.

NXDRIVE-2225: Update Nuxeo action icon tooltip

---

docs/changes/4.4.5.md
nxdrive/engine/tracker.py
nxdrive/gui/api.py
nxdrive/gui/application.py
nxdrive/manager.py
tests/functional/test_tracker.py

Send a simple "Hello world" event at startup.

NXDRIVE-2254: Always send primary metrics (app and OS versions)

---

.github/workflows/docker_build.yml

NXDRIVE-2259: Fix the workflow file

---

.github/workflows/docker_build.yml

Error response from daemon:
Get https://docker-private.packages.nuxeo/v2/:
dial tcp:
lookup docker-private.packages.nuxeo: no such host

NXDRIVE-2259: Fix the registry

---

.gitignore
docs/changes/4.4.5.md
nxdrive/client/uploader/direct_transfer.py
nxdrive/engine/dao/sqlite.py
nxdrive/engine/engine.py
nxdrive/engine/processor.py
nxdrive/engine/queue_manager.py
nxdrive/gui/folders_dialog.py
nxdrive/utils.py
tests/old_functional/test_direct_transfer.py

User stories:
- As a user, I can **upload** 1 **folder** and its content.
- As a user, I can **upload** several **folders** and their content.

NXDRIVE-2019: Enable folder uploads

---

docs/changes/4.4.5.md
nxdrive/client/remote_client.py
nxdrive/direct_edit.py
nxdrive/objects.py
tests/old_functional/test_direct_edit.py

With such documents, we loose the file integrity check and thus the conflicts detection.

NXDRIVE-2236: Should work with non-standard or empty digests

---

docs/changes/4.4.5.md
nxdrive/data/i18n/i18n.json
nxdrive/engine/engine.py
nxdrive/engine/processor.py
nxdrive/notification.py

A notification is now shown once a Direct Transfer sessionis complete.

NXDRIVE-2156: [Direct Transfer] Add a notification once transfer session is complete

---

docs/changes/4.4.5.md
nxdrive/client/uploader/__init__.py
nxdrive/client/uploader/direct_transfer.py
tools/skiplist.py

Try to prevent uploading again the blob when the `FileManager` failed.

NXDRIVE-2298: Improve large file upload resiliency

---

nxdrive/engine/engine.py
tests/old_functional/test_direct_transfer.py

The method has been fixed and tests have been updated.

NXDRIVE-2301: [Direct Transfer] Fix cancel_upload on Windows

---

nxdrive/engine/dao/sqlite.py

The `_adapt_path` method has been fixed and optimized.

NXDRIVE-2302: Fix SQlite path adapter

---

docs/changes/4.4.5.md
nxdrive/engine/engine.py
nxdrive/gui/folders_dialog.py
tests/old_functional/test_direct_transfer.py

When clicking on add files or add folders, Drive will now save
the last place accessed to open again there.

NXDRIVE-2289: [Direct Transfer] Remember the last selected local folder

---

docs/changes/4.4.6.md
nxdrive/logging_config.py
tools/skiplist.py

Set the envar before running the application and be ready for spam :)

NXDRIVE-2323: Add LOG_EVERYTHING envar to ... log everything

---

docs/changes/4.4.6.md
nxdrive/__main__.py

NXDRIVE-2338: Enable performance monitoring on Sentry

---

docs/changes/4.4.6.md
nxdrive/client/uploader/__init__.py
nxdrive/engine/dao/sqlite.py
nxdrive/objects.py
tools/skiplist.py

It is now a little bit more structured and the upload flow is really respected (the 3 steps).

NXDRIVE-2325: Refactor the upload flow

---

.github/workflows/integration_tests.yml
docs/changes/4.4.6.md
tools/posix/deploy_ci_agent.sh
tools/windows/deploy_ci_agent.ps1

For now, there is only Windows that has such tests.

NXDRIVE-2111: Use GitHub Actions to run integration tests

---

nxdrive/engine/dao/sqlite.py

For one reason or another, it happens that the `completed_on` field
of a session is set while at least one transfer is not finished.
This seems something related to concurrency at hight speed, so why
we didn't see it before.
Retry locked database #2, args=('UPDATE Sessions SET uploaded = ?, status = ? , completed_on = 2020-11-06 13:58:25 WHERE uid = ?', (13, 4, 21)), kwargs={}
Traceback (most recent call last):
File "nxdrive/engine/dao/sqlite.py", line 147, in execute
sqlite3.OperationalError: near "13": syntax error
Anyway, I simplified the logic to not rely on f-strings to prevent the SQL error
and to update the `completed_on` field only when revelant, i.e.: when the session is
actually completed.

NXDRIVE-2309: Fix a SQL syntax error

---

docs/changes/4.4.6.md
nxdrive/client/remote_client.py
nxdrive/client/uploader/__init__.py
nxdrive/client/uploader/direct_transfer.py
nxdrive/client/uploader/sync.py
nxdrive/direct_edit.py
nxdrive/engine/watcher/remote_watcher.py
nxdrive/objects.py
tests/old_functional/__init__.py
tests/old_functional/test_remote_client.py

Let the Python client handling mimetype stuff.
Mimetype tests were added into the Python client too.

NXDRIVE-2380: Clean-up mimetype code

---

.travis.yml
docs/changes/4.4.6.md
tools/versions.py

😢 but we need to move foward until https://github.com/pyinstaller/pyinstaller/pull/5232.

NXDRIVE-2399: Temporary stop releasing a GNU/Linux version

---

docs/changes/4.5.0.md
nxdrive/engine/dao/sqlite.py
nxdrive/engine/engine.py
nxdrive/engine/processor.py
nxdrive/gui/api.py
nxdrive/gui/application.py
tests/conftest.py
tests/unit/test_engine_dao.py

- NXDRIVE-2407: Display 10 documents into the conflicts window 
- NXPY-191: Fix tests

NXDRIVE-2406: Put duplicate documents into the ignore list

---

.github/dependabot.yml

NXDRIVE-2396: Allow more PRs

---

docs/changes/4.5.0.md
nxdrive/constants.py
nxdrive/data/i18n/i18n.json
nxdrive/data/qml/DirectTransfer.qml
nxdrive/data/qml/Main.qml
nxdrive/data/qml/TransferItem.qml
nxdrive/engine/dao/sqlite.py
nxdrive/engine/engine.py
nxdrive/gui/api.py
nxdrive/gui/application.py

Only chunked files are now displayed in the Direct Transfer Monitoring tab.

NXDRIVE-2432: [Direct Transfer] Only display chunked transfers into the Monitoring tab

---

docs/changes/4.5.0.md
nxdrive/client/proxy.py
nxdrive/client/remote_client.py
nxdrive/data/i18n/i18n.json
nxdrive/gui/api.py
tests/unit/test_proxy.py

Also prevent a crash when the proxy saved into the database is not good.

NXDRIVE-2435: Fix handling of direct PAC file input in proxy settings

---

tests/unit/test_proxy.py

And rename proxy test functions.

NXDRIVE-2435: Improve the PAC file reading resiliency

---

docs/changes/4.5.0.md
nxdrive/engine/engine.py
nxdrive/engine/processor.py
nxdrive/engine/tracker.py
nxdrive/engine/watcher/local_watcher.py
nxdrive/engine/watcher/remote_watcher.py
nxdrive/engine/workers.py
nxdrive/manager.py

- `account`.`count`
- `server`.`protocol`
- `sync`.`error`
- `sync`.`operation`
- `sync`.`skip`

NXDRIVE-2439: Add more metrics to understand several keypoints

---

docs/changes/4.5.0.md
nxdrive/client/remote_client.py
nxdrive/client/uploader/direct_transfer.py
nxdrive/engine/engine.py
nxdrive/engine/tracker.py
tests/old_functional/__init__.py

- `direct_transfer`.`session_items`

NXDRIVE-2439: Add a metrics for Direct Transfer

---

docs/changes/4.5.1.md
nxdrive/client/uploader/__init__.py
nxdrive/client/uploader/direct_transfer.py
nxdrive/engine/activity.py
nxdrive/engine/dao/sqlite.py
nxdrive/engine/processor.py
nxdrive/gui/view.py
tests/old_functional/test_direct_transfer.py

NXDRIVE-2394: [Direct Transfer] Handle multiple transfers on same file

---

docs/changes/4.5.1.md
nxdrive/utils.py

See https://github.com/nuxeo/nuxeo-drive/security/code-scanning/1.

NXDRIVE-2472: Fix a security issue when retrieving a SSL certificate

---

nxdrive/data/qml/AccountsTab.qml
nxdrive/data/qml/ChannelPopup.qml
nxdrive/data/qml/ConfirmPopup.qml
nxdrive/data/qml/DeletionPopup.qml
nxdrive/data/qml/LogLevelPopup.qml
nxdrive/data/qml/NewAccountPopup.qml
nxdrive/data/qml/NuxeoButton.qml
nxdrive/data/qml/NuxeoInput.qml
nxdrive/data/qml/ProxyPopup.qml
nxdrive/gui/application.py

Buttons colors have been aligned on the Nuxeo guidelines.

NXDRIVE-2354: Align buttons

---

docs/changes/4.5.1.md
nxdrive/data/i18n/i18n.json
nxdrive/data/qml/GeneralTab.qml
nxdrive/data/qml/Systray.qml
nxdrive/gui/application.py
nxdrive/gui/view.py
nxdrive/manager.py

Direct Transfer icon button in the systray is now refreshed on feature state change.

NXDRIVE-2413: Refresh the GUI after a feature state has changed

---

nxdrive/gui/folders_dialog.py

Also:
- Reduce options height: they seem more "grouped" now.
- Reduce the new folder input width.

NXDRIVE-2329: [Direct Transfer] Give more space to the QTreeView

---

docs/changes/4.5.1.md
nxdrive/engine/dao/sqlite.py

SQLite will automatically handle those data thanks to the adapter.

NXDRIVE-2489: Remove useless manual Path -> str calls

---

nxdrive/engine/watcher/local_watcher.py
tests/old_functional/test_direct_edit.py

Also:
-  NXDRIVE-2517: Fix `test_attachments()`

NXDRIVE-2140: Fix file local update not synced

---

docs/changes/5.0.1.md
nxdrive/data/i18n/i18n.json

A small change to remove disambigu between the option on the Settings and the feature.

NXDRIVE-2551: Reword the auto-update option on the Settings screen

---

docs/changes/5.0.1.md
nxdrive/client/uploader/__init__.py
nxdrive/objects.py
tests/functional/conftest.py
tests/functional/test_bind_server.py
tests/functional/test_db_backup.py
tests/functional/test_direct_edit.py
tests/functional/test_engine.py
tests/functional/test_remote_client.py
tests/old_functional/common.py

- NXDRIVE-2552: Pass a custom callback for token renewal on S3

NXDRIVE-2553: Adapt the code following recent Python client changes

---

docs/changes/5.0.1.md
nxdrive/engine/tracker.py

The custom dimension 13 will contain the machine type (arm64|i386|x86_64|...).

NXDRIVE-2557: Add a Google Analytics metric for the machine type

---

docs/changes/5.1.1.md
nxdrive/engine/engine.py
tests/functional/test_engine.py

NXDRIVE-2587: Skip conflict resolution on non-standard digest

---

docs/changes/5.1.1.md
nxdrive/updater/__init__.py
nxdrive/updater/base.py
tests/functional/test_updater.py

NXDRIVE-2589: Lower logging level of installer integrity check failure

---

docs/changes/5.1.1.md
nxdrive/options.py
tests/unit/test_options.py
tools/windows/deploy_ci_agent.ps1

Also removed Nuitka code unused since several years. Actually it was present for testing at the time we had issues on Windows with Windows session usernames and unicode characters. Those issues are fixed since a while in PyInstaller.

NXDRIVE-2600: Improve options.py coverage

---

docs/changes/5.1.2.md
nxdrive/data/i18n/i18n.json
nxdrive/direct_edit.py
nxdrive/gui/application.py
tests/functional/conftest.py
tests/functional/test_direct_edit.py

NXDRIVE-2621: Handle HTTPError 404 (Not Found) errors

---

docs/changes/5.1.2.md
nxdrive/options.py
tests/unit/test_commandline.py

NXDRIVE-2622: Fix parsing of paths in local configuration file

---

docs/changes/5.1.2.md
nxdrive/engine/processor.py

NXDRIVE-2624: Handle HTTP 408 errors (Request Timeout)

---

docs/changes/5.1.2.md
nxdrive/utils.py
tests/unit/test_utils.py

NXDRIVE-2635: [Direct Transfer] Do not follow symlinks

---

docs/changes/5.2.1.md
nxdrive/data/i18n/i18n.json
nxdrive/engine/engine.py
nxdrive/exceptions.py
nxdrive/gui/api.py
nxdrive/manager.py

NXDRIVE-2644: Check extended attributes support when adding account

---

docs/changes/5.2.1.md
nxdrive/engine/dao/sqlite.py

NXDRIVE-2645: Gracefully handle processor releasing issues

---

docs/changes/5.2.1.md
nxdrive/engine/dao/sqlite.py
tests/unit/test_proxy.py

NXDRIVE-2217: New migration to add the PRAGMA

---

docs/changes/5.2.2.md
nxdrive/dao/base.py
nxdrive/engine/queue_manager.py
tools/deps/requirements-tests.txt

NXDRIVE-2682: Fix mypy issues following the update to mypy 0.901

---

docs/changes/5.2.2.md
nxdrive/gui/api.py

NXDRIVE-2683: Ignore incomplete custom protocol URL token requests

---

docs/changes/5.2.2.md
tools/windows/scripts/setup-dev-env.bat

NXDRIVE-2685: [Windows] Create setup dev env BAT script

---

docs/changes/5.2.2.md
docs/deployment.md
tools/deps/requirements-tests.txt
tools/posix/deploy_ci_agent.sh

It is no more needed to deal with manual CLI calls for managing the virtual environment (GNU/Linux and macOS).

NXDRIVE-2688: Add virtual environment facilities to deploy scripts

---

.github/dependabot.yml
.github/workflows/alpha_cleanup.yml
.github/workflows/beta_to_prod.yml
.github/workflows/codeql-analysis.yml
.github/workflows/crowdin.yml
.github/workflows/dead_code.yml
.github/workflows/docker_build.yml
.github/workflows/functional_tests.yml
.github/workflows/integration_tests.yml
.github/workflows/lint.yml
.github/workflows/spell.yml
.github/workflows/style.yml
.github/workflows/translations.yml
.github/workflows/types.yml
.github/workflows/unit_tests.yml
docs/changes/5.2.2.md

NXDRIVE-2691: Use proper job names in GitHub workflows

---

docs/changes/5.2.2.md
nxdrive/direct_edit.py
tests/old_functional/test_direct_edit.py

NXDRIVE-2142: Sanitize the filename in Direct Edit

---

docs/changes/5.2.2.md
nxdrive/gui/api.py

NXDRIVE-2701: Lower logging level of unknown connection error

---

.github/workflows/functional_tests.yml
.github/workflows/release.yml
.github/workflows/unit_tests.yml
docs/changes/5.3.0.md
tests/unit/test_custom_metrics.py
tools/deps/requirements-tests.txt

Update macos version from mac-latest to mac-10.15

Dependabot/pip/tools/deps/faker 11.3.0

---

nxdrive/manager.py

NXDRIVE-2758: fix drive announcement on boot.

NXDRIVE-2758: fix drive announcement on boot.

---

tools/posix/deploy_ci_agent.sh

zlib and _struct not getting created.

NXDRIVE-2781:Appimage-build-fix

---

nxdrive/client/remote_client.py
nxdrive/client/uploader/__init__.py

NXDRIVE-2782: Fix synchronization of files whose name contains a quote on MS Windows

NXDRIVE-2782: Fix synchronization of files whose name contains a quote on MS Windows

---

docs/changes/5.3.0.md

NXDRIVE-2794: Release Drive beta 5.3.0

NXDRIVE-2794: Release Drive beta 5.3.0

---

docs/changes/5.3.1.md
nxdrive/direct_edit.py
tests/functional/test_direct_edit.py

NXDRIVE-2796: Remove the .dl folder after using Direct Edit on a document

NXDRIVE-2796: Remove the .dl folder after using Direct Edit on a document

---

docs/changes/5.3.2.md
nxdrive/gui/view.py
nxdrive/options.py
tests/functional/test_view.py

NXDRIVE-2767: Clean up systray menu

NXDRIVE-2767: Clean up systray menu

---

docs/changes/5.3.2.md

NXDRIVE-2851: Release Beta 5.3.2

NXDRIVE-2851: Release Beta 5.3.2

---

docs/changes.md
docs/changes/5.3.3.md
nxdrive/__init__.py

NXDRIVE-2851: Bump the version number to 5.3.3

NXDRIVE-2851: Bump the version number to 5.3.3

---

docs/changes/5.3.3.md
tools/deps/requirements.txt

Update nuxeo python client version to 6.1.1

NXDRIVE-2883: Update python-client latest version to 6.1.1

---

docs/changes.md
docs/changes/5.5.0.md
nxdrive/__init__.py

NXDRIVE-2876: Bump the version number to 5.4.0

NXDRIVE-2876: Bump the version number to 5.5.0

---

.github/workflows/functional_tests.yml
.github/workflows/functional_tests_2023.yml
.github/workflows/integration_tests.yml
.github/workflows/unit_tests.yml
docs/changes/5.5.0.md

NXDRIVE-2938: Update token for codecov

NXDRIVE-2938: Update token for codecov

---

docs/changes/5.5.0.md

NXDRIVE-2890: List all pending documents for review

NXDRIVE-2890: List all pending documents for review

---

.github/workflows/release.yml
docs/changes/5.5.0.md
tools/windows/deploy_ci_agent.ps1

NXDRIVE-2941: Update the release process to sign windows exe to limit signature usage

NXDRIVE-2941: Update the release process to sign windows exe to limit signature usage

---

docs/changes.md
docs/changes/5.5.0.md
nxdrive/__init__.py

NXDRIVE-2917: Bump the version number to 5.5.0

NXDRIVE-2917: Bump the version number to 5.5.0

---

docs/changes/5.4.1.md
nxdrive/data/qml/TaskManager.qml
nxdrive/gui/application.py
nxdrive/gui/view.py

NXDRIVE-2943: Fix Tabbar behaviour and change "No tasks available" Lable for Task Window

NXDRIVE-2943: Fix Tabbar behaviour and change "No tasks available" Lable for Task Window

---

docs/changes/5.5.0.md
nxdrive/data/i18n/i18n.json
nxdrive/data/qml/Main.qml
nxdrive/data/qml/tasksManager/TaskListItem.qml
nxdrive/data/qml/tasksManager/TaskManager.qml
nxdrive/gui/api.py
nxdrive/gui/application.py
nxdrive/gui/view.py
tests/functional/test_api.py

NXDRIVE-2948: Add translations to hardcoded strings and refractor the code

NXDRIVE-2948: Add translations to hardcoded strings and refractor the code

---

docs/changes/5.5.0.md

NXDRIVE-2946: Release beta 5.5.0

NXDRIVE-2946: Release beta 5.5.0

---

docs/changes.md
docs/changes/5.5.1.md
nxdrive/__init__.py

NXDROVE-2946: Bump the version number to 5.5.1

NXDROVE-2946: Bump the version number to 5.5.1

---

tools/deps/requirements.txt

Reverts nuxeo/nuxeo-drive#4946

Revert "Bump pyqt5-qt5 from 5.15.2 to 5.15.14 in /tools/deps"
