nuxeo-drive-client/nxdrive/utils.py

Windows doesn't change creation time if file is deleted and then created quickly. This may create multiple instances of running nxdrives.

NXDRIVE-356: Fixed pid file check error

---

nuxeo-drive-client/nxdrive/wui/conflicts.py

When sync fails for locally_created documents the last_remote_modifier is None. So the call ``self._engine.get_user_full_name(state.last_remote_modifier)`` will raise exception. This will result in empty conflict/error window.

NXDRIVE-393: Avoid exception when last_remote_modifier is None

---

nuxeo-drive-client/nxdrive/manager.py
nuxeo-drive-client/nxdrive/wui/settings.py

@loopingz 
Bonjour,
I have updated the code to return a value from ```set_proxy_settings``` under settings.py. And I have overriden the same method under ```CPOManager``` class to validate the proxy, which handles the result that the UI projects to the user. So inorder to return the value(Valid or Invalid) I had to change this part.
CPO side code changes have been already made. 
https://github.com/nuxeo/sharp-cpo-clients/pull/154

NXDRIVE-438: Update set proxy to return string

---

nuxeo-drive-client/nxdrive/client/base_automation_client.py

Need to catch error "Unable to find batch associated with id ..." in execute method too. In addition need to check error has value.
Please review. Thanks.

NXDRIVE-556: Catch unable to find batch exception in execute too

---

nuxeo-drive-client/nxdrive/client/local_client.py

NXDRIVE-707: Windows: bug test_synchronize_special_filenames (sync timeout)
Explanation: `os.tempnam` returns a string with a possible available temporary path, `tempfile.mkstemp` creates and opens a temporary file. As the file is opened in memory, Windows has issue with that.
Concerning the security issue with `os.tempnam`, it should be good as we just need a temporary name.

Revert "NXDRIVE-702: fix use of deprecated and insecure os.tempnam()"

---

nuxeo-drive-client/nxdrive/client/local_client.py
nuxeo-drive-client/tests/test_long_path.py

A rewrite of #133 to match with CI changes.

NXDRIVE-689: Handle long paths name on setup on Windows (#133)

---

nuxeo-drive-client/tests/mac_local_client.py
nuxeo-drive-client/tests/test_local_client.py
nuxeo-drive-client/tests/win_local_client.py

Also:
- Optimize imports
- Several PEP8 fixes
Real changes starts at ligne 245 in test_local_client.py. I renamed the class `TestLocalClient` to `StubLocalClient` and added two classes that inherit of it. Tests are declared into that class.
Then to test OS specific operations (like Explorer or OSX File Manager), the class `TestLocalClientSimulation` overrides few test methods to explicitely fail when needed. And the class `TestLocalClientNative` uses the native/normal `LocalClient` as Drive would do to test Drive operations.
Finally GNU/Linux does not need to test specific behaviors because it uses native LocalClient by default.

NXDRIVE-742: Add native LocalClient tests to simulate Drive operations

---

.landscape.yml

Severity is at the higher level, so our score might drop drastically :)
For now, I did not enable docstring and tests warnings as it will make to much noise.

NXDRIVE-754: Create the landscape.io configuration file

---

nuxeo-drive-client/tests/test_synchronization.py

This is temporary and I will have a look in the next sprint. We decided to skip it to have all tests OK on Jenkins, finally. And then to proceed to more important work.

NXDRIVE-756: Skip the test for now to have green icon on Windows slaves

---

nuxeo-drive-client/tests/common_unit_test.py
nuxeo-drive-client/tests/test_conflicts.py
nx_cx_Freeze/__init__.py

It is temporary for we can work on other issues while the fix will be ready.

NXDRIVE-766: Skip temporary test_conflicts.py failing due to NXP-21854

---

nuxeo-drive-client/tests/test_aaa.py

With this commit, we will have a new line printed after test initializations:
>>> Launching the tests suite
Test session starts (platform: linux2, Python 2.7.13, pytest 3.0.6, pytest-sugar 0.8.0)
run-last-failure: rerun last 1 failures first
rootdir: nuxeo-drive, inifile: 
plugins: sugar-0.8.0, cov-2.4.0
check: time.sleep() average error is 0.22ms
To ensure failing tests with sync timeout are related or not to this function.

NXDRIVE-767: Add time.sleep() average error test file

---

nuxeo-drive-client/tests/test_versioning.py

Following https://jira.nuxeo.com/browse/NXP-21275, we can no more change the versioning delay on the fly for the tests.

NXDRIVE-773: Remove test case relying on the deprecated NuxeoDrive.SetVersioningOptions operation

---

nuxeo-drive-client/nxdrive/client/local_client.py
nuxeo-drive-client/tests/test_synchronization.py

The cause was that the path + file name was >260 characters in the last `remote.update()` operation.
As this test uses the `WindowsLocalClient`, the prefix for long path (`\\?\`) was removed.
And so, the test failed because it could not find the path anymore.

NXDRIVE-756: Fix test_synchronize_special_filenames on Windows

---

tools/jenkins/beta.groovy

I think this will fix the current problem:
[Drive-beta] Running shell script
+ tools/release.sh --create
>>> [beta 2.3.331] Creating the commit
[detached HEAD c98220f5] Release 2.3.331
1 file changed, 1 insertion(+), 1 deletion(-)
error: src refspec master does not match any.
error: failed to push some refs to 'https://github.com/nuxeo/nuxeo-drive.git'
Source: https://github.com/dalalv/jenkinsfiles/blob/master/jenkinsfile-push-to-git-repo

NXDRIVE-571: Work on a local branch to allow git push

---

nuxeo-drive-client/tests/test_local_move_folders.py
nuxeo-drive-client/tests/test_shared_folders.py

Should fix the random bug observed in test_local_changes_while_unbinded, see https://qa.nuxeo.org/jenkins/view/Drive/job/Drive/job/FT-drive/job/task-NXDRIVE-808-try-no-random-bugs-bypass/7/consoleFull.

fix-NXDRIVE-646-NXDRIVE-647-wait-sync-after-rebind

---

nuxeo-drive-client/nxdrive/__init__.py
nuxeo-drive-client/nxdrive/client/common.py
nuxeo-drive-client/nxdrive/client/local_client.py
nuxeo-drive-client/nxdrive/client/remote_document_client.py
nuxeo-drive-client/nxdrive/commandline.py
nuxeo-drive-client/nxdrive/direct_edit.py
nuxeo-drive-client/nxdrive/engine/engine.py
nuxeo-drive-client/nxdrive/manager.py
nuxeo-drive-client/tests/common_unit_test.py
nuxeo-drive-client/tests/test_local_client.py

To define custom prefixes/suffixes, use this kind of `config.ini`:
[DEFAULT]
env=custom
[custom]
ignored-prefixes =
IGNOREME-
IGNOREME-
no_release-
ignored-suffixes = .bak
Custom prefixes/suffixes will be appended to the default ones.

NXDRIVE-158: Allow configuring ignored prefixes and suffixes in the local configuration

---

nuxeo-drive-client/nxdrive/commandline.py
nuxeo-drive-client/nxdrive/engine/tracker.py
nuxeo-drive-client/nxdrive/manager.py
tools/jenkins/packages.groovy
tools/osx/deploy_jenkins_slave.sh

Curiously, when Drive is built with Esky, as usual, `locale.getdefaultlocale()` returns `(None, None)`.
Don't know what is the cause, but for now we just bypass the error.

NXDRIVE-866: Fix startup on macOS

---

nuxeo-drive-client/nxdrive/client/common.py
nuxeo-drive-client/nxdrive/client/local_client.py
nuxeo-drive-client/nxdrive/engine/processor.py
nuxeo-drive-client/nxdrive/engine/watcher/local_watcher.py

The partial revert keeps the method signature even if `no_digest` is not used anymore. We will wait 2-3 months and see if bugs come before deciding to remove it.
The other part of the patch filter `ignored_suffixes` "at the root", which is a good thing.

NXDRIVE-712: Conflict detection during multiple backups (saves) in a short time interval

---

nuxeo-drive-client/nxdrive/__init__.py
nuxeo-drive-client/nxdrive/client/local_client.py
nuxeo-drive-client/nxdrive/engine/dao/sqlite.py
nuxeo-drive-client/nxdrive/engine/processor.py
nuxeo-drive-client/nxdrive/engine/watcher/remote_watcher.py
nuxeo-drive-client/tests/manual/nxdrive-881.py

The previous fix was fixing this issue but failed elsewhere. So this is a new approach that passes all tests. I keeped the `mark_unknown` keyword removal from the previous patch, it seems to be useless now.
There are a couple of cleanup/fixes too, reported by SonarPython.

NXDRIVE-881: Handle folder remote rename when doing full remote scan

---

nuxeo-drive-client/nxdrive/client/common.py

It will be usefull for every one and we need it for OTEIS right know.

NXDRIVE-918: Ignore .bak files

---

nuxeo-drive-client/nxdrive/data/ui5/activity.html
nuxeo-drive-client/nxdrive/data/ui5/conflicts.html
nuxeo-drive-client/nxdrive/data/ui5/debug.html
nuxeo-drive-client/nxdrive/data/ui5/js/ndrive-conflicts.js
nuxeo-drive-client/nxdrive/data/ui5/js/ndrive-settings.js
nuxeo-drive-client/nxdrive/data/ui5/js/ndrive.js
nuxeo-drive-client/nxdrive/data/ui5/modal.html
nuxeo-drive-client/nxdrive/data/ui5/network_error.html
nuxeo-drive-client/nxdrive/data/ui5/settings.html
nuxeo-drive-client/nxdrive/data/ui5/systray.html
nuxeo-drive-client/nxdrive/data/ui5/templates/conflicts-content.html
nuxeo-drive-client/nxdrive/data/ui5/templates/debug-content.html
nuxeo-drive-client/nxdrive/data/ui5/templates/settings-account.html
nuxeo-drive-client/nxdrive/data/ui5/templates/settings-accounts.html
nuxeo-drive-client/nxdrive/data/ui5/templates/settings-advanced.html
nuxeo-drive-client/nxdrive/data/ui5/templates/settings-content.html
nuxeo-drive-client/nxdrive/data/ui5/templates/systray-bottom.html
nuxeo-drive-client/nxdrive/data/ui5/templates/systray-content.html
nuxeo-drive-client/nxdrive/data/ui5/templates/systray-notifications.html

Fixes for several errors/warnings:
- HTML - Redundant default attribute
- JS - Variables should be declared explicitly
- JS - Remove use of eval()
- XML - Collapses empty tags
- Use HTTPS for Google Analytics script

NXDRIVE-929: Cleanup JavaScript/HTML code

---

docs/changes.md
docs/deployment.md
ftest/itests.xml
ftest/pom-8.10.xml
ftest/pom.xml
nuxeo-drive-client/nxdrive/engine/processor.py
nuxeo-drive-client/nxdrive/engine/watcher/local_watcher.py
nuxeo-drive-client/nxdrive/engine/watcher/remote_watcher.py
nuxeo-drive-client/tests/test_local_move_and_rename.py
nuxeo-drive-client/tests/test_permission_hierarchy.py
tools/windows/deploy_jenkins_slave.ps1

Introduced with NXDRIVE-836, actions taken on local deletion of read-only documents was not the same on Unix and Windows. This patch fixes that behavior.
Also:
- On Windows, use `QT_PATH` and `MINGW_PATH` envars to facilitate tests.

NXDRIVE- 956: Uniformize actions on local deletion of read-only documents

---

docs/changes.md
nuxeo-drive-client/nxdrive/client/base_automation_client.py
nuxeo-drive-client/nxdrive/data/ui5/css/ndrive.css
nuxeo-drive-client/nxdrive/data/ui5/js/ndrive-settings.js
nuxeo-drive-client/nxdrive/data/ui5/templates/settings-about.html
nuxeo-drive-client/nxdrive/engine/engine.py
nuxeo-drive-client/nxdrive/wui/settings.py

A simple check on the current action (here: unbinding) to prevent several calls to `unbind_server()`.

NXDRIVE-963: Crash when deleting an account

---

docs/changes.md
tools/deploy.sh
tools/jenkins/beta.groovy
tools/release.sh

If the packages job fails, we remove the newly created tag.

NXDRIVE-992: Rollback release tag on Drive-package job failure

---

docs/changes.md
tools/checksums.txt
tools/jenkins/packages.groovy
tools/jenkins/tests-8.10.groovy
tools/jenkins/tests.groovy
tools/windows/deploy_jenkins_slave.ps1

I also bypassed the use of get-pip.py for pip installation as it fails often in our Windows slaves.

NXDRIVE-991: Upgrade Python from 2.7.13 to 2.7.14

---

.gitignore
docs/changes.md
docs/technical_changes.md
nuxeo-drive-client/nxdrive/client/local_client.py
nuxeo-drive-client/nxdrive/direct_edit.py
nuxeo-drive-client/nxdrive/engine/dao/sqlite.py
nuxeo-drive-client/nxdrive/engine/next/simple_watcher.py
nuxeo-drive-client/nxdrive/engine/processor.py
nuxeo-drive-client/nxdrive/engine/watcher/local_watcher.py
nuxeo-drive-client/nxdrive/engine/watcher/remote_watcher.py
nuxeo-drive-client/nxdrive/manager.py
nuxeo-drive-client/nxdrive/utils.py
tools/posix/deploy_jenkins_slave.sh

Some cleanup too:
*  Use `%r` instead of `%s` for paths in logs
*  Jenkins: Update pyenv to take into account new Python versions (to fix Python version not found on our slaves)
*  Remove unused `LocalClient.is_osxbundle()`
*  Use `self` instead of creating a new `LocalClient` objects
*  Removed `Manager.is_updated()`
*  Check for `atmp****` pattern in lower case (AutoCAD)
*  Manager: move SSL check into the new `_bypass_https_verification()`
*  Little refactor of `Manager.get_system_pac_url()`
*  Moved `normalize_event_filename()` to utils.py

NXDRIVE-995: Prevent renaming from 'folder' to 'folder ' on Windows

---

docs/changes.md
nuxeo-drive-client/nxdrive/__init__.py
nuxeo-drive-client/nxdrive/client/local_client.py
nuxeo-drive-client/nxdrive/engine/engine.py
nuxeo-drive-client/nxdrive/engine/queue_manager.py

Mostly a review of `is_processing_file()` to reduce conditions call.
Also
* Fix `LocalClient.get_path()` to use `str.partition()` that prevents `IndexError`s and simplify the code.

NXDRIVE-1011: Cleanup queue_manager.py

---

docs/changes.md
docs/technical_changes.md
nuxeo-drive-client/nxdrive/client/__init__.py
nuxeo-drive-client/nxdrive/client/base_automation_client.py
nuxeo-drive-client/nxdrive/client/local_client.py
nuxeo-drive-client/nxdrive/engine/watcher/remote_watcher.py
nuxeo-drive-client/nxdrive/utils.py
nuxeo-drive-client/nxdrive/wui/settings.py
nuxeo-drive-client/tests/common_unit_test.py
nuxeo-drive-client/tests/test_local_client.py
nuxeo-drive-client/tests/test_remote_changes.py
nuxeo-drive-client/tests/test_remote_document_client.py
nuxeo-drive-client/tests/test_utils.py
tools/posix/deploy_jenkins_slave.sh
tools/windows/deploy_jenkins_slave.ps1

- Cache operations and parameters.
- Do not call fetch_api().
- By default, do not check parameters in fetch_api().
- Add check_access() and server_reachable().
Tests for server_reachable() were added to the Python client.
Also:
- Stronger utils.py guess_server_url()
- Remove spaces from utils.py DEVICE_DESCRIPTIONS
- Use sys.platform when no device description found
- Encoding fix and test for LocalClient.get_path()

NXDRIVE-1006: Improve calls to /site/automation

---

docs/changes.md
nuxeo-drive-client/nxdrive/__init__.py
tools/release.sh

Fix bad bash comparison in tools/release.sh to prevent PyPi upload in case of bad Python version.

NXDRIVE-1030: Bugfix release 2.5.8

---

docs/changes.md
ftest/pom.xml
nuxeo-drive-client/nxdrive/__init__.py
nuxeo-drive-client/tests/test_local_creations.py
nuxeo-drive-client/tests/test_remote_document_client.py

Add simple tests to ensure we support folders with dots in their names.
Also:
* Bump version to 2.5.10
* NXDRIVE-1035: Update Nuxeo version to 9.10-SNAPSHOT for the tests

NXDRIVE-1034: Test folders containing dots

---

docs/changes.md
nuxeo-drive-client/tests/common.py
nuxeo-drive-client/tests/common_unit_test.py
nuxeo-drive-client/tests/test_bind_server.py
nuxeo-drive-client/tests/test_commandline.py
nuxeo-drive-client/tests/test_engine_dao.py
nuxeo-drive-client/tests/test_manager_dao.py
nuxeo-drive-client/tests/test_report.py

`addCleanup()` is a `unittest` method that will be called whatever the sate of the test to ensure a good clean-up.

NXDRIVE-317: Test tmp directories are not cleaned up after tear down

---

docs/changes.md
nuxeo-drive-client/nxdrive/client/remote_document_client.py
nuxeo-drive-client/nxdrive/engine/dao/sqlite.py
nuxeo-drive-client/tests/test_synchronization.py

NXDRIVE-1034: Cannot unsync an accentued root on Windows

---

docs/changes.md
tools/jenkins/packages.groovy
tools/jenkins/tests-8.10.groovy
tools/jenkins/tests.groovy

These parameters are not usable. If we want to reproduce a build, we just have to set the good branch name.

NXDRIVE-1042: Remove non-used jobs parameters

---

nuxeo-drive-client/nxdrive/engine/engine.py
nuxeo-drive-client/nxdrive/manager.py
nuxeo-drive-client/nxdrive/updater.py
nuxeo-drive-client/tests/common_unit_test.py
nuxeo-drive-client/tests/test_nxdrive_903.py

Also:
- Disable updater threads in test
- Bypass test_nxdrive_903 on macOS, temporary

NXDRIVE-1019: Adapt the server configuration URL

---

docs/changes.md
docs/technical_changes.md
nuxeo-drive-client/nxdrive/client/local_client.py
nuxeo-drive-client/nxdrive/direct_edit.py
nuxeo-drive-client/nxdrive/engine/dao/sqlite.py
nuxeo-drive-client/tests/test_readonly.py
tools/integration_tests_setup.py
tools/jenkins/tests-8.10.groovy
tools/jenkins/tests.groovy

Using `abspath()` only when needed sped up methods like `delete()`, `move()` or `rename()`. 
I also removed the setup stage from Jenkins Drive-test job, useless.

NXDRIVE-1046: Review the LocalClient class

---

docs/changes.md
nuxeo-drive-client/nxdrive/client/local_client.py
nuxeo-drive-client/nxdrive/engine/engine.py
nuxeo-drive-client/nxdrive/engine/processor.py
nuxeo-drive-client/tests/test_local_client.py

Also, cleaned-up a test from de-duplication condition.

NXDRIVE-1061: Remote rename of an accentued folder on Windows fails

---

docs/changes.md
docs/technical_changes.md
nuxeo-drive-client/nxdrive/direct_edit.py
nuxeo-drive-client/nxdrive/engine/processor.py
nuxeo-drive-client/nxdrive/engine/watcher/local_watcher.py
nuxeo-drive-client/nxdrive/engine/watcher/remote_watcher.py
nuxeo-drive-client/nxdrive/report.py
nuxeo-drive-client/nxdrive/utils.py
nuxeo-drive-client/tests/common.py
nuxeo-drive-client/tests/common_unit_test.py
nuxeo-drive-client/tests/test_bulk_remote_changes.py
nuxeo-drive-client/tests/test_local_client.py
nuxeo-drive-client/tests/test_local_move_and_rename.py
nuxeo-drive-client/tests/test_local_storage_issue.py
nuxeo-drive-client/tests/test_permission_hierarchy.py
nuxeo-drive-client/tests/test_readonly.py
nuxeo-drive-client/tests/test_synchronization.py
nuxeo-drive-client/tests/test_windows.py

Alos:
- Framework: Review LocalWatcher class, better use of lock
- Updater: Updated minimum server version from 5.6 to 7.10
- \[Windows\] Jenkins: Added `-direct` argument to the deploy script to prevent downloading any dependency

NXDRIVE-836: Bad behaviors with read-only documents

---

docs/changes.md
docs/deployment.md
docs/technical_changes.md
nuxeo-drive-client/nxdrive/engine/engine.py
nuxeo-drive-client/nxdrive/engine/next/engine_next.py
nuxeo-drive-client/nxdrive/engine/watcher/remote_watcher.py
nuxeo-drive-client/nxdrive/engine/workers.py
nuxeo-drive-client/nxdrive/notification.py
nuxeo-drive-client/nxdrive/osi/__init__.py
nuxeo-drive-client/tests/test_synchronization.py
nuxeo-drive-client/tests/test_utils.py

The systray icon will no longer being red when a HTTP error is not a real credentials one.

NXDRIVE-1104: Set invalid credentials on 401,403 errors only

---

tools/jenkins/tests-8.10.groovy

NXBT-1744 fix discardoldbuild jenkinsfile 
The changes made before have not been applied during the build. The Builddiscarder/logrotator classes have to be inline.

NXBT-1744 fix discardoldbuild jenkinsfile

---

docs/changes.md
nuxeo-drive-client/nxdrive/__init__.py
nuxeo-drive-client/nxdrive/client/local_client.py
nuxeo-drive-client/nxdrive/data/ui5/i18n.js
nuxeo-drive-client/nxdrive/engine/engine.py
nuxeo-drive-client/nxdrive/engine/processor.py
nuxeo-drive-client/nxdrive/manager.py
nuxeo-drive-client/nxdrive/notification.py
nuxeo-drive-client/tests/test_manager_dao.py
nuxeo-drive-client/tests/test_remote_move_and_rename.py
nuxeo-drive-client/tests/test_windows.py

So, when a folder/file is blocked because of another process using it, we delay the action for 60 secondes and notify the user. There will be no error and the action will be done when the user will close the software using that document or one of its children.
That commit may fix others issues from the epic https://jira.nuxeo.com/browse/NXDRIVE-1089, will check then.
Also:
- NXDRIVE-1009: Some folders not deleted on client when file is open
- Ease future transition to Qt 5 in `notifications.py`

NXDRIVE-1105: Avoid unwanted file deletions on Windows 7

---

docs/changes.md
nuxeo-drive-client/nxdrive/client/local_client.py
nuxeo-drive-client/nxdrive/data/ui5/i18n.js
nuxeo-drive-client/nxdrive/engine/engine.py
nuxeo-drive-client/nxdrive/engine/processor.py
nuxeo-drive-client/nxdrive/engine/watcher/local_watcher.py
nuxeo-drive-client/nxdrive/notification.py
nuxeo-drive-client/tests/test_local_client.py
nuxeo-drive-client/tests/test_synchronization.py
tools/jenkins/tests.groovy

An unexpected behavior with long paths is the inability to move to trash. Send2Trash uses an old API  that cannot deal with such files. So we are currently ignoring actions on them and NXDRIVE-1118 will try to fix it.

NXDRIVE-1008: Document deleted server side when unfiltering and opened elsewhere

---

nuxeo-drive-client/nxdrive/engine/processor.py
nuxeo-drive-client/tests/test_synchronization.py
tools/jenkins/tests.groovy

It happens when using the same local sync folder with an account, delete it and use another account.
Old files have to be removed locally without any error.

NXDRIVE-1118: Fix obsolete synced files deletion

---

docs/changes.md
docs/deployment.md

We can now build Drive on Windows 10.

NXDRIVE-1190: Remove Microsoft Visual C++ Compiler from requirements

---

docs/technical_changes.md
nxdrive/client/local_client.py
nxdrive/commandline.py
nxdrive/engine/dao/sqlite.py
nxdrive/engine/engine.py
nxdrive/engine/next/simple_watcher.py
nxdrive/engine/processor.py
nxdrive/engine/tracker.py
nxdrive/engine/watcher/local_watcher.py
nxdrive/engine/watcher/remote_watcher.py
nxdrive/wui/application.py
tests/common.py
tests/mac_local_client.py
tests/test_nxdrive_903.py
tests/win_local_client.py

* Fixed a subtle threading bug with `time.strptime()`
* Fixed a `RemoteFileInfo` instanciation bug into `RemoteWatcher._update_remote_states()`
* Added `Engine.__repr__()`
* Better `repr(FileInfo)`
* Remove unused `LocalClient.is_inside()`
* Vars clean-up in various `Processor` methods
* Vars clean-up in `RemoteWatcher._update_remote_states()`
* Refactor `Tracker` events sending
* Use `os.path.is*()` instead of general `os.path.exists()`
* Keep the testing database in `Engine.unbind()`
* Replace use of `dict.iteritems()` with `dict.items()` to ease future Python 3 transition
* Give time for test_nxdrive_903.py to perform renames

NXDRIVE-903: Clean-up

---

docs/changes.md
docs/technical_changes.md
nxdrive/engine/engine.py
nxdrive/manager.py

The badge lookup was done in the wrong engine. Fixed the comparison to ensure a correct lookup.

 NXDRIVE-1203: Files appears as "not synced" when restarting Nuxeo Drive

---

docs/changes.md
nxdrive/client/remote_client.py
nxdrive/engine/dao/sqlite.py
nxdrive/engine/engine.py
nxdrive/engine/watcher/remote_watcher.py
nxdrive/engine/workers.py
nxdrive/updater/base.py
nxdrive/utils.py
nxdrive/wui/application.py
nxdrive/wui/settings.py
requirements.txt
tests/__init__.py
tests/common.py
tests/conftest.py
tests/test_bind_server.py
tests/test_darwin.py
tests/test_direct_edit.py
tests/test_group_changes.py
tests/test_local_move_and_rename.py
tests/test_local_storage_issue.py
tests/test_long_path.py
tests/test_mac_local_client.py
tests/test_manager_dao.py
tests/test_options.py
tests/test_remote_move_and_rename.py
tests/test_synchronization.py

GNU/Linux: OK.
Windows: OK.
macOS: tests OK, but we still have the noisy `select: Invalid argument`. I will provide a second PR for that.
Why merging now? To let other work to be done based on fixes provided by this PR.
Also, I want to see how it works with other waiting PR to be merged + NXDRIVE-1212 where we will disable all server side converters. Currently, tests are taking too long on this OS with converters enabled.

NXDRIVE-1214: Fix lastest failures following the Python client integration

---

docs/changes.md
nxdrive/direct_edit.py
nxdrive/engine/blacklist_queue.py
tests/test_direct_edit.py

Actually there is no fix needed. The error is effective on Drive < 3.1 only.
So I added a test case and applied some changes to help triggering the manual error (+ debugging log)

NXDRIVE-1239: DirectEdit should work after network loss

---

docs/changes.md
requirements-tests.txt
requirements.txt

* Updated pytest from 3.6.4 to 3.7.0
* Updated xattr from 0.9.3 to 0.9.6
* The requirements file has been reformated automatically by `pre-commit`, it is fine like that too.

Upgrade pytest and xattr

---

nxdrive/data/qml/Systray.qml
nxdrive/gui/application.py

Also:
- Remove the loading of the custom Nuxeo font,
- Prevent an action with type == None from crashing the app.

NXDRIVE-1290: Systray error message is not loaded

---

docs/changes.md
nxdrive/engine/processor.py

We were missing a Windows specific error (code n° 3) when the system did not find a specified file.

NXDRIVE-1286: Ignore documents when the system cannot find the file

---

tools/osx/deploy_jenkins_slave.sh
tools/osx/fix_app_qt_folder_names_for_codesign.py
tools/posix/deploy_jenkins_slave.sh

Qt5 folder naming is blocking the codesigning because there are folders containing a dot in their name. And codesign sees them as code bundles and will reject them if they don't conform to the
expected code bundle layout.
The fix will move those folders from the MacOS directory to the Resources one, create a symlink into MacOS and finally update any impacted DLL to use appropriate `@load_path`.

NXDRIVE-1301: Fix .app tree to allow codesign on macOS

---

ndrive.spec
nxdrive/manager.py

They are shipped starting with Qt 5.11.

NXDRIVE-1319: Missing OpenGL DLLs after packaging on Windows

---

nxdrive/translator.py
tests/test_translator.py

Sequential calls to `Translate.get(...)` with the same `values` list would modify it each time.

NXDRIVE-1313: Translator._tokenize() mutates the values list

---

nxdrive/manager.py

`Manager.open_local_file()` would raise an `OSError` even if the browser is successfully opened. This happens when using Opera on Windows 7 for instance. So we just log the error and let Drive continue.

NXDRIVE-1171: Prevent Drive crash on URL open failure

---

nxdrive/engine/tracker.py
nxdrive/gui/application.py
nxdrive/gui/folders_dialog.py

Also, initialize `Tracker.app_name` variable earlier so it exists when accessing `Tracker.user_agent` afterwards.

NXDRIVE-1354: Bring Settings window to the top after login in the browser

---

docs/technical_changes.md
nxdrive/client/remote_client.py
nxdrive/engine/engine.py
nxdrive/gui/folders_treeview.py

Having a different class and two remote client instances just for a filter seemed excessive. Now the `Remote` client filters by default, but when populating the filters window, passes an argument to deactivate the filtering.

NXDRIVE-1356: Fix removed filters not appearing back when unchecked

---

nxdrive/utils.py
tests/test_utils.py

The RegExp was replacing elements by groups, selecting consecutives characters by only one dash.
Added regression tests and fixed the pattern.
Another patch will be needed but done only for the next version. This is a regression bugfix.

NXDRIVE-1259: Fix a bug in utils.safe_filename()

---

docs/changes/4.0.1.md
docs/deployment.md
nxdrive/client/local_client.py
nxdrive/objects.py
tests/test_commandline.py
tools/posix/deploy_jenkins_slave.sh
tools/windows/deploy_jenkins_slave.ps1

NXDRIVE-1389: Upgrade Python from 3.6.6 to 3.6.7

NXDRIVE-1236: Fix datetime.fromtimestamp() erronously throws an OSError on Windows

---

docs/changes/4.0.1.md
nxdrive/commandline.py
nxdrive/options.py
tests/test_commandline.py
tests/test_options.py

- Enhance `MetaOptions` to display the faultive file and section.
- Pre-configure the logging to catch early configuration errors.
- Unskip `test_site_update_url()` from `test_options.py`.
- Code clean-up in `test_commandline.py` and `test_options.py`.

NXDRIVE-1405: Handle local INI system-wide configuration

---

docs/changes/4.0.1.md
nxdrive/data/i18n/i18n.json
nxdrive/data/qml/NuxeoInput.qml
nxdrive/data/qml/Systray.qml
nxdrive/data/qml/SystrayFile.qml
tests/resources/i18n/i18n.json

NXDRIVE-1412: Replace 'Synchronization completed' label by 'Synchronization complete'
NXDRIVE-1413: Prevent long server URL from moving folder and settings icons to the right
NXDRIVE-1421: Enable text selection on server URL and destination folder
NXDRIVE-1410: Add a frame to systray layer

NXDRIVE-1411: Use consistent icons to edit document / open local folder

---

docs/changes/4.0.1.md
nxdrive/client/proxy.py
nxdrive/client/remote_client.py
nxdrive/commandline.py
nxdrive/gui/api.py
nxdrive/gui/application.py
nxdrive/manager.py
nxdrive/updater/base.py
nxdrive/utils.py

Requests made from the auto-updater are kept secure.

NXDRIVE-1434: Fix the "consider-ssl-errors" option implementation

---

docs/changes/4.0.1.md
docs/changes/4.0.2.md
docs/configuration.md
nxdrive/client/proxy.py
nxdrive/client/remote_client.py
nxdrive/commandline.py
nxdrive/gui/api.py
nxdrive/gui/application.py
nxdrive/options.py
nxdrive/updater/base.py
nxdrive/utils.py

Introduce the `ca-bundle` option that must point to a file or directory with certificates of trusted CAs.
If set, the `ssl-no-verify` option has no effect.

NXDRIVE-1433: Handle custom SSL certificates

---

tests/test_long_path.py

Just restricting a test, this bug has been fixed by the use of pathlib with NXDRIVE-1109.

NXDRIVE-1090: Long path names generates duplicata on folder creation

---

docs/changes/4.1.0.md
nxdrive/client/local_client.py
nxdrive/data/i18n/i18n.json
nxdrive/engine/engine.py
nxdrive/engine/processor.py
nxdrive/notification.py
tests/test_long_path.py

On most GNU/Linux FS, the maximum filename size is 255.
It is worst when using encryptFS which sets the limit to 143.
The patch makes `Processor()` to handle this case (`OSError` 36) and adapt `LocalClient.exists()` to return `False` when encountering that error.

NXDRIVE-1523: Handle paths with more than 143 chars on encrypted FS

---

nxdrive/gui/application.py

Introduced in 57ad7c6, I thought it would help. But accordingly to
http://python.6.x6.nabble.com/how-to-implement-QApplication-notify-td1920004.html#a1920005
this is only for C++ code. Also, it was making Drive to crash on macOS and Windows.
No clue why it was not doing the same on GNU/Linux ...

NXDRIVE-1531: Do not declare QApplication.notify()

---

docs/README.md
docs/behaviors/Adobe Creative Suite.md
docs/behaviors/README.md
docs/changes/4.1.0.md
nxdrive/autolocker.py
nxdrive/direct_edit.py
nxdrive/manager.py
nxdrive/objects.py
nxdrive/osi/__init__.py
nxdrive/osi/darwin/darwin.py
nxdrive/osi/darwin/files.py
nxdrive/osi/linux/files.py
nxdrive/osi/linux/linux.py
nxdrive/osi/windows/files.py
nxdrive/osi/windows/windows.py
nxdrive/utils.py
requirements.txt
tests/test_utils.py

I splitted changes in several commits. Will do a single commit when merging.
For now, only support for Photoshop and Illustrator as other apps do not expose any API (via COM or AppleScript). And it works pretty well :muscle:
On Windows, we are using COM objects to communicate with an eventual running instance of Photoshop.
And on macOS, we are doing the same but with AppleScript.

NXDRIVE-1493: Add DirectEdit support for the Adobe Creative Suite

---

docs/changes/4.1.0.md
docs/configuration.md
nxdrive/__main__.py
nxdrive/constants.py
nxdrive/data/i18n/i18n.json
nxdrive/data/qml/GeneralTab.qml
nxdrive/gui/api.py
nxdrive/manager.py
nxdrive/options.py

* NXDRIVE-1537: Prompt the user for metrics sharing settings
Added `Options.use_analytics` and `Options.use_sentry` to control what data we will be able to collect.
The message box will be displayed one time, then preferences will be saved in a ".metrics.state" file next to the executable.
Also introduced a new constant, `COMPANY`, and removed all text mentioning "Nuxeo" or "Drive" in `__main__.py` to ease branding.
* NXDRIVE-1537: Removed the GUI option to control analytics
It is now useless as it is prompted the user to allow/disallow to send analytics at startup, then the preference is saved. The option can still be controlled by the `use-analytics` parameter.
Also added "sentry" to `Manager` metrics.

NXDRIVE-1537: Prompt the user for metrics sharing settings

---

docs/changes/4.1.0.md
requirements.txt

This reverts commit f379aed8373eed4654f6186e04dd7b3a7708d6b9.
It causes a fatal error on macOS:
ModuleNotFoundError: No module named 'sentry_sdk.integrations.logging'
Will take time later to investigate, but this is not a priority.

Revert "Update sentry-sdk from 0.7.3 to 0.7.4"

---

docs/changes/4.1.0.md
docs/support.md
tools/scripts/check_update_process.py
tools/versions.py

This reverts commit 28928d39dc5d8b2e4bc4f2dd0b9e5abf58f1c400.
It has been decided to not drop the 7.10 support until we use a missing feature from 7.10 that would effectively break its support.

Revert "NXDRIVE-1564: Drop support for Nuxeo Platform 7.10"

---

tests/old_functional/common.py
tests/unit/test_options.py

* Do not trigger a Sentry event in `test_options.py`::`test_error`.
* Ensure the tested method is sent to Sentry to ease debugging.

NXDRIVE-1542: Little improvements

---

nxdrive/commandline.py
nxdrive/manager.py
nxdrive/options.py
tests/unit/test_options.py
tools/posix/deploy_jenkins_slave.sh
tools/scripts/check_update_process.py

* NXDRIVE-1596: Set the `channel` option to release by default. Also fix the `channel` option persistence in the database.
* NXDRIVE-1597: Update options of type sequence instead of overwriting them.
* NXDRIVE-1552: Fix deploy script on macOS.
* NXDRIVE-1552: Fix the `check_update_process.py` script.

NXDRIVE-1552: Pre-release 4.1.0 fixes

---

docs/changes/4.1.0.md
nxdrive/commandline.py
nxdrive/gui/application.py
nxdrive/osi/extension.py

There is a case where `QLocalSocket.disconnectFromHost()` will disconnect immediately.
So the next call to `QLocalSocket.waitForDisconnected()` will print out a warning:
```
QLocalSocket::waitForDisconnected() is not allowed in UnconnectedState
```

NXDRIVE-1598: Ensure the QLocalSocket is connected before disconnection

---

nxdrive/data/qml/DeletionPopup.qml

To fix such warning when Drive is packaged:
```
GeneralTab.qml:149:5: QML NuxeoPopup: Binding loop detected for property "contentHeight"
```

NXDRIVE-1501: Fix contentHeight of the popup

---

docs/changes/4.1.1.md
nxdrive/utils.py
tests/unit/test_utils.py

Move URLs computation to its own function compute_urls().
It will remove trailing slashes and doubles slashes from URL paths.

NXDRIVE-1607: Improve URLS computation

---

docs/changes/4.1.1.md
nxdrive/osi/darwin/files.py

* Add checks for `NSWorkspace` and running applications.
* Replace use of deprecated [launchedApplications()](https://developer.apple.com/documentation/appkit/nsworkspace/1579272-launchedapplications) with [runningApplications()](https://developer.apple.com/documentation/appkit/nsworkspace/1534059-runningapplications?language=objc).

NXDRIVE-1612: [macOS] Improve running applications detection

---

docs/changes/4.1.1.md
nxdrive/client/local_client.py
nxdrive/client/remote_client.py
nxdrive/engine/dao/sqlite.py
nxdrive/engine/processor.py
tests/old_functional/__init__.py
tests/old_functional/test_local_changes_when_offline.py
tests/old_functional/test_local_deletion.py
tests/old_functional/test_local_move_and_rename.py
tests/old_functional/test_local_move_folders.py
tests/old_functional/test_nxdrive_903.py
tests/old_functional/test_remote_deletion.py
tests/old_functional/test_special_characters.py
tests/old_functional/test_versioning.py
tests/old_functional/test_watchers.py

* Introduced `Remove.move2()` to call `Document.Move`. (name not very original, but I did as it is done with `shutil`: `shutil.copy()` and `shutil.copy2()`)
The trick here is to call `move2()` inside the same parent but with a new name. It will update the name and so the URL.
**WARNING**: this is a big change as it will invalidate any shared URL containing the document's name. In other words, if one shared a simple URL, and if the document is renamed by anyone, the URL will end on a 404 error (not found). This is not the case if one used the official mecanism and shared the document using the "Share link" that is using the document's UID.
---
And some bugfixes/improvements:
* Fix several escaping errors in SQL and NXQL queries.
* Improve `Remote.get_info()`: by removing a HTTP call to the …

NXDRIVE-986: Creating a new folder then renaming generates meaningless URLs

---

docs/changes/4.1.3.md
nxdrive/gui/application.py
nxdrive/manager.py
tests/functional/test_behavior.py

* Make database backups when adding and removing an account.
* Display the file URL in `Application.event()`.

NXDRIVE-1618: Remove inexistant engines from the Manager engines list

---

docs/changes/4.1.3.md
nxdrive/data/qml/AccountsTab.qml
nxdrive/engine/engine.py
nxdrive/gui/application.py
nxdrive/manager.py
nxdrive/objects.py
nxdrive/options.py
nxdrive/utils.py

This needed several fixes (each one appearing after a fix was done).
* Rework `Manager.bind_engine()` to path releated handle error  and start watching the folder only if the Engine has started.
* Fix `Engine.bind()` to use a Remote client only if we can   login to the server.
* Fix a `TypeError` in `DocPair.__getattr__()` when the `local_path` or `local_parent_path` is not defined or set to `None`.
* Handle bad token value in `Application._web_auth_not_frozen()`.
* Fix `Application.init_checks()` not show the Accounts window if any Engine has invalid credentials. This will show the 1st Engine in the list, not the faultive one.
* Display a link to re-authenticate in the Account tab.

NXDRIVE-1641: Fix bind-server CLI without the --password argument

---

docs/changes/4.1.3.md
nxdrive/client/local_client.py
nxdrive/engine/engine.py
nxdrive/engine/watcher/local_watcher.py
nxdrive/gui/application.py
nxdrive/options.py
tests/functional/test_behavior.py
tests/old_functional/test_local_move_folders.py
tests/unit/test_action.py
tests/unit/test_options.py
tests/unit/test_pid_lock_file.py
tools/posix/deploy_jenkins_slave.sh
tools/windows/deploy_jenkins_slave.ps1

* Improved `LocalClient.get_path()`
But also:
* Fixed `test_actions.py::test_file_action_with_values()`
* Fixed `test_options.py::test_str_utf8()`
* Fixed `test_pid_lock_file.py::test_already_locked()`
* Skip `test_behavior.py::test_mananger_engine_removal()` on Windows
* Review how tests are launched to let time for the server to breath.

NXDRIVE-1644: Fix LocalWatcher.rootMoved() signal emitter

---

docs/changes/4.1.3.md
nxdrive/constants.py
nxdrive/engine/dao/sqlite.py
nxdrive/engine/processor.py
nxdrive/gui/application.py
nxdrive/manager.py
nxdrive/osi/windows/windows.py
nxdrive/updater/base.py
tests/old_functional/test_local_storage_issue.py

Introduced `NO_SPACE_ERRORS` to handle different kind of disk space related errors.
Different scenarii:
* On database backup: log a warning
* On database restore: raise a fatal error
* On upgrade: alert the user
* On local file opening: raise a fatal error
* Anytime while syncing: alert the user and pause the sync

NXDRIVE-1148: Better handle no space left on the device

---

docs/changes/4.1.3.md
nxdrive/autolocker.py
nxdrive/client/local_client.py
nxdrive/client/remote_client.py
nxdrive/engine/watcher/remote_watcher.py
nxdrive/exceptions.py
tests/old_functional/test_remote_client.py

Also:
* remove usage of lambdas for `operator.attrgetter()`
* use `time.monotonic()` instead of `datetime.datetime.now()`

NXDRIVE-1665: Ensure coherent response of ScrollDescendants

---

nxdrive/engine/processor.py
tests/old_functional/test_local_storage_issue.py

Also pushing the doc_pair in the errors queue to prevent infinite sync.

NXDRIVE-1148: Fix test_synchronize_no_space_left_on_device()

---

docs/changes/4.1.3.md
nxdrive/updater/base.py
nxdrive/updater/utils.py
tests/integration/windows/utils.py
tests/unit/test_updater.py

Also fix `pytest --last-failed` trying to import Windows module on non Windows OS.

NXDRIVE-1682: Make the updater more robust against inappropriate server response

---

nxdrive/engine/blacklist_queue.py
nxdrive/engine/dao/sqlite.py
nxdrive/engine/engine.py
nxdrive/engine/watcher/local_watcher.py
nxdrive/engine/watcher/remote_watcher.py
tests/old_functional/test_synchronization_suspend.py
tests/unit/test_blacklist_queue.py

This fixes the issue on macOS and Windows.
On GNU/Linux, the deleted event is against the old `/folder/subfolder/file.txt` instead of `/folder-renamed/subfolder-renamed/file.txt`.
This is a corner case and I have no idea how to fix it. So the fix is postponed on GNU/Linux. To follow with [NXDRIVE-1690](https://jira.nuxeo.com/browse/NXDRIVE-1690).

NXDRIVE-695: File is not deleted on the server when the parent folder is renamed, while offline

---

docs/changes/4.1.4.md
nxdrive/data/qml/SystrayFile.qml
nxdrive/gui/view.py
nxdrive/objects.py
nxdrive/utils.py
tests/unit/test_utils.py

Introduced `sizeof_fmt()` to pretty display the file size.

NXDRIVE-1684: Display the file size in the systray

---

docs/changes/4.1.4.md
nxdrive/constants.py
nxdrive/direct_edit.py
nxdrive/utils.py
tests/functional/test_direct_edit.py
tests/old_functional/test_direct_edit.py
tests/unit/test_utils.py

Alos moved tests from "old_functional" to "functional" and some clean-up.

NXDRIVE-1671: Only cleanup well-formed folders in DirectEdit directory

---

docs/changes/4.1.4.md
docs/deployment.md
tools/posix/deploy_jenkins_slave.sh
tools/windows/deploy_jenkins_slave.ps1

* `SKIP=flake8` to skip code style
* `SKIP=mypy` to skip type annotations
* `SKIP=rerun` to not rerun failed test(s)
* `SKIP=integration` to not run integration tests on Windows
* `SKIP=all` to skip all (equivalent to `flake8,mypy,rerun,integration`)

NXDRIVE-1694: Add the SKIP envar to bypass specific actions

---

docs/changes/4.1.4.md
nxdrive/direct_edit.py
tests/old_functional/common.py
tests/old_functional/test_remote_deletion.py
tests/old_functional/test_remote_move_and_rename.py
tests/unit/test_action.py
tools/jenkins/tests.groovy
tools/jenkins/tests_os.groovy
tools/windows/deploy_jenkins_slave.ps1

* `test_action.py`
* `test_remote_deletion.py`
* `test_remote_move_and_rename.py`
Also fixed an old copy/paster error in `wait_sync()`.
---
And others interesting things:
* NXDRIVE-1702: Enable concurrent pipeline builds
* NXDRIVE-1694: Fix DirectEdit checksum verification with downloaded tmp files

NXDRIVE-1697: Fix tests

---

docs/deployment.md
tools/posix/deploy_jenkins_slave.sh
tools/windows/deploy_jenkins_slave.ps1

Now, if you want to only check code quality, you can use `SKIP=tests`. It will run flake8, then mypy and quit.

NXDRIVE-1694: Add SKIP=tests to run only code quality checks

---

docs/changes/4.1.4.md
nxdrive/client/remote_client.py
nxdrive/engine/dao/sqlite.py
nxdrive/engine/processor.py
nxdrive/engine/watcher/remote_watcher.py
nxdrive/engine/workers.py
nxdrive/utils.py
tests/old_functional/test_transfer.py

Also:
* Remove obsolete downloads on remote changes;
* Minor code clean-up;
* Introduce `Remote.upload_callback()`.

NXDRIVE-1697: Add tests for the transfers pause/resume feature

---

docs/changes/4.1.4.md
docs/support.md
nxdrive/__main__.py
requirements-dev.txt
requirements.txt
tests/__init__.py
tests/functional/conftest.py
tests/functional/test_direct_edit.py
tests/old_functional/test_direct_edit.py
tools/osx/fix_app_qt_folder_names_for_codesign.py
tools/posix/deploy_jenkins_slave.sh
tools/windows/deploy_jenkins_slave.ps1

* Add `requests` requirement to bypass a bug with old version and `urllib3` >= 1.25;
(see https://github.com/kennethreitz/requests/issues/5067)
* Use a development branch of PyInstaller to bypass a venv bug;
(see https://github.com/pyinstaller/pyinstaller/issues/3942)
* Remove `setuptools` and `pip` 18 requirement, there is no more issue here;
* Fixed `fix_app_qt_folder_names_for_codesign.py` as it was yielding
files and folders in a random manner and was trying to fix non-DLL files.

NXDRIVE-1224: Upgrade Python from 3.6.8 to 3.7.3

---

docs/changes/4.1.4.md
nxdrive/data/qml/Systray.qml
nxdrive/engine/activity.py
nxdrive/engine/dao/sqlite.py
nxdrive/engine/engine.py
nxdrive/gui/api.py
nxdrive/gui/application.py
nxdrive/objects.py
tests/unit/test_engine_dao.py

It seems we cannot use `Action` as a PyQt slot type. Using `object` fixes the issue.
Also:
* Fix `Engine.refresh_files()` QtSlot: it was missing an argment
* Removed `Engine.transferUpdated`;
* Removed `Engine.get_last_files()` and `.get_last_files_count()`;
* Remove unsued `state_factory` arg from `EngineDAO.__init__()`;
* Do not alter `EngineDAO.row_factory` in `get_transfers()`;
* Remove non-signal class attributes in `activity.py`;
* NXDRIVE-1604: Set keyword only `get_last_file()` methods. Same for `get_last_files_count()`;
* Set up a timer to kick off the event loop every 100 ms.

NXDRIVE-1720: Fix a crash when selecting a root to sync

---

docs/changes/4.1.4.md
nxdrive/data/i18n/i18n.json
nxdrive/engine/engine.py
nxdrive/gui/api.py
nxdrive/utils.py
tests/unit/test_utils.py

* Also improved Engine.unbind() when the database file is already deleted;
* NXDRIVE-1723: When selecting a local folder on auth, another folder is selected.

NXDRIVE-1727: Check for local folder rights and fail gracefully on permission error

---

docs/changes/4.1.4.md
nxdrive/client/remote_client.py
nxdrive/direct_edit.py
nxdrive/engine/processor.py
nxdrive/engine/watcher/remote_watcher.py
nxdrive/exceptions.py
nxdrive/utils.py
requirements.txt
tests/old_functional/test_direct_edit.py
tests/old_functional/test_permission_hierarchy.py
tests/old_functional/test_readonly.py
tests/old_functional/test_synchronization.py

* Packaging: Updated nuxeo from 2.1.1 to 2.2.1;
* NXDRIVE-1731: Fix `UnboundLocalError`: local variable 'handler_name' referenced before assignment in `Processor`.

NXDRIVE-1722: Correctly handle Unauthorized and Forbidden statuses

---

docs/changes/4.1.4.md
nxdrive/constants.py
nxdrive/engine/processor.py
nxdrive/manager.py
tests/old_functional/common.py
tests/old_functional/test_multiple_files.py

* NXDRIVE-1736: Filter out the `WinError 123` (about long file names too long);
* Remove the `QTimer` to kill a test. It is no more useful since 7b317b4.

NXDRIVE-1733: Fix missing "select" argument in open_local_file()

---

docs/changes/4.1.4.md
nxdrive/client/local_client.py
nxdrive/engine/watcher/remote_watcher.py
nxdrive/osi/darwin/darwin.py
tests/functional/test_local_client.py

Introduced the `LocalClient.set_path_remote_id()` static method to be able to test the feature without needing an account.
While testing, I saw that on Windows, when a file is not found and we want to set the remote ID, an exception would be rasied. But not on other OSes. So I aligned the behavior.
* NXDRIVE-1729: [macOS] Use EAFP to catch `FileNotFoundError` in `send_content_sync_status()`
* NXDRIVE-1728: Lower logging level of "Cannot find parent pair of post…poned remote descendant, ..."

NXDRIVE-1734: Ignore decoding issues when retrieving the path stored in xattrs

---

docs/changes/4.1.4.md
nxdrive/client/remote_client.py
nxdrive/engine/dao/sqlite.py
nxdrive/engine/processor.py
nxdrive/engine/watcher/remote_watcher.py
requirements.txt
tests/__init__.py
tests/old_functional/common.py
tests/old_functional/test_direct_edit.py
tests/old_functional/test_local_creations.py
tests/old_functional/test_multiple_files.py
tests/old_functional/test_reinit_database.py
tests/old_functional/test_synchronization.py
tests/old_functional/test_transfer.py

The commit splits out `Remote.upload()` in 2 parts:
- `Remote.upload_chunks()` to effectively upload a given blob (either in chunk or normal mode).
- `Remote.link_blob_to_doc()` that calls the `NuxeoDrive.CreateDocument` operation.
I reworked the code to be more robust against temporary failures while uploading chunks and after, at the operation call. This should help with big file uploads.
Also:
* This reverts commit 853cb52 as it seems we still need the timer to prevent infinite tests.
* NXDRIVE-1705: Fix tests requiring local data to be present after unbinding.

NXDRIVE-1753: Improve uploads robustness

---

docs/changes/4.1.4.md
nxdrive/client/local_client.py
nxdrive/client/remote_client.py
nxdrive/direct_edit.py
nxdrive/engine/activity.py
nxdrive/engine/processor.py
nxdrive/utils.py
tests/functional/test_local_client.py
tests/unit/test_action.py

Also a couple of other fixes to reduce Sentry events:
* NXDRIVE-1777: Force re-download if a local file does not exist anymore but it is still referenced in the database
* NXDRIVE-1776: Handle incorrect chunked encoding in Direct Edit's upload queue
* NXDRIVE-1734: [Windows] Ignore decoding issues when retrieving the path stored in xattrs
And fixes related to uploads:
* NXDRIVE-1753: Handle correctly empty file uploads
* NXDRIVE-1753: [Windows] Fix path separator when calling `Remote.fetch()`

NXDRIVE-1775: Bypass PermissionError raised from Path.resolve()

---

README.md
docs/changes/4.1.4.md
nxdrive/engine/engine.py
nxdrive/engine/processor.py
nxdrive/fatal_error.py
nxdrive/gui/application.py
nxdrive/manager.py
nxdrive/osi/__init__.py
nxdrive/osi/darwin/darwin.py
nxdrive/osi/linux/linux.py
nxdrive/osi/windows/windows.py
nxdrive/utils.py
tests/functional/conftest.py
tests/integration/windows/utils.py
tests/old_functional/test_context_menu.py

I needed to change how we deal with the clipboard.
It now uses OS tools:
- `pbcopy`/`pbpaste` on macOS
- `xclip` on GNU/Linux (manual installation needed)
The `QApplication.clipboard()` is broken and not really safe to use (segfault on Unix, no clipboard available for some reason, ... ).
Also remove void transfers on document not found.

NXDRIVE-1780: Fix "Access online" context menu not opening the browser

---

nxdrive/client/remote_client.py
nxdrive/constants.py
nxdrive/engine/watcher/local_watcher.py

As chunked uploads are based on the file size, and to have proper uploads with large files, we need to wait for the file to be fully copied on the hard drive before starting to upload it.
Also set the Nuxeo timeout to 6 hours. This is huge but only to handle big files. Testing are ongoing to knwo what value to set exactly.

NXDRIVE-1714: Start the upload only when the file is fully copied

---

docs/changes/4.1.4.md
nxdrive/data/i18n/i18n.json
nxdrive/engine/processor.py
nxdrive/engine/tracker.py
nxdrive/gui/application.py
nxdrive/gui/view.py
nxdrive/utils.py
tests/unit/test_utils.py

The suffix is translated only in the systray menu. In the logs, as sentences are in english, no need
to do the translation.

NXDRIVE-1751: Localize the "B" abbreviation for "byte" in sizeof_fmt()

---

docs/changes/4.1.4.md
docs/configuration.md
nxdrive/client/local_client.py
nxdrive/engine/dao/sqlite.py
nxdrive/engine/engine.py
nxdrive/engine/processor.py
nxdrive/engine/watcher/local_watcher.py
nxdrive/options.py
tests/old_functional/test_local_client.py
tests/old_functional/test_local_move_and_rename.py
tests/old_functional/test_nxdrive_903.py

Introduced `Options.big_file` to be able to set a custom value for the file size limit (300 MiB by
default). This is a tradoff to handle large files as best effort.
* Stop the checksum computation on pause or exit.
* Repush the acquired doc pair only on Windows
As this portion of code is only needed on Windows whhen creating a file inside a read-only folder,
we can skip it on Unix.

NXDRIVE-1714: Skip digest computation for big files

---

nxdrive/client/remote_client.py
nxdrive/engine/activity.py
tests/old_functional/test_transfer.py

The issue is only reproductible when there is a GUI.
The UploadAction, when displayed in the systray menu, was somehow blocking the file access that was being uploaded, thus making socket timeouts and the upload was never really started.

NXDRIVE-1801: Chunk upload is broken on macOS

---

docs/changes/4.1.4.md
nxdrive/osi/extension.py
tests/unit/test_extension_listener.py

The issue came from `QHostAdress()` that does no DNS lookup and so returning an empty string.
Qt used then the default `0.0.0.0` IP.

NXDRIVE-1766: Fix extensions local server to listen on localhost

---

docs/changes/4.1.4.md
nxdrive/direct_edit.py
nxdrive/utils.py
tests/functional/test_direct_edit.py
tests/unit/test_utils.py

The regexp to parse the DirectEdit URL is now stricter: the download URL must be part of it. It is a requirement since a while, but the regexp was not updated.
Also, the same regexp has been improved to skip an anonymous group around the document's UID.
Tests have been added for `parse_protocol_url()`.

NXDRIVE-1732: Better handling of the Direct Edit protocol

---

nxdrive/engine/activity.py
nxdrive/utils.py

NXDRIVE-1706: Improve `encrypt()`/`decrypt()` when lazy is set to `True`.

NXDRIVE-1706: Fix repr(FileAction)

---

docs/changes.md
docs/changes/4.2.0.md
nxdrive/__init__.py

The major version update is because we will implement this new feature: NXDRIVE-1803 (Add a new update option: Centralized).

NXDRIVE-1699: Bump version to 4.2.0

---

docs/changes/4.2.0.md
nxdrive/gui/application.py
nxdrive/utils.py

Fallback on the cusor position to display the Systray menu when the notification tray is not reliable. This is true for some GNU/Linux flavors but the code will work for all OSes.

NXDRIVE-1749: [GNU/Linux] Systray menu is not at the good location

---

docs/changes/4.2.0.md
nxdrive/manager.py
tests/functional/test_behavior.py

This happens in that scenario:
- Add a new account using the local folder `/home/USER/drive`.
- Delete the Engine database.
- Add a new account using the local folder `/home/USER/drive`.
`FolderAlreadyUsed` is raised instead of deleting the old database entry because it is convenient to be able to restore the DB file later for whatever reason.
And there is no popup to ask the user for its deletion for the same purpose.
Note that the use case is rare enough to be handled that way. In fact, in years, that happened only while testing the application a lot.

NXDRIVE-1783: Handle account addition with already used local folder

---

docs/changes/4.2.0.md
nxdrive/client/remote_client.py
nxdrive/engine/activity.py
nxdrive/engine/engine.py
nxdrive/engine/processor.py
nxdrive/engine/tracker.py
nxdrive/gui/api.py
nxdrive/gui/view.py
requirements.txt
tests/functional/test_tracker.py
tests/old_functional/test_transfer.py
tests/unit/test_action.py

Reworked `Engine.suspend_client()` and little refactoring to use 3 transfer callbacks instead of a big method.
Timers are using nanoseconds to have the most accurate metrics possible, and so the variation
between 2 chunk metrics can be high depending on the server time to respond and the network
bandwith.
I also removed the useless and inaccurate `Processor` speed metric, completely.
Also:
- NXDRIVE-1784: Remove unused `QMLDriveApi.get_actions()`.

NXDRIVE-1782: Provide information on transfer speed

---

docs/changes/4.2.0.md
requirements-tests.txt
tests/integration/windows/test_cli_sub_command.py
tests/integration/windows/utils.py

`access-online` and `edit-metadata` are not well tested because we need to have control over the browser to guess the current opened URL.
So there is only a check that Drive works as expected, and the browser check should be done later in a specific ticket.

NXDRIVE-1815: [Windows] Add CLI sub-commands tests: context menu entries

---

docs/changes/4.2.0.md
nxdrive/__main__.py
nxdrive/client/remote_client.py
nxdrive/constants.py
nxdrive/data/qml/GeneralTab.qml
nxdrive/direct_edit.py
nxdrive/engine/dao/sqlite.py
nxdrive/engine/engine.py
nxdrive/engine/processor.py
nxdrive/engine/watcher/remote_watcher.py
nxdrive/gui/api.py
nxdrive/gui/application.py
nxdrive/logging_config.py
nxdrive/manager.py
nxdrive/options.py
nxdrive/osi/__init__.py
nxdrive/osi/darwin/darwin.py
nxdrive/osi/darwin/pyNotificationCenter.py
nxdrive/osi/extension.py
nxdrive/osi/windows/windows.py
nxdrive/report.py
nxdrive/translator.py
nxdrive/updater/base.py
nxdrive/updater/darwin.py
nxdrive/utils.py
tests/old_functional/__init__.py
tests/old_functional/test_concurrent_synchronization.py
tests/old_functional/test_direct_edit.py
tests/unit/test_translator.py

A lot of changes, remaining issues will be tackled with NXPY-128 and NXDRIVE-1095.
```shell
$ python -m pylint --disable=all --enable=protected-access nxdrive          
************* Module nxdrive.engine.watcher.local_watcher
nxdrive/engine/watcher/local_watcher.py:841: [W0212(protected-access), LocalWatcher._handle_watchdog_event_on_known_pair] Access to a protected member _queue_pair_state of a client class
************* Module nxdrive.client.remote_client
nxdrive/client/remote_client.py:449: [W0212(protected-access), Remote.upload_chunks] Access to a protected member _upload_idx of a client class
nxdrive/client/remote_client.py:479: [W0212(protected-access), Remote.upload_chunks] Access to a protected member _upload_idx of a client class
```

NXDRIVE-1816: Remove access to private methods

---

docs/changes/4.2.0.md
nxdrive/constants.py
nxdrive/osi/darwin/darwin.py
nxdrive/osi/linux/linux.py
nxdrive/updater/README.md
nxdrive/updater/linux.py
tools/linux/deploy_jenkins_slave.sh

Also a small improvement regarding the previous commit (GNU/Linux support for the auto-updater):
-  NXDRIVE-1743: Move the new file next to the running AppImage instead of the `$HOME` folder

NXDRIVE-445: [GNU/Linux] Add support for the custom URL protocol

---

docs/changes/4.2.0.md
nxdrive/gui/application.py
requirements.txt
tools/scripts/check_update_process.py
tools/windows/deploy_jenkins_slave.ps1

Upgrading to PyQt 5.13 fixes the issue.
That upgrade is effective on GNU/Linux and Windows only as there are blocker issues on macOS (they will be tackled in specific tickets).
A small fix is needed on Windows until PyInstaller 3.6 comes out.

NXDRIVE-1747: Fix the SSL support on GNU/Linux

---

docs/changes/4.2.0.md
nxdrive/engine/engine.py
nxdrive/gui/view.py

And:
- NXDRIVE-1819: Use arrows to indicate transfer type in speed metrics

NXDRIVE-1823: Update the sync count after resuming transfers at startup

---

docs/changes/4.2.0.md
nxdrive/client/remote_client.py
nxdrive/constants.py
nxdrive/engine/activity.py
nxdrive/options.py
nxdrive/osi/linux/linux.py

Also:
- Do not log `repr(Options)` but `str(Options)` when an option is modified. It will output less data.
- NXDRIVE-1824: Resuming a download fails if the temporary file was deleted.
- NXDRIVE-1825: Display the transfer speed at 1s interval (or more)
The speed was displayed at each transferred chunk. But if the connection is fast, the speed is not
readable and so useless. Instead, it is printed/refreshed when the transfer duration is more than 1 second.

NXDRIVE-445: [GNU/Linux] Better desktop integration

---

docs/changes/4.2.0.md
docs/dep/2019-01 Generate a unique test environment during the setup.md
docs/dep/2019-09 New update channel - Centralized.md
nxdrive/commandline.py
nxdrive/constants.py
nxdrive/data/qml/ChannelPopup.qml
nxdrive/manager.py
nxdrive/options.py
nxdrive/updater/base.py
nxdrive/updater/utils.py
tests/unit/test_updater.py

Step 1: DEP review.
You can see the DEP at this [link](https://github.com/nuxeo/nuxeo-drive/blob/wip-NXDRIVE-1803-new-centralized-auto-update-option/docs/dep/2019-09%20New%20update%20channel%20-%20Centralized.md).

NXDRIVE-1803: Add a new update channel: Centralized

---

docs/changes/4.2.0.md
nxdrive/constants.py
nxdrive/engine/watcher/remote_watcher.py

(introduced in 4.1.3 with NXDRIVE-1636)
Also several improvement:
- Higher value for remote scrolling descendant batch size: 100 -> 500.
- Removed useless timings from `RemoteWatcher._scan_remote_scroll()`.
- Better sorting of remote descendants.
(see commit contents for details)

NXDRIVE-1832: Fix a regression that prevents deep structure sync

---

docs/changes/4.2.0.md
docs/gnu_linux.md
docs/gnu_linux_qa.md
docs/support.md
nxdrive/gui/application.py
nxdrive/updater/base.py
nxdrive/utils.py
tests/functional/test_behavior.py
tests/unit/test_utils.py
tools/linux/deploy_jenkins_slave.sh

After testing from several people, we can assure this compatibilty table:
| Nuxeo Drive | Debian | Ubuntu | Fedora | Manjaro
|---|---|---|---|---
| 4.2.0+ | 10 | 16.04 | 29 | 18.1.0
And I did several fixes at the same time as they were spotted while testing:
-  NXDRIVE-1842: Skip update when no file is provided for a given version on a given OS
-  NXDRIVE-1844: Use light icons on Manjaro Linux
-  NXDRIVE-1845: Prevent a crash if the local folder does not exist anymore

NXDRIVE-1834: Test GNU/Linux binary on several distributions

---

docs/gnu_linux_qa.md
nxdrive/engine/engine.py
nxdrive/updater/base.py
nxdrive/utils.py
tests/conftest.py
tests/unit/test_utils.py

- NXDRIVE-1842: Fix mypy
- NXDRIVE-1845: Better fix. 
Creating the folder inside `find_suitable_tmp_dir()` was not a good idea. It would shadow the `rootDeleted()` event.

NXDRIVE-1834: Expand documentation with Ubuntu 16.04 output

---

tests/functional/test_behavior.py
tests/unit/test_utils.py

And:
- NXDRIVE-1686: Skip tests when the local sever is not local
This is to prevent false failures on a VM where the server is not local.

NXDRIVE-1845: Fix PermissionError on Windows tests

---

nxdrive/updater/base.py
nxdrive/updater/utils.py
tests/unit/test_updater.py

When using the centralized channel and the desired version is not set and the current version is from another channel than the release one, a downgrade is done. This should rather display a popup asking the user to either downgrade on the release channel or continue using the channel from the current version.

NXDRIVE-1803: Prevent unexpected downgrades

---

docs/changes/4.2.0.md
nxdrive/logging_config.py

* Compress old rotated log files at startup.
This should fix the issue when several rotated (old) files were not compressed.
* Remove old compressed log files at startup.

NXDRIVE-1830: Rotating logs check-up

---

docs/changes/4.2.1.md
nxdrive/client/local_client.py
nxdrive/engine/tracker.py
nxdrive/osi/darwin/darwin.py
nxdrive/osi/darwin/pyNotificationCenter.py
requirements.txt
tools/osx/deploy_jenkins_slave.sh

Send2Trash has been commented out and will be vendored with NXDRIVE-1868.

NXDRIVE-1396: [macOS] Upgrade PyObjC to 5.2

---

docs/changes/4.2.1.md
nxdrive/__main__.py
nxdrive/client/remote_client.py
nxdrive/data/qml/Systray.qml
nxdrive/engine/dao/sqlite.py
nxdrive/engine/engine.py
nxdrive/engine/processor.py
nxdrive/engine/queue_manager.py
nxdrive/engine/watcher/local_watcher.py
nxdrive/engine/watcher/remote_watcher.py
nxdrive/gui/api.py
nxdrive/gui/application.py
nxdrive/gui/view.py
tests/old_functional/test_transfer.py
tools/whitelist.py

Added timers to control when the files list in the systray can be updated. Same for syncing docs and synced docs counts.
Some refactoring in `view.py` on how rows insertion and deletion are done. The new code is cleaner and less resources greedy.
There is a small downside though: the remaining docs to sync (at the last iteration) is not updated
until the sync is actually over. But this is another issue not related to the subject and should be tackled another time.
Also:
- NXDRIVE-1875: Use more processors by default (5 -> 10)
- NXDRIVE-1876: Fix threads not totally released

NXDRIVE-1839: The GUI should be responsive when syncing a lot of files

---

nxdrive/gui/folders_loader.py
nxdrive/gui/folders_model.py

When a document is filtered inside a folder, all its sibbling are partially checked.

NXDRIVE-1838: Fix filters showing partially checked items

---

docs/changes/4.2.1.md
nxdrive/updater/windows.py

When cygwin is installed, the `timeout.exe` call was made using the one from cygwin rather than
the system one. This was causing that error:
```batch
timeout: invalid time interval ‘/t’
Try 'timeout --help' for more information.
```
Replacing timeout with ping is a reliable solution. Ping waits 1 second between attemps.

NXDRIVE-1890: [Windows] Fix waiting during auto-upgrade

---

docs/changes/4.2.1.md
nxdrive/fatal_error.py
nxdrive/osi/darwin/darwin.py
nxdrive/updater/darwin.py
tools/scripts/check_update_process.py

Those changes do not modify default behaviors:
- Updated `tools/scripts/check_update_process.py` to use the user folder.
- Made the FinderSync extension location agnostic.
- Made the auto-updater location agnostic.

NXDRIVE-1892: [macOS] Allow the app to be run from $HOME/Applications

---

docs/changes/4.2.1.md
nxdrive/client/local/base.py
tests/old_functional/test_local_creations.py

Added a test file mostly to only check the methods and it will also be usefull to validate NXDRIVE-988.

NXDRIVE-1897: The clean-folder CLI argument should ignore errors

---

docs/changes/4.2.1.md
nxdrive/data/i18n/i18n.json
nxdrive/gui/application.py

A popup with accounts is shown first when there is more than 1 account registered.
If the user hit ESC or click on Cancel, the upload is aborted.
When hitting ENTER or clicking on OK, the selected account is used for the Direct Transfer. There is no sorting on accounts yet, the first printed will be used by default.

NXDRIVE-1857: Handle multi-account for Direct Transfers

---

docs/changes/4.2.1.md
nxdrive/client/local/base.py
nxdrive/client/remote_client.py
nxdrive/data/i18n/i18n.json
nxdrive/engine/engine.py
nxdrive/engine/processor.py
nxdrive/gui/application.py
nxdrive/gui/folders_dialog.py
nxdrive/utils.py

I reviewed the notifications to not flood the user:
- When the user has selected the remote folder, a notif saying the upload is planned is shown.
- When a folder is uploaded, no notif.
- When a file is uploaded and it is considered a "big file" (depending of the `big_file` option), a notif saying the upload was done is shown.
If the folder already exists on the server, contents are merged. If there are duplicates, a popup asks the user what to do.

NXDRIVE-1853: Allow to Direct Transfer a folder and its contents

---

docs/changes/4.2.1.md
nxdrive/client/remote_client.py
nxdrive/direct_edit.py
nxdrive/engine/engine.py
tests/old_functional/test_remote_client.py

The issue fixed is that there may have transfers with the ONGOING status at startup. This is nonsens and reflect an past error. The fix is quite simple: remove them.
I also refactored `Engine.resume_suspended_transfers()`.

NXDRIVE-1919: Remove staled transfers at startup

---

tools/scripts/check_update_process.py

`distutils.version.StrictVersion` does not handle "w.x.y.z".
But for alpha versions, this is the schema we use. So the check is now removed.

NXDRIVE-1710: Removed version check in check_update_process.py

---

docs/changes/4.2.1.md
nxdrive/constants.py

Added `MaxRetryError` to the `CONNECTION_ERROR` constant.

NXDRIVE-1864: Retry later when a MaxRetryError occures

---

docs/changes/4.3.1.md
nxdrive/engine/processor.py
nxdrive/engine/tracker.py
nxdrive/manager.py
tests/functional/test_tracker.py

A new category "DirectTransfer" is added with one action "Sent". Events will have the document's type (either file or folder) and the document's size in bytes (0 for folders).
Events will be sent when the Direct Transfer is done.

NXDRIVE-1932: Send Direct Transfer analytics using its own category

---

docs/changes/4.3.1.md
nxdrive/direct_edit.py
tests/old_functional/test_direct_edit.py

- To ease debugging, we should log the final path that will be opened on the machine.
- Also, when a edited document is already synced and present in the local sync folder, we should
use `shutils.copyfile()` instead of `shutils.copy()` to prevent any metadata copy.
- Add a test for the previous statement.

NXDRIVE-1942: Small Direct Edit improvements

---

docs/changes/4.3.1.md
nxdrive/client/remote_client.py
nxdrive/commandline.py
nxdrive/manager.py

Fixed these errors:
```bash
manager.py:636:
Incompatible return value type (got "Optional[str]", expected "str")
commandline.py:574:
On Python 3 '{}'.format(b'abc') produces "b'abc'"; use !r if this is a desired behavior
```
There is also a false positive ignored for now (should be fixed in the next mypy release, see python/mypy#7717).

NXDRIVE-1944: Fix mypy issues following the update to mypy 0.740

---

docs/changes/4.3.1.md
setup.cfg

Fixes:
```bash
PytestDeprecationWarning: The 'junit_family' default value will change to 'xunit2' in pytest 6.0.
Add 'junit_family=legacy' to your pytest.ini file to silence this warning and make your suite compatible.
```

NXDRIVE-1946: Fix a deprecation warning in pytest 5.3.0

---

docs/changes/4.3.1.md
nxdrive/osi/darwin/files.py

If the user closes one or more documents in-between the time the documents list was retrieved and the time the list is processed, that error happens:
```
NSRangeException - *** -[NSArray getObjects:range:]: range {...} extends beyond bounds [...]
````

NXDRIVE-1955: [macOS] Fix opened documents retrieval not interating-safe

---

nxdrive/engine/processor.py
tests/old_functional/test_direct_transfer.py
tests/unit/test_utils.py

Also:
- NXDRIVE-1956: Handle the case when the remote path is no more set in the xattrs.
- Added more tests for new functions.

NXDRIVE-1853: [Windows] Fix blob check for TestDirectTransferFolder tests

---

docs/changes/4.3.1.md
docs/configuration.md
nxdrive/data/qml/AccountsTab.qml
nxdrive/data/qml/Systray.qml
nxdrive/data/qml/SystrayMenu.qml
nxdrive/engine/engine.py
nxdrive/engine/queue_manager.py
nxdrive/engine/watcher/local_watcher.py
nxdrive/engine/watcher/remote_watcher.py
nxdrive/gui/application.py
nxdrive/manager.py
nxdrive/options.py
nxdrive/poll_workers.py
tests/old_functional/common.py
tests/old_functional/test_direct_edit.py
tests/old_functional/test_direct_transfer.py
tests/old_functional/test_synchronization.py

Introduced a new option: `synchronization_enabled` (defaults to `True`).
When that option is set to `False`, local and remote whatchers will be started but nothing will be synced at all; Direct Edit and Direct Transfer features will continue to work as expected. I tried to be the less intrusive as possible.
I duplicated tests for those 2 features: one class in "normal" mode, when sync is effective; and one class with sync disabled.

NXDRIVE-1579: Disable synchronization upon server configuration

---

docs/changes/4.3.1.md
tests/README.md
tests/cleanup.py
tests/conftest.py
tests/env.py
tests/functional/conftest.py
tests/integration/windows/_test_installer.py
tests/integration/windows/test_cli_sub_command.py
tests/old_functional/__init__.py
tests/old_functional/common.py
tests/old_functional/test_group_changes.py
tests/old_functional/test_local_move_and_rename.py
tests/old_functional/test_remote_move_and_rename.py
tests/old_functional/test_volume.py
tests/unit/test_utils.py
tests/utils.py
tools/jenkins/test_volume.groovy
tools/jenkins/test_volume_specific.groovy
tools/scripts/check_update_process.py

The goal is to allow the test to be run on a given server (typically a customer preprod) to validate or check for performance issues.

NXDRIVE-1957: Add a test volume pipeline for specific cases

---

docs/changes/4.4.1.md
nxdrive/client/local/base.py
nxdrive/engine/processor.py
tests/old_functional/test_local_client.py
tests/old_functional/test_remote_move_and_rename.py

Folderish documents were not properly checked on remote modifications.
So the scenario of trying to update folderish contents was happening.
The fix is to filter out those documents.
Another smaller fix was applied to not get the size of a folder.
Even if it is a valid operation, it is useless and not required.

NXDRIVE-1951: Do not try to update contents of a folderish document

---

docs/changes/4.4.2.md
nxdrive/data/i18n/i18n.json
nxdrive/data/qml/AboutTab.qml
nxdrive/data/qml/FileCard.qml
nxdrive/data/qml/GeneralTab.qml
nxdrive/data/qml/IconLabel.qml
nxdrive/data/qml/NewAccountPopup.qml
nxdrive/data/qml/ProxyPopup.qml
nxdrive/data/qml/ScaledText.qml
nxdrive/fatal_error.py
nxdrive/gui/application.py

- Reduced the displayed report URL. Now only the basename is printed to fix missing parts of the final URL at different scalings.
- Removed the "monospace" font for "Courier". The former did not scale well on high zoom values.
Windows related changes:
- Removed "Arial" and "sans-serif" fonts as they did not scale well.
- Added the "Times" font as it scale well.
- The main window has a bigger height (540 -> 580).

NXDRIVE-1900: Fix display scaling when zoom is set to > 100%

---

docs/changes/4.4.2.md
nxdrive/logging_config.py
tests/unit/test_logging_config.py

The custom memory handler has a maximum capacity (tweaked via the `MAX_LOG_DISPLAYED` constant).
When retrieving its buffer contents, if the buffer exceeded the capacity just before, it is then empty. And so no logs are available.
This is a regression introduced with NXDRIVE-1231 in ec493f7.

NXDRIVE-1985: Fix the custom memory handler buffer retrieval

---

docs/changes/4.4.2.md
tools/cleanup.sh

The regexp used to deleted files was too greedy and so to remove 4.2.1.1 files, it was globbing 4.2.1.1* files. Thus 4.2.1.14 or any number greater then 4.2.1.1 was removed too.

NXDRIVE-1992: Fix old alpha files purgation

---

.pyup.yml
dependabot/config.yml
docs/changes/4.4.2.md

Pyup-bot is removed for Dependabot.

NXDRIVE-1993: Use Dependabot to keep dependencies up-to-date

---

benchmarks/__init__.py
benchmarks/test_safe_filename.py
docs/changes/4.4.2.md
nxdrive/client/local/base.py
nxdrive/client/local/windows.py
nxdrive/constants.py
nxdrive/direct_edit.py
nxdrive/utils.py
requirements-tests.txt
setup.cfg
tests/old_functional/test_direct_edit.py
tests/old_functional/test_local_client.py
tests/old_functional/test_special_characters.py
tests/old_functional/test_synchronization.py
tests/unit/test_utils.py
tools/posix/deploy_jenkins_slave.sh
tools/windows/deploy_jenkins_slave.ps1

The benchmark used for the original patch was not realistic and resultats were way wrong. I added a micro-benchmark suite.
Introducing unicode characters in filenames make results even worse. But `str.replace()` still has the best score. In the code is cleaner and more easy to read.
Also removed `safe_os_filename()`.
Filename sanitization is now the same for all OS.

NXDRIVE-1981: Better improvement patch for safe_filename()

---

docs/changes/4.4.2.md
nxdrive/updater/darwin.py

The last step of the auto-update is failing on some Catalina machines due to the new security framework. It is about unmounting the DMG volume. From the user POV, it always worked, the new version was effective at the next start.
We can "safely" ignore that error as the update actually did work.
Having smooth updates is the priority.

NXDRIVE-1976: [macOS] Do not fail the auto-update on unmountable volume

---

docs/changes/4.4.2.md
nxdrive/autolocker.py
tests/unit/test_autolock.py

Let's skip all errors at the top the the function.
It would be an endless fight to catch specific errors only.

NXDRIVE-1984: Handle all errors when checking for opened files

---

docs/changes/4.4.2.md
tools/windows/deploy_jenkins_slave.ps1

Skip JUnit report when running a specific test as it will fail because of the "::" that may contain the report filename.

NXDRIVE-1994: [Windows] Skip JUnit report when running a specific test

---

docs/changes/4.4.2.md
nxdrive/engine/watcher/local_watcher.py

Sometimes a FS event is targetting the NTFS stream and it triggers another event(s) with no source path.
The cause is not clear, but such events are now skipped.

NXDRIVE-1986: [Windows] Ignore FS moves with no source path

---

tools/codespell_skip.txt
tools/codespell_whitelist.txt
tools/posix/deploy_jenkins_slave.sh
tools/spell.skip
tools/spell.whitelist

- Renamed `codespell_skip.txt` to the generic `spell.skip`.
- Renamed `codespell_whitelist.txt` to the generic `spell.whitelist`.
- Empty lines and comments are now skipped. This allowes more sturctured and readable configuration files.
- Inline comments are handled too (they are removed from the line).

NXDRIVE-2008: Codespell adjustments

---

nxdrive/objects.py
tests/functional/test_direct_edit.py
tests/unit/test_objects.py

There is no more limitations on the `xpath`.
Those are all valid if they are present in the `properties` attribute (given "s" for string and "n" for number):
- s:s (file:content, foo:bar, note:note)
- s:s/n (files:files/0, foo:bar/0)
- s:s/n/s (files:files/0/file)
- s:s/n/n/n/n/s/n/s/... (foo:baz/0/0/0/0/file/0/real:file...)
Notes handling is stricter, only "note:note" `xpath` is taken into account.

NXDRIVE-2027: Allow to Direct Edit any custom metadata values

---

nxdrive/gui/application.py
nxdrive/osi/darwin/darwin.py
nxdrive/updater/darwin.py
tools/scripts/check_update_process.py

This is required to be able to use alpha versions as we will notarize official releases only.
Also:
- NXDRIVE-2041: Minor clean-up in `check_update_process.py`
- NXDRIVE-2045: [macOS] Fix a `TypeError` in `DarwinIntegration._get_favorite_list()`
- NXDRIVE-2044: Fix mispelled `Qt.CheckSate` attribute
Note: none of those tickets needs a changelog entry as for NXDRIVE-2044 and 2045 are regressions introduced in the current dev version; and the real fix for NXDRIVE-2041 will come later.

NXDRIVE-2041: [macOS] Fix the notarization in the auto-updater

---

docs/changes/4.4.2.md
nxdrive/client/local/linux.py
nxdrive/data/icons/emblem.svg
nxdrive/engine/engine.py

- Updated the set_folder_icon on linux. It now use the gio set command to change the folder custom-icon metadata.
- For the moment, the folder_windows icon is used as there is no icon for linux in the project.

NXDRIVE-1831: Set the root local folder icon on Linux

---

docs/changes/4.4.2.md
requirements.txt

This reverts commit 8bd3c242f748808f15fbd235b448c2c260c71b87.
`requests` does not support it right now.

Revert "Bump idna from 2.8 to 2.9 (#1360)"

---

tools/osx/deploy_jenkins_slave.sh
tools/osx/notarize.py

- Use the hardened runtime option on code signing.
- Use a signed timestamp on code signing.
- QML libraries need to be signed too for the notarization.
- Added `notarize.py` to automate notarization stuff.
This is not yet working as there is a blocker issue with Legrandin/pycryptodome#381.
But this is safe to merge, it will be made effective later.

NXDRIVE-2041: [macOS] Notarize the application

---

docs/changes/4.4.2.md
nxdrive/autolocker.py

- Updated psutil.process_iter() call to retrieve only the process pid.
- Fixed imports.

NXDRIVE-2048: Reduce the amount of Process informations retrieved in the auto-locker

---

tools/jenkins/packages.groovy

That agent was upgraded to macOS 10.13.6 (High Sierra) to meet notarization standards.
Also:
- NXDRIVE-2062: Skip code-signing and notarization for the auto-update check

NXDRIVE-2062: Use mac-drive-2 for macOs releases

---

docs/changes/4.4.2.md
tools/jenkins/packages.groovy

The mac-drive-1 agent has been upgraded to 10.13.6 too, so it can be used for releases too.

NXDRIVE-2068: Use any macOS agent for releases

---

docs/changes/4.4.2.md
tests/README.md
tests/env.py
tests/old_functional/__init__.py
tools/jenkins/test_volume_specific.groovy

Introduced 2 envars to control document types:
- `DOCTYPE_FILE` for file creations;
- `DOCTYPE_FOLDERISH` for non-files creations.

NXDRIVE-2004: Allow to customize document types in tests

---

docs/changes/4.4.2.md
nxdrive/engine/processor.py
tests/old_functional/test_synchronization.py

When a download is paused, it may happen that the file size on the server
is modified. In this particular case, an HTTP 416 error will be raised.
We want the local temporary file to be deleted and the download to be
restarted.
The processor.py file have been updated to catch and process the error.
A new test have been added in the test_synchronization.py file.
Also the changelog have been updated.

NXDRIVE-2010: Restart the download on HTTP 416 error (range not satisfiable)

---

docs/changes/4.4.2.md
tools/check_pytest_lastfailed.py
tools/posix/deploy_jenkins_slave.sh
tools/windows/deploy_jenkins_slave.ps1

When all tests pass, the "rerun" mecanism will still
be executed. And then all tests will be started, without
OS filtering.
The problem is caused by the pytest_cache that is used by the
command `pytest --last-failed --last-failed-no-failures`.
When all test pass, the lastfailed cache file will be empty,
in that case, the command will collect and rerun all the tests.
When this happen no test should be run at all.
The check_pytest_lastfailed.py file has been added to verify
verify the lastfailed cache file.
The script is called by the `deploy_jenkins_slave`(.sh|.ps1) files.
The .pytest_cache folder is now deleted before launching tests.
Also the changelog have been updated.

NXDRIVE-1991: Fix the tests "rerun" mechanism

---

docs/changes/4.4.2.md
nxdrive/commandline.py
tests/unit/test_commandline.py

When reading a config file with an unhandled encoding the config parser will crash.
We want Drive to ignore those files.
Drive is now handling only UTF-8 encoding for the config file.
A new test have been added in the test_commandline.py file.
Also changelog have been updated.

NXDRIVE-2049: Skip malformed local configuration files

---

docs/changes/4.4.2.md
nxdrive/utils.py
tests/unit/test_utils.py

'get_tree_size()' and 'get_tree_list()' methods have been updated to catch OSError.

NXDRIVE-1970: get_tree_size() and get_tree_list() should be resilient to OS errors

---

docs/changes/4.4.2.md
nxdrive/autolocker.py
nxdrive/direct_edit.py
nxdrive/engine/engine.py
nxdrive/manager.py
nxdrive/notification.py
nxdrive/poll_workers.py
tests/old_functional/__init__.py
tests/unit/test_autolock.py

A lot of code move, to better isolate some components' signals.
Engines, the Auto-Updater and Direct Edit (+ its Autolocker) are now started when the server's configuration has been fetched.

NXDRIVE-2091: Wait for the server configuration before starting features

---

docs/changes/4.4.2.md
nxdrive/engine/dao/sqlite.py

It seems that when a conflicted document was manually resolved by the user, and that same document was modified on the server at the same time (or almost), the error pops-up as that state was previously undefined. It is now a new conflict.

NXDRIVE-1869: Handle pair state resolved-modified as conflicted

---

docs/changes/4.4.2.md
nxdrive/engine/dao/sqlite.py
nxdrive/gui/view.py
tests/unit/test_engine_dao.py

In Downloads and Uploads tables of the Engine database, path fields
are wrongly defined as INTEGER.
A new migration have been added to change path fields to VARCHAR.
A test have been added.
Also changelog have been updated.

NXDRIVE-2092: Downloads.path and Uploads.path database field type

---

docs/changes/4.4.2.md
tools/jenkins/junit/merge.py
tools/posix/deploy_jenkins_slave.sh
tools/windows/deploy_jenkins_slave.ps1

Usage: `python merge.py FOLDER [FILE]`
Merge JUnit reports from `FOLDER` into `FILE`.
`FILE` is optional and defaults to `junit.xml`.
The final report will be saved into `FOLDER/FILE`.
It is possible to custom the test suite final report name using the `TEST_SUITE` envar (default is `Project`), examples:
export TEST_SUITE=Drive
export TEST_SUITE=nxPyML

NXDRIVE-2092: Make the JUnit merge script universal

---

docs/changes/4.4.2.md
tests/old_functional/test_group_changes.py

The line 'self.root_remote.groups.delete(group.groupname)' may
sometimes ends on a 404 error.
The test has been updated to now skip the error.

NXDRIVE-2003: Skip inexistant group deletion in test_group_changes.py

---

docs/changes/4.4.2.md
nxdrive/gui/api.py
nxdrive/gui/application.py

When clicking on "Open window" link in the Account settings, the window
may not appear if is already shown and hidden by another application.
A fix has been added in api.py file to always arise the conflict
windows when clicking on the link.

NXDRIVE-2074: Always raise the Conflicts/Errors window

---

docs/changes/4.4.2.md
docs/configuration.md
docs/dep/2020-03 Features flags.md
nxdrive/behavior.py
nxdrive/engine/processor.py
nxdrive/gui/application.py
nxdrive/poll_workers.py
tests/functional/test_server_options.py
tests/old_functional/test_behavior.py

There is only one at the time:
- `server_deletion`: Allow or disallow server deletions.

NXDRIVE-2079: Add behaviors flags

---

nxdrive/client/local/linux.py
nxdrive/osi/linux/linux.py

Instead of catching too specific exceptions, let's catch them all.
Here it was done to bypass:
FileNotFoundError: [Errno 2] No such file or directory: 'gio': 'gio'

NXDRIVE-374: Fix error handling

---

nxdrive/manager.py

Our packaging job tests the auto-updater before validating an alpha release. For that, it does not use an account and bypass that check. But with d8bf965 the auto-updater is started only
after the server's config is fetched, which cannot happen without account.
So we add a special case check to make the alpha release job happy again.

NXDRIVE-2079: Special case handling when testing the auto-updater

---

docs/changes/4.4.2.md
nxdrive/data/qml/FileCard.qml
nxdrive/data/qml/SelectableText.qml

Text selection should be enabled in the error window.
A new QML component has been added to create selectable text.
Text in errors/conflicts windows is now selectable.

NXDRIVE-2022: Allow text selection into the errors/conflicts window

---

docs/changes/4.4.2.md
nxdrive/data/qml/FileCard.qml
nxdrive/gui/api.py
tools/whitelist.py

Being able to click on the error title to open the document is an
intuitive action users often try.
The error title is now a link to the remote document.

NXDRIVE-2023: Make the error title an URL to the remote document

---

docs/changes/4.4.2.md
nxdrive/client/remote_client.py
nxdrive/engine/dao/sqlite.py
nxdrive/engine/processor.py
nxdrive/engine/watcher/local_watcher.py
nxdrive/gui/folders_model.py
nxdrive/osi/windows/windows.py
nxdrive/updater/darwin.py
nxdrive/utils.py
tests/integration/windows/test_cli_sub_command.py
tests/integration/windows/utils.py
tests/old_functional/test_synchronization_dedup.py
tests/unit/test_utils.py
tests/unit/test_windows_registry.py
tools/scripts/check_update_process.py

This was only one kind of error:
F999 f-string is missing placeholders

NXDRIVE-2115: Fix flake8 issues following the update to pyflakes 2.2.0

---

.github/workflows/dead_code.yml
.github/workflows/lint.yml
.github/workflows/spell.yml
.github/workflows/style.yml
.github/workflows/translations.yml
.github/workflows/types.yml
.github/workflows/unit_tests.yml
tools/deps/requirements-clean.txt
tox.ini

And other small improvements:
- NXDRIVE-2064: Use more specific paths for unit tests detection
- NXDRIVE-2064: Add the 'clean' tox env to remove tests data

NXDRIVE-2064: Use the latest VM image available for GitHub Actions

---

docs/changes/4.4.3.md
nxdrive/data/i18n/i18n.json
nxdrive/direct_edit.py
tests/functional/test_direct_edit.py
tests/old_functional/test_direct_edit.py

The downloaded file can be corrupted during a DirectEdit.
In this case We should display a notification and restart the download.
The CorruptedFile exception is now catched and the download restarted.
Notifications are now sent when this error happen.

NXDRIVE-1786: Handle corrupted downloads in Direct Edit

---

tools/deps/requirements.txt

PRs made by Dependabot are bad (#1498, #1499, #1500, #1501, #1502 and #1506).

Upgraded PyObjC from 6.1 to 6.2

---

docs/changes/4.4.3.md
nxdrive/direct_edit.py
tests/functional/test_direct_edit.py
tests/old_functional/test_direct_edit.py

It seems that there are more and more issues because of a previous
Direct Edit download failure. Doing another Direct Edit on the same
document will resume the download. Sometimes it will work, and
most of the time not.
A fresh download is now started everytime to prevent this issues.
The test test_resumed_download has benn added.

NXDRIVE-2112: Always start a fresh download on Direct Edit

---

docs/changes/4.4.3.md
nxdrive/direct_edit.py

Uploading a new blob of an ongoing Direct Edit'ed document should be made only when the
user had already locked it.
The auto-locking of documents can be disabled on Drive throught an option, exposing
the user to possibles concurrent updates of the document.
A warning log has been added when a Direct Edit is done while this option is activated.

NXDRIVE-2113: [Direct Edit] Add a warning on upload when server-side lock is disabled

---

docs/changes/4.4.2.md
tests/old_functional/test_local_client.py
tests/old_functional/test_synchronization_suspend.py

- Fixed `test_missing_file()`: it was not passing and was killed by the timeout. I do not know why, but the fix is simple and working.
- Reverted NXDRIVE-1690: as tests was screwed, it was passing even if it should have failed. Reverting the news also.
There are other failures to tackle, coming later.

NXDRIVE-2127: Fixes

---

docs/changes/4.4.3.md
nxdrive/client/proxy.py
nxdrive/constants.py
nxdrive/engine/tracker.py
nxdrive/manager.py
nxdrive/updater/base.py
nxdrive/utils.py
tools/changelog.py
tools/scripts/check_update_process.py

For calls made outside the Python client.
Now, when looking at Apache logs, we will see more interesting data (before/after):
IP - - [27/Apr/2020:14:03:07 +0000] "GET /static/drive-updates/versions.yml HTTP/1.1" 200 22268 "-" "python-requests/2.23.0"
IP - - [27/Apr/2020:15:00:28 +0000] "GET /static/drive-updates/versions.yml HTTP/1.1" 200 22255 "-" "nuxeo-drive/4.4.3"

NXDRIVE-2139: Make the custom user agent effective

---

docs/changes/4.4.3.md
nxdrive/engine/engine.py

The logging level from exception "Icon folder cannot be set"
has been lowered to warning because it is filling Sentry with
useless informations.

NXDRIVE-2121: Lower logging level of "Icon folder cannot be set"

---

docs/changes/4.4.3.md
nxdrive/data/i18n/i18n.json
nxdrive/direct_edit.py
nxdrive/objects.py
tests/old_functional/__init__.py
tests/old_functional/test_direct_edit.py

Direct Edit on proxies should be forbidden as it causes
many errors that fills the logs.
The document download is now aborted and a graphical error
is displayed when the user try to use Direct Edit on a proxy.
The translation file has been updated with the new error message.
A functionnal test has been added.

NXDRIVE-2132: Do not allow Direct Edit on proxies

---

docs/changes/4.4.3.md
nxdrive/direct_edit.py
nxdrive/engine/blacklist_queue.py
tests/old_functional/test_direct_edit.py

When trying to upload changes in Direct Edit, and if the target is a proxy then
the HTTPError 413 will be raised, filling server logs, client logs and
Sentry events. The error was already partially fixed by NXDRIVE-2132.
The error is now catched and the upload skipped when this error is raised.
The functional test test_direct_edit_413_error has been added.

NXDRIVE-2131: [Direct Edit] Handle HTTP 413 error: Request Entity Too Large

---

.github/workflows/dead_code.yml
.github/workflows/lint.yml
.github/workflows/spell.yml
.github/workflows/style.yml
.github/workflows/translations.yml
.github/workflows/types.yml
.github/workflows/unit_tests.yml

This would have catch the Windows crash. Better late than never!

NXDRIVE-2169: Enforce Python 32-bit on the CI

---

docs/changes.md
docs/changes/4.4.3.md
docs/changes/4.4.4.md
nxdrive/__init__.py

The history is weird because we urgently released 4.4.3 from a divergent branch. I tried to retrieve important data to keep aligned and doing thins right.

NXDRIVE-2137: Bump the version to 4.4.4

---

tests/old_functional/common.py
tox.ini

Just restoring the old behavior as there are too many useless errors reported to Sentry.

NXDRIVE-2127: Shadow (again) errors at closing

---

docs/changes/4.4.4.md
nxdrive/client/remote_client.py
nxdrive/engine/dao/sqlite.py
nxdrive/engine/dao/utils.py
nxdrive/osi/linux/linux.py
tests/old_functional/test_transfer.py

Also:
- NXDRIVE-2183: Removed code useless now that NXPY-163 is done
- NXDRIVE-2184: Fix mypy issues following the update to mypy 0.780
- NXDRIVE-2185: Be more specific on HTTP error handling when fetching the batch ID associated to an upload

NXDRIVE-2183: Fix chunked upload using an obsolete batch ID in certain circumstances

---

docs/changes/4.4.4.md
nxdrive/direct_edit.py
tests/functional/test_direct_edit.py

When the application is shut down during a direct edit, the edited file
stay locked on the remote server and the temporary file is not deleted.
When starting, the expected behaviour is to unlock the document on
the remote then remove the local orphan file.

NXDRIVE-2129: [Direct Edit] Orphaned documents should first be remotely unlocked before being cleaned up

---

tests/old_functional/common.py

The attribute was too often "lost" at some point: I think
it is cleaned up in the tear down method concurrently when
a report is asked.
Remove that attr and use the envar should fix that.
Note: it is intentional to always generate a reort on (unexpected) failure.

NXDRIVE-2179: Remove TwoUsersTest.report_path

---

docs/changes/4.4.4.md
nxdrive/engine/dao/sqlite.py
tests/conftest.py
tests/functional/conftest.py
tests/unit/test_autolock.py

When the application is shut down during a direct edit, the edited file
stay locked on the remote server and the temporary file is not deleted.
When starting, the expected behaviour is to unlock the document on
the remote then remove the local orphan file.
This commit fix the current behaviour in which Drive fails to retrieve
correctly the informations about the locked files from the database.
This prevent Drive to recognize orphan local files as locked.
This is the second step of a three steps fix of the bug.
Also changes has been updated.

NXDRIVE-2129: Fix behaviour of get_locked_paths()

---

tests/old_functional/common.py

A try to fix errors at the `generate_report()` step about that missing attribute.

NXDRIVE-2179: Remove TwoUsersTest.current_test

---

nxdrive/direct_edit.py
tests/old_functional/__init__.py
tests/old_functional/test_direct_edit.py

When the application is shut down during a direct edit, the edited file
stay locked on the remote server and the temporary file is not deleted.
When starting, the expected behaviour is to unlock the document on
the remote then remove the local orphan file.
This commit add a functionnal test on the direct edit system for
unlocking orphan files.
This is the last step of a three steps fix of the bug.

NXDRIVE-2129:  [Direct Edit] Ensure unlocking of orphaned documents

---

docs/changes/4.4.4.md
nxdrive/engine/engine.py
nxdrive/utils.py
tests/old_functional/test_direct_transfer.py
tests/unit/test_utils.py

This is only to keep the API homogenous and futures PRs will need that.

NXDRIVE-2018: Change order of elements returned by get_tree_list()

---

docs/changes/4.4.4.md
nxdrive/client/remote_client.py
nxdrive/client/uploader/__init__.py
nxdrive/client/uploader/direct_transfer.py
nxdrive/client/uploader/sync.py
nxdrive/engine/processor.py
tests/old_functional/common.py
tests/old_functional/test_direct_transfer.py

Split the current implementation of the uploads to ease customizing the behavior.
This is a required step in order to keep unified upload flow with different features (the sync process and Direct Transfer for now) without code duplication.

NXDRIVE-2190: Refactor Remote client uploads

---

docs/changes/4.4.4.md
nxdrive/client/uploader/__init__.py
nxdrive/client/uploader/direct_transfer.py
tests/old_functional/test_direct_transfer.py
tools/spell.whitelist
tools/whitelist.py

One small regression is that when a document without blob alreay exists on the server, a second document will be created, causing duplicates.

NXDRIVE-2065: Leverage the FileManager

---

docs/changes/4.4.4.md
tools/jenkins/beta.groovy

Notification will be sent to the public `#drive-notifs` channel.

NXDRIVE-2204: Add notifications when release jobs fail

---

tests/old_functional/common.py

It was changed mistakenly with 47ba4437fe170bd618bb19dcc672e4dd5c542868.

NXDRIVE-2201: Restore the 4 hours kill timeout for test_volume.py

---

docs/changes/4.4.4.md
nxdrive/client/remote_client.py
nxdrive/data/i18n/i18n.json
nxdrive/data/qml/TransferItem.qml
nxdrive/engine/engine.py
nxdrive/gui/application.py
tests/old_functional/test_direct_transfer.py
tools/whitelist.py

A new button was needed to have a way to cancel a transfer.
This button has been implemented using an icon next to the
pause/resume one.

NXDRIVE-2208: [Direct Transfer] Enable to cancel one or more transfer

---

nxdrive/data/i18n/i18n.json
nxdrive/data/qml/DirectTransfer.qml
nxdrive/data/qml/Main.qml
nxdrive/data/qml/TransferItem.qml
nxdrive/gui/application.py

- Reworked the entire window to place elements "correctly" (each element has its own rectangle, it eases positioning and thinking).
- The scrollbar is only affecting the items list: this allowes to not hide the selected remote folder on scrolling.
- Fixed the window resizing that was very weird and sometimes it was also not possible to resize it.
- Introduced tabs for next works, it renders better IMO.
- Commented the QML code to ease maintenance and reading.
- Fixed a QML error on Windows:
```
QWindowsWindow::setGeometry: Unable to set geometry 580x220+660+390 (frame: 598x267+651+352)
on QQuickView/"" on "\\.\DISPLAY1". Resulting geometry: 600x300+660+390
(frame: 618x347+651+352) margins: 9, 38, 9, 9 minimum size: 600x300
MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=618,347 maxtrack=0,0) …
```

NXDRIVE-1926: Improve the Direct Transfer window

---

nxdrive/data/qml/TransferItem.qml

From https://developer.blackberry.com/native/documentation/best_practices/performance/performance.html
> **Avoid declaring variant properties.**
> The variant type in QML is useful because it allows your app to store values from any of the basic Qt types. Although the variant type is versatile, the versatility comes at a price. Using a variant type when you can use a more specific type means that you get less compile-time help (the compiler may not recognize certain type-related errors) and your app pays a performance penalty for converting the value into and from a QVariant each time. If the variable is always a number, you should use the int or real types. If the variable is always text, use a string type.
This is for the history mostly :)
But here, the property was not used at all, and …

NXDRIVE-1926: Improve performances by removing an unused QVariant

---

docs/changes/4.4.4.md
nxdrive/client/uploader/__init__.py
nxdrive/client/uploader/direct_transfer.py
nxdrive/data/i18n/i18n.json
nxdrive/data/qml/DirectTransfer.qml
nxdrive/data/qml/Main.qml
nxdrive/data/qml/TransferItem.qml
nxdrive/engine/dao/sqlite.py
nxdrive/engine/engine.py
nxdrive/engine/processor.py
nxdrive/gui/api.py
nxdrive/gui/application.py
nxdrive/gui/view.py
nxdrive/objects.py
nxdrive/state.py
tests/old_functional/test_direct_transfer.py
tools/whitelist.py

This fixes UI performance issues because there is no need to do QML > C > Python > C > QML to fetch the remote folder path and UID (it was displayed in the header of the Direct transfer window).
Another performance issue was tackled: the use of xattrs to store remote paths and UIDs. Sending 50,000 files was freezing the UI; not it is still frozen but quite less. I may need additionnal work to completely tackle that issue.
Some interesting fixes/improvements:
- A nice folder icon is shown on the left of each progress bar to access the remote destination folder.
- Clean-up Direct transfer tests.
- Notifications are shown when the uploaded file is >= 25 MiB.
- The buttons available when cancelling a transfer are now Yes/No.

NXDRIVE-2219: Display a remote folder icon for each transfer

---

docs/changes/4.4.4.md
nxdrive/data/qml/FeaturesTab.qml
nxdrive/feature.py
nxdrive/gui/application.py
nxdrive/options.py
tests/unit/test_options.py

Due to NXDRIVE-2210, the S3 feature is now temporarily disabled.
Changelog has been updated.

NXDRIVE-2226: Disable temporarily S3 capability

---

docs/changes/4.4.4.md
nxdrive/client/remote_client.py
nxdrive/client/uploader/__init__.py
nxdrive/client/uploader/direct_transfer.py
nxdrive/data/qml/DirectTransfer.qml
nxdrive/data/qml/Main.qml
nxdrive/data/qml/SystrayTransfer.qml
nxdrive/data/qml/TransferItem.qml
nxdrive/engine/activity.py
nxdrive/engine/dao/sqlite.py
nxdrive/engine/engine.py
nxdrive/engine/processor.py
nxdrive/gui/api.py
nxdrive/gui/application.py
nxdrive/gui/view.py
nxdrive/objects.py
nxdrive/utils.py
tests/old_functional/test_direct_transfer.py
tests/unit/test_action.py
tests/unit/test_utils.py

- Do less work on the QML side.
- Improved upload file size computation: it is now done one-time only.
- Fixed duplicate prevention for documents without blobs.
- File size is only computed once for all `FileAction`s.
- Fixed `KeyError` in `BaseUploader.upload_chunks()` (`upload_idx`).
- A small sync icon + count is displayed at the bottom right.
- Items to transfer are first added to the database and then started. This is proper and will prevent GUI freeze because of too many bidirectional database access.
See my comment on https://jira.nuxeo.com/browse/NXDRIVE-2221 for more details + perf reports.

NXDRIVE-2221: Improve performances to prevent GUI freezes

---

nxdrive/client/uploader/__init__.py

Regression introduced with NXDRIVE-2190.
No changelog required as this was not shipped with any released version.

NXDRIVE-2222: Fix display of progress bars when pausing a transfer

---

docs/changes/4.4.4.md
nxdrive/engine/engine.py
nxdrive/gui/application.py
nxdrive/manager.py
nxdrive/osi/darwin/darwin.py

The interesting error was:
```python
Traceback (most recent call last):
File "osi/darwin/darwin.py", line 340, in unregister_folder_link
LSSharedFileListItemRemove(favorites, item)
ValueError: NSInvalidArgumentException - -[__NSCFString identifier]: unrecognized selector sent to instance 0x7fa036c71f50
```
---
Also a small fix in the same area:
- NXDRIVE-2138: Fix Account display on no account

NXDRIVE-2206: [macOS] Fix favorites unregistering process

---

docs/changes/4.4.4.md
nxdrive/client/remote_client.py
nxdrive/client/uploader/__init__.py
nxdrive/client/uploader/direct_transfer.py
tests/old_functional/__init__.py

The request is almost the same, but the "trick" is to use ElasticSearch instead of the current database.
The improvement is quite significative: for a folder containing 100,000 documents; the old way was taking up-to 15 seconds to complete. With the new way, it is a matter of milliseconds.

NXDRIVE-2231: [Direct Transfer] Improve the NXQL duplicate check

---

docs/changes/4.4.4.md
docs/configuration.md
nxdrive/engine/engine.py
nxdrive/options.py

Introduced `Options.database_batch_size` defaults to 256.

NXDRIVE-2232: Add an option to control the database batch size

---

nxdrive/client/uploader/direct_transfer.py

- Using the `X-Batch-No-Drop` header is not for our use case.
- Using the `nx-es-sync` header is a bad idea as it will start a synchronous thread just to try to wait for ES, which is async by design. For big uploads (files count) it will just start many threads for no real benefits for us.
- Using the `overwite` param is not a good idea as it would just create another document with the same name and thus generating duplicates. Even if we are doing a pre-check, concurrency can always catch us.

NXDRIVE-2065: Remove headers and params

---

nxdrive/engine/engine.py

The idea is to not force the signal when doing batch insertions and force a signal call when all items are added.
This will go easier on the database when adding a lot of files, and still it will works when adding only one file.

NXDRIVE-2232: Better signal management

---

docs/changes/4.4.4.md
nxdrive/client/remote_client.py
nxdrive/client/uploader/direct_transfer.py
tests/old_functional/__init__.py

We finally can't rely on ES for that task. ES is intrinsically async and the query does not make sens anymore then. Restored the old behavior.
Also fixed the duplicate creation (the `overwite` parameter).
Another small improvement was done: if `replace_blob` is True, then no need to check for existent documents on the server.

NXDRIVE-2231: Partly revert the patch

---

docs/changes/4.4.5.md
nxdrive/direct_edit.py
tests/functional/test_direct_edit.py

When Direct Edit'ing a file, a temporary file may be created next to
the edited file. During Drive startup, all the orphaned Direct Edit'ed files
are listed. If a temporary file is listed before the orphaned file then
it will be uploaded instead of the original file.
Some security has been added to prevent Drive from uploading these files
as it may result in data loss on Nuxeo.

NXDRIVE-2144: [Direct Edit] Prevent unintentional upload of files

---

docs/changes/4.4.5.md
nxdrive/data/i18n/i18n.json
nxdrive/data/qml/Systray.qml
nxdrive/engine/engine.py
nxdrive/gui/api.py
tests/functional/test_direct_edit.py
tools/whitelist.py

The server url in the systray has been removed and the Nuxeo icon action
tooltip has been updated.

NXDRIVE-2225: Remove the server URL below the account name in the systray

---

docs/changes/4.4.5.md
nxdrive/client/local/base.py
nxdrive/manager.py
tests/old_functional/common.py

Some old functional tests were broken as they don't use the
Windows long path prefix. The safe_long_path() method is 
now used to handle it.

NXDRIVE-2245: Use safe_long_path() in old functional tests

---

nxdrive/osi/darwin/darwin.py
tools/osx/drive/NuxeoFinderSync/FinderSync.swift
tools/osx/drive/NuxeoFinderSync/Info.plist

Until NXDRIVE-2251 is fixed, there will be no auto-update of menu entries.

NXDRIVE-2247: Apply changes in the FinderSync code too

---

nxdrive/gui/folders_dialog.py

It was used before we chose to use a default duplicates behavior.
But it is now useless.

NXDRIVE-2234: Remove useless signal

---

.github/workflows/docker_build.yml

invalid argument "docker-private.packages.nuxeo.com/docker-private.packages.nuxeo.com/drive:nuxeo-drive-build:py-3.7.7"
for "-t, --tag" flag: invalid reference format

NXDRIVE-2259: Fix

---

.github/workflows/docker_build.yml

invalid argument "docker-private.packages.nuxeo.com/drive:nuxeo-drive-build:py-3.7.7"
for "-t, --tag" flag: invalid reference format

NXDRIVE-2259: This is the good one (hopefully)

---

tests/old_functional/common.py

tests/old_functional/common.py:53:
LOCATION = safe_long_path(__file__).parent.parent
AttributeError: 'str' object has no attribute 'parent'

NXDRIVE-2245: Fix an AttributeError in common.py

---

docs/changes/4.4.5.md
nxdrive/gui/folders_dialog.py

The file picker is not opened anymore when clicking on the Direct Transfer icon in the systray menu. Now that
folders can also be uploaded, the remote selection window with the add folder button is opened instead to avoid
any confusion.

NXDRIVE-2267: [Direct Transfer] Do not open the file selection box on click in the systray

---

docs/changes/4.4.5.md
nxdrive/engine/engine.py
tests/old_functional/test_direct_transfer.py

Hidden files are now ignored during Direct Transfer.

NXDRIVE-2266: [Direct Transfer] Should ignore same file patterns as the sync engine

---

nxdrive/gui/application.py

Rely on the version rather than on the update channel as it would show release notes when using an alpha version and having the update channel set to something else than alpha.

NXDRIVE-2241: Skip the release notes popup on alpha versions

---

docs/changes/4.4.5.md
nxdrive/engine/engine.py
nxdrive/gui/folders_dialog.py
nxdrive/utils.py
tests/old_functional/test_direct_transfer.py
tests/unit/test_utils.py

Let's image a folder containing:
sources
└── repos
│   │   └── file.ext
.tox
├── base
│   ├── bin
│   │   └── activate.sh
logs.txt
.travis.yml
Before the patch, when selecting such folder, the ".tox" folder was filtered out, but not its contents.

NXDRIVE-2266: Fix file patterns filtering

---

docs/changes/4.4.5.md
nxdrive/client/proxy.py
nxdrive/manager.py

Also set a lower logging level on proxy validation error to prevent Sentry events spam.

NXDRIVE-2135: Check for proxy instantiation success when using a PAC

---

docs/changes/4.4.5.md
nxdrive/data/i18n/i18n.json
nxdrive/direct_edit.py
nxdrive/engine/blacklist_queue.py
tests/old_functional/test_direct_edit.py

Unhandled error while uploading a file where retried indefinitely.
This was quite bad as it exploded server logs, client logs and
the Sentry quote. From now, a failing upload will be tried 3 times
before being dropped from the upload_queue.

NXDRIVE-2147: [Direct Edit] Add a maximum retry count for items in the upload queue

---

docs/changes/4.4.5.md
nxdrive/engine/dao/sqlite.py

Also:
- NXDRIVE-2282: Use a bigger SQL transaction timeout

NXDRIVE-2019: Do not fetch the database lazily to prevent deadlocks

---

docs/changes/4.4.5.md
nxdrive/engine/dao/sqlite.py
nxdrive/gui/api.py

A small naive benchmark: Direct Transfer a folder containing 100 files.
- Before: ~ 281 req/s
- After:  ~ 352 req/s
From the UX POV, it feels like a significant gain on the overall upload speed.

NXDRIVE-2019: Improve database queries

---

nxdrive/data/qml/FileCard.qml
nxdrive/data/qml/SystrayFile.qml
nxdrive/data/qml/SystrayTransfer.qml

FileCard.qml:14: TypeError: Cannot read property 'width' of null
FileCard.qml:15: TypeError: Cannot read property 'horizontalCenter' of null
SystrayFile.qml:9: TypeError: Cannot read property 'width' of null
SystrayTransfer.qml:11: TypeError: Cannot read property 'width' of null

NXDRIVE-2180: Fix more QML errors

---

docs/changes/4.4.5.md
nxdrive/client/local/base.py
nxdrive/manager.py
nxdrive/utils.py
tests/old_functional/common.py

Those were too dangerous and I do not measure exactly the possible side-effects of those changes. They also still break some tests. Let's tackle the real issue later (it does not affect Drive itself but the tests).

Revert NXDRIVE-2245 and NXDRIVE-2277

---

nxdrive/client/proxy.py

Logging an error would just fill our Sentry quota with useless data.

NXDRIVE-2135: Lower the logging level of validate_proxy()

---

tests/old_functional/test_direct_edit.py

Increased wait_sync() timeout to 30 seconds for test_direct_edit_max_error().

NXDRIVE-2147: Fixed test_direct_edit_max_error() on Windows

---

docs/changes/4.4.5.md
nxdrive/client/remote_client.py

A small patch to prevent useless logs like:
Chunk transfer speed was 0.0 B/s
When the transfer was too fast on small files.

NXDRIVE-2294: Improve logging of the transfer speed

---

docs/changes/4.4.5.md
tests/old_functional/test_direct_edit.py

The test test_orphan_should_unlock was broken on Windows and has
been fixed.

NXDRIVE-2245: [Windows] Fix test_orphan_should_unlock()

---

docs/changes/4.4.5.md
nxdrive/engine/dao/sqlite.py

Before the patch, the journal mode was MEMORY, which is prone to data loss (and we saw it a lot!).
Now the "new" WAL mode is used, resulting in better integrity, no more data loss (even if the app crashes), and way better performances.

NXDRIVE-1888: Improve database queries to anihile any deadlock

---

docs/changes/4.4.5.md
nxdrive/engine/dao/sqlite.py
nxdrive/engine/engine.py
nxdrive/engine/processor.py
tests/old_functional/test_direct_transfer.py

When a Direct Transfer session is ongoing, the user can cancel one
of the documents. The session is now updated when the user remove
an element from the Transfer session.

NXDRIVE-2301: [Direct Transfer] Handle a transfer cancel during sessions

---

docs/changes/4.4.5.md
nxdrive/engine/engine.py
nxdrive/engine/processor.py
nxdrive/notification.py

The notification on large file upload is not sent anymore.
Changelog has been updated.

NXDRIVE-2156: [Direct Transfer] Cleanup useless notification

---

tests/old_functional/common.py
tests/old_functional/test_direct_transfer.py

Logs can now be captured in old_functionnal tests.

NXDRIVE-2156: Add tests for Direct Transfer sessions notifications

---

docs/changes/4.4.5.md
nxdrive/engine/dao/sqlite.py
tests/unit/test_engine_dao.py

The previous code allowing to store path-like objects in
the database was quite intrusive.
The code has been replaced by the usage of an sqlite adapter.

NXDRIVE-2302: Use an adapter to store path-like objects in the database

---

nxdrive/client/uploader/direct_transfer.py
nxdrive/engine/processor.py

It would happen when all chunks have been uploaded but there wouldbe an error at the `FileManager.Import` call.
In that case, we should not re-upload the file but just skip it.

NXDRIVE-2268: Fix a regression where the file would be uploaded again

---

docs/changes/4.4.5.md
tests/old_functional/common.py
tests/old_functional/test_context_menu.py
tests/old_functional/test_direct_edit.py
tests/old_functional/test_direct_transfer.py
tests/old_functional/test_permission_hierarchy.py
tests/old_functional/test_volume.py

Also fixed the case when a test should be skipped or xfailed and it would go until the kill timeout. Such tests are now "returning" quickly as they should.

NXDRIVE-2303: Fix useless reports generated in tests

---

docs/changes/4.4.6.md
nxdrive/gui/api.py

When adding a new account and the synchronization is
disabled, the Filters windows will be skipped as it
is useless.

NXDRIVE-2305: Do not display the filters window on new account if the synchronization is disabled

---

docs/changes/4.4.6.md
nxdrive/gui/application.py

When adding an account, the browser may take some time
to open. A waiting cursor has been added so the user
can know that something is currently happening.

NXDRIVE-2076: Change the cursor on click on new account connect button

---

docs/changes/4.4.6.md
nxdrive/data/qml/ChannelPopup.qml
nxdrive/data/qml/DeletionPopup.qml
nxdrive/data/qml/LogLevelPopup.qml
nxdrive/data/qml/ProxyPopup.qml

When validating a setting, a QML check is done to check if
the setting value has changed and prevent useless calls to
Python code.

NXDRIVE-2306: Do not validate again settings when the value did not change

---

docs/changes/4.4.6.md
nxdrive/gui/application.py
tools/osx/deploy_ci_agent.sh
tools/osx/travis.sh
tools/scripts/check_update_process.py
tools/windows/deploy_ci_agent.ps1
tools/windows/travis.sh

This is currently preventing the alpha job to work on Travis-CI.
Also reduced the release process time by 33% on macOs and Windows!

NXDRIVE-2316: Skip the synchronization in the auto-update check script

---

docs/changes/4.4.6.md
nxdrive/client/remote_client.py

Retrying on HTTP 500 was leading to obscure issues when finalizing a transfer done via a third-party provider like S3.

NXDRIVE-2322: Do not retry a HTTP call that failed on 500 error

---

docs/changes/4.4.6.md
tests/old_functional/test_context_menu.py

We changed the default UI in NXDRIVE-2223 and since then the test was failing.

NXDRIVE-2326: Fix test test_get_metadata_infos()

---

docs/changes/4.4.6.md
nxdrive/utils.py
tests/unit/test_utils.py
tools/deps/requirements-tests.txt

It appears that our tests mocking `os.scandir()` were also bad.
So I fixed the tests by using the `pyfakefs` module, way cleaner now.

NXDRIVE-2331: Check for ignored patterns against lowercased names

---

docs/changes/4.4.6.md
mypy.ini
nxdrive/osi/windows/registry.py

The error has been patched upstream, see https://github.com/python/typeshed/pull/4663.

NXDRIVE-2336: Fix mypy issues following the update to version 0.790

---

docs/changes/4.4.6.md
nxdrive/data/qml/NewAccountPopup.qml

Since the upgrade to PyQt 5.15.1, when adding an account there is a missing margin above the URL field. But as soon as a character is entered into the field, the margin comes again and all is fine.
So let's increase the margin and see later when the Qt/PyQt issue will be addressed to remove it.

NXDRIVE-2349: Fix a QML margin in the account addition

---

docs/changes/4.4.6.md
nxdrive/client/uploader/__init__.py
nxdrive/client/uploader/direct_transfer.py
nxdrive/engine/processor.py
tests/old_functional/test_direct_transfer.py

A check is now done before starting a file upload to verify if the linked session is already paused.

NXDRIVE-2341: [Direct Transfer] Non-chunked uploads must be put in pause when the session is paused

---

.github/dependabot.yml
docs/changes/4.4.6.md

Let Dependabot update GitHub Actions dependency once a month.
Here's reference to the dependabot configs.
https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-actions-up-to-date-with-github-dependabot
Source: https://github.com/python/cpython/pull/22787

NXDRIVE-2370: Allow dependabot to check GitHub actions monthly

---

.github/workflows/functional_tests.yml
.travis.yml
docs/changes/4.4.6.md
nxdrive/manager.py
tests/functional/test_server_options.py

Great news, I also unlocked:
- NXDRIVE-2071: Use GitHub Actions to run functional tests

NXDRIVE-2376: Use the dedicated test server whenever possible

---

docs/changes/4.4.6.md
nxdrive/client/uploader/__init__.py
nxdrive/client/uploader/direct_transfer.py
nxdrive/data/qml/SessionItem.qml
nxdrive/engine/dao/sqlite.py
nxdrive/engine/processor.py
nxdrive/exceptions.py

Direct Transfer uploads will now inherit the session status when saved into database. Uploads from cancelled sessions won't be uploaded anymore.

NXDRIVE-2309: [Direct Transfer] Fix multiple non-chunked uploads pause and cancel

---

docs/changes/4.4.6.md
tools/osx/entitlements.plist

This is required for the upcoming PyInstaller version that will allow to handle Apple events.

NXDRIVE-2391: [macOS] Add required entitlement for Apple events

---

docs/changes/4.4.6.md
nxdrive/__main__.py

This is a commit ahead of the time: it will make sens only when we will be using Python 3.8.6+ and PyInstaller 4.1+.
But it has been verified that using those versions + this patch make the app working on macOS Big Sur.
Note: we still can't use Big Sur as a development machine due to issues on other modules (`packaging`), Python and Qt.

NXDRIVE-2270: [macOS] Big Sur support

---

docs/changes/4.4.6.md
nxdrive/constants.py
nxdrive/data/qml/DirectTransfer.qml
nxdrive/data/qml/SessionItem.qml
nxdrive/data/qml/TransferItem.qml
nxdrive/gui/api.py
nxdrive/gui/application.py
nxdrive/gui/view.py
tools/skiplist.py

Previously, items were added and removed from the ListView when a change in sessions or direct transfer items was detected.
This behaviour caused the app to crash if an item from the list was removed while in use (cancel popup).
Now, a fixed list of items is used an just edited when changes are detected, preventing the interface to remove used items.

NXDRIVE-2379: Review how the GUI is repainted to fix a crash

---

.travis.yml
docs/changes/4.4.6.md
docs/support.md
tools/windows/setup-addons.iss
tools/windows/setup-common.iss

That means:
- We do not support anymore Windows 7 without SP1.
- The minimum Windows version required is Windows 7 SP1.

NXDRIVE-2395: [Windows] Upgrade Inno Setup from 6.0.5 to 6.1.2

---

docs/changes/4.4.6.md
nxdrive/client/uploader/__init__.py

With NXDRIVE-2298, we made use of the `X-Batch-No-Drop` HTTP header when finalizing an upload. And then, the `batchId` had to be removed manually, doing one HTTP call for that.
That is useful for large uploads but the HTTP call can be saved for non-chunked uploads.

NXDRIVE-2397: Small improvement for non-chunked uploads

---

nxdrive/osi/extension.py
tests/old_functional/test_local_share_move_folders.py
tests/old_functional/test_synchronization.py

Before the upcoming release, I wanted to add debug logs into the extenstion server startup code to help catching/understanding what is the issue on macOS when it would not start because of a local address set to `None`.

NXDRIVE-2408: Add debugging logs to help understanding the issue

---

docs/changes/4.5.0.md
nxdrive/engine/dao/sqlite.py
nxdrive/engine/engine.py
nxdrive/engine/processor.py
nxdrive/gui/api.py
nxdrive/gui/application.py
tests/unit/test_engine_dao.py

Fixes done too quickly and introducting issues.

Reverts NXDRIVE-2406 and NXDRIVE-2407

---

nxdrive/client/remote_client.py
nxdrive/engine/watcher/remote_watcher.py

Also use a higher logging level for `UnknownDigest` errors.

NXDRIVE-2140: Handle unknown digests from the remote watcher

---

nxdrive/updater/linux.py
tools/scripts/check_update_process.py

The old `os.chmod()` was destructive, in the sense that it reset all other permission bits.

NXDRIVE-2360: Fix os.chmod() to conserve other permissions

---

docs/changes/4.5.0.md

No need for the changelog entry as the bug was introduced in the current dev release.

NXDRIVE-2429: Remove the changelog entry

---

docs/changes/4.5.0.md
nxdrive/client/uploader/__init__.py
nxdrive/data/qml/SessionItem.qml
nxdrive/data/qml/TransferItem.qml
nxdrive/engine/dao/sqlite.py
nxdrive/engine/engine.py
nxdrive/engine/processor.py
nxdrive/gui/application.py

Remove the possibilty to pause transfers displayed on the monitoring tab. It is now possible to cancel an ongoing transfer.

[Direct Transfer] Remove pause button on the monitoring tab

---

nxdrive/osi/darwin/darwin.py
nxdrive/updater/darwin.py
nxdrive/updater/linux.py
nxdrive/updater/windows.py

- Fixed the `SIGKILL:9` error when unmounting the volume. This was due to the xattr modification on the new folder. I am not sure why, but skipping that step fixed the issue.
- Fixed the `SIGKILL:9` error when unloading the Finder extenstion. This was due to the fact that the extension was stopped twice. The second time ended on error.
- Removed the code looking for the FinderSync PID that was not working. The information is not really useful though.
- Use the `plistlib` module to find the volume mount point, more reliable and future proof.

NXDRIVE-2363: [macOS] Fix auto-update issues 

---

nxdrive/gui/application.py

The finalizing status from shadow items is now ignored when refreshing the transfers list.

NXDRIVE-2433: Ignore data from shadow items on transfers refresh

---

nxdrive/client/uploader/__init__.py

The `test_pause_upload_automatically()` from `test_direct_transfer.py` revealed the issue.
Introduced in 98830f18.

NXDRIVE-2433: Fix handling of transfer that must be suspended at exit

---

docs/changes/4.5.0.md
nxdrive/data/qml/TransferItem.qml
nxdrive/engine/dao/sqlite.py
nxdrive/gui/application.py
nxdrive/gui/view.py

When cancelling a transfer in the Monitoring tab, the
next transfer that will replace him will have it's button
disabled.

NXDRIVE-2433: Fix cancel button become disabled after transfer removal

---

nxdrive/engine/dao/sqlite.py
nxdrive/engine/processor.py

Before the patch, all items to be transferred were started and then paused when their session was paused. This was quite bad because as a transfer was initiated, a call to the server was made for at least retrieve a `batchId`. Even worse, all remaining transfers not yet handled were started _at once_; resulting in N parallel calls to the server and entries in the `Uploads` database table.
Now, when pausing a session, ongoing transfers will be finished for non-chunked ones, the others will be paused ASAP.
Another issue was fixed when starting the app and a session is paused: all its transfers were added to the queue and then filtered out by the `Processor`. The SQL query was improved to prevent pushing such pairs into the queue.
As always: less is better, let's be lazy :)

NXDRIVE-2309: Improve the session pause behavior

---

nxdrive/client/local/base.py
nxdrive/client/remote_client.py
nxdrive/utils.py

Also some improvements:
- Remove useless `str()` cast for `os.path.abspath()`.
- Use `os.fsdecode()` instead of `str.decode()`.
---
Also NXDRIVE-2448: Remove the temporary file on `CorruptedFile` error
If we do not do the clean-up, the file will grow up to file size * N (where N is the download count).

NXDRIVE-2319: [Windows] Fix double long path prefix

---

nxdrive/commandline.py

Discovered when auto-updating using
python tools/scripts/check_update_process.py
The fatal error screen shows then:
Command line arguments:
bind-server
Administrator
http://localhost:8080/nuxeo
--password=Administrator
--local-folder=/var/folders/cl/np3mbdjs28sb3sgbgh67lv680000gn/T/tmpzw9mq098/folder
Exception:
Traceback (most recent call last):
File "nxdrive/__main__.py", line 130, in main
File "nxdrive/commandline.py", line 544, in handle
TypeError: bind_server() got some positional-only arguments passed as keyword arguments: 'options'

NXDRIVE-1768: Fix commandline.py

---

docs/changes/4.5.1.md
docs/manual_init.md
ftest/README.md
nxdrive/commandline.py
nxdrive/data/qml/icon-font/license.txt
nxdrive/fatal_error.py
nxdrive/gui/api.py
nxdrive/gui/application.py
nxdrive/gui/folders_dialog.py
nxdrive/gui/folders_loader.py
nxdrive/gui/folders_model.py
nxdrive/gui/folders_treeview.py
nxdrive/gui/systray.py
nxdrive/gui/view.py
nxdrive/osi/extension.py
nxdrive/qt_constants.py
tests/functional/test_tracker.py
tests/integration/windows/_test_installer.py
tests/integration/windows/test_cli.py
tests/integration/windows/utils.py
tests/old_functional/test_local_creations.py
tests/old_functional/test_synchronization_suspend.py
tests/unit/conftest.py
tests/unit/test_autolock.py
tests/unit/test_blacklist_queue.py
tests/unit/test_extension_listener.py
tests/unit/test_objects.py
tools/linux/nautilus/contextual_menu.py

Thanks for the work done on https://github.com/qutebrowser/qutebrowser/issues/5904, I used the provided `enums.txt` with that script in order to find Qt enums used accross the project:
```python
from pathlib import Path
def get_enums():
file = Path.home() / "downloads" / "enums.txt"
lines = file.read_text().splitlines()
return [line.strip().split() for line in lines]
def get_files():
for file in Path("nxdrive").glob("**/*.py"):
yield file, file.read_text().splitlines()
def find(old, new, file, contents):
for lineno, line in enumerate(contents, 1):
if f"{old}." in line:
print(f"{file}:{lineno} {old} -> {new}")
def main():
files = list(get_files())
lines = get_enums()
for file, content in files:
for old, new in lines:
find(old, new, file, content)
main()
```

NXDRIVE-2444: Use Qt scoped enums

---

docs/changes/4.5.1.md
tools/deps/requirements.txt

Reverts nuxeo/nuxeo-drive#2349 until https://github.com/psf/requests/pull/5711 is merged.

Revert "Bump idna from 2.10 to 3.1 in /tools/deps"

---

docs/changes/4.5.1.md
nxdrive/data/qml/DirectTransfer.qml
nxdrive/gui/view.py
tools/skiplist.py

Fixed NO_ACTIVE_SESSION label refresh.

NXDRIVE-2453: [Direct Transfer] Missing label on the active sessions list

---

nxdrive/utils.py

Python will automatically use the most secure protocol by default.

NXDRIVE-2472: Prefer to not setting the protocol

---

nxdrive/client/remote_client.py
nxdrive/client/uploader/direct_transfer.py
nxdrive/gui/folders_dialog.py

Without that patch, it would be impossible to upload a folder named "test" if a remote non-folderish document already exists with the same name.
The same applies for the reverse check (local file "test" -> remote folder "tests").

NXDRIVE-2438: Use a more specific NXQL query with the mixinType

---

docs/changes/4.5.1.md
nxdrive/direct_edit.py
tests/old_functional/test_direct_edit.py

Exception is now catched and orphan is purged when the error is encountered.
A tests have been added.

NXDRIVE-2409: [Direct Edit] Handle document unlock error when it is already locked by someone else

---

docs/changes/4.5.1.md
nxdrive/client/local/base.py
nxdrive/utils.py

`realpath()` will resolve symbolic links and return an absolute path.

NXDRIVE-2485: Use os.path.realpath() instead of abspath()

---

docs/changes/4.5.1.md
nxdrive/engine/dao/sqlite.py

The States table was not cleaned correctly when filtering a
remote sync root. This prevented the sub-sub-folders to
be synced again when the user unfitered the remote sync root.
All childrens of the synced root are now deleted from the States
table when applying a filter.

NXDRIVE-2489: [Windows] Subfolder content not synced on unfiltering

---

docs/changes/5.0.0.md
nxdrive/engine/processor.py

- Moved `._current_doc_pair` from class attribute to instance attribute.
- Introduced `._get_next_doc_pair()`.
- Introduced `._handle_doc_pair_dt()` and `._handle_doc_pair_sync()`.
Mixing sync items with Direct Transfer ones was already quite tricky.
I split the code in specific methods. It is a little bit more clear.
I am not sure we can optimize `._execute()` more, the "D" `radon` notation is because of errors handling.

NXDRIVE-1359: Reduce the complexity of Processor._execute()

---

nxdrive/data/qml/Systray.qml

Systray.qml:304: ReferenceError: orange is not defined

NXDRIVE-2351: Fix left 'orange' color

---

nxdrive/client/uploader/__init__.py
nxdrive/engine/processor.py

Prevent that error when the import will be made lazily:
ImportError: cannot import name 'UploaderS3' from partially initialized module 'nuxeo.handlers.s3' (most likely due to a circular import)
Also log the cause of an upload error to help debug.

NXDRIVE-2479: Improve S3 class import

---

docs/changes/5.0.0.md
nxdrive/engine/dao/sqlite.py

The DELETE journal mode is now user for the manager database instead of WAL.

NXDRIVE-2524: [GNU/Linux] WAL journal mode cause manager database corruption

---

docs/changes/5.0.1.md
tests/unit/test_action.py

`test_file_action_with_values()` was leaking its action and it was making `test_tooltip()` to fail on macOS.

NXDRIVE-2543: Fix test_file_action_with_values() to finish the action

---

docs/changes/5.0.1.md
tools/posix/deploy_ci_agent.sh

On macOs, before the patch, we had those lines:
>>> [1/      47] Testing tests/old_functional/test_special_characters.py ...
And with the patch:
>>> [1/47] Testing tests/old_functional/test_special_characters.py ...
It is a uniformization of the display on all OSes.

NXDRIVE-2549: Fix test number display

---

docs/changes/5.0.1.md
nxdrive/__main__.py
nxdrive/tracing.py
tests/unit/test_tracing.py

Added a simple filter to ignore already sent events.
I also removed the sensitive data redaction as it was not working and Sentry already provides such mechanism by default.

NXDRIVE-2550: Prevent Sentry flooding

---

nxdrive/direct_edit.py
tests/old_functional/test_direct_edit.py
tests/old_functional/test_remote_move_and_rename.py
tests/old_functional/test_transfer.py

This is a good thing, tests a using less mocking, which is always good.
Also added a Direct Edit test to cover the behavior when all download attempts failed.

NXDRIVE-2553: Fix tests no more passing because of __slots__ constraints

---

nxdrive/engine/engine.py
nxdrive/engine/processor.py

The metric was sent each and every time a transfer was finished.
It is now only sent when we want to: when the session is effectively finished.

NXDRIVE-2476: [Direct Transfer] Fix session status metric

---

docs/changes/5.1.1.md
docs/configuration.md
nxdrive/client/uploader/__init__.py
nxdrive/engine/dao/sqlite.py
nxdrive/engine/processor.py
nxdrive/engine/queue_manager.py
nxdrive/objects.py
nxdrive/options.py
tests/old_functional/test_synchronization.py
tests/old_functional/test_transfer.py
tests/unit/test_engine_dao.py

Introduced a new option, disabled by default, to enable idempotent requests: `use_idempotent_requests`.

NXDRIVE-2463: Add support for idempotent requests

---

docs/changes/5.1.1.md
nxdrive/translator.py
tests/unit/test_translator.py

Also aligned `values` kwarg of `Translator.get()` on `Translator.get_translation()`.

NXDRIVE-2597: Use a LRU cache for translation strings

---

docs/changes/5.1.1.md
tools/scripts/check_update_process.py

- Print the log content in the auto-updater check script, to ease debugging issues on Travis-CI, hopefully.
- Set the `exec-profile` option to not pollute metrics.

NXDRIVE-2599: Enhance the auto-update check script

---

docs/changes/5.1.2.md
nxdrive/client/uploader/__init__.py
tests/old_functional/test_transfer.py
tools/deps/requirements-tests.txt

NXDRIVE-2607: Handle invalid data returned by the server when asking for a batchId

---

docs/changes/5.1.2.md
nxdrive/engine/processor.py

NXDRIVE-2636: Handle HTTP 405 (Method Not Allowed) errors

---

tools/deps/requirements-pip.txt

Following adba459d404629908f9349504a188287a3f70e0c.

Fix missing colorama requirement on Windows

---

docs/changes/5.2.2.md
nxdrive/options.py

To ease debugging, `Options` changes are now logged at `INFO` level.

NXDRIVE-2661: Set a higher logging level for Options changes

---

docs/changes/5.2.2.md
nxdrive/osi/darwin/files.py

NXDRIVE-2684: [macOS] Fix opened documents retrieval not interating-safe

---

docs/changes/5.2.2.md
nxdrive/engine/engine.py

NXDRIVE-2700: Prevent 'Comparison between bytes and string' warning

---

docs/changes/5.2.2.md

NXDRIVE-2672: Release 5.2.2

---

nxdrive/engine/processor.py
nxdrive/engine/queue_manager.py

Also minor refactoring of `QueueManager.push_error()`.

NXDRIVE-2704: Do not send metrics on postponed actions

---

docs/changes/5.2.3.md
nxdrive/__main__.py

The issue is probably more global as I was able to reproduce on Linux until the version 4.2.0.
I did not tested older versions but they should fail too.

NXDRIVE-2714: Can't start on macOS when the OS locale is english

---

docs/changes/5.2.5.md
nxdrive/engine/queue_manager.py

NXDRIVE-2721: [Windows] Correctly handle WinError 32

---

docs/changes/5.2.5.md
docs/configuration.md
nxdrive/client/remote_client.py
nxdrive/engine/watcher/remote_watcher.py
nxdrive/options.py
nxdrive/utils.py
tests/functional/test_remote_client.py
tests/unit/test_options.py
tests/unit/test_utils.py

Sync roots will be renamed according to their `N` parents' names. `N` defaults to 2 and can be controled through the `sync_root_max_level` option.
The option can get up to 4 levels or hierarchy. Set it to 0 to disable the new behavior.
Sync root names are also always shortened to 47 chars (ellipsis will be included in the middle when it was altered).

NXDRIVE-2694: Review handling of sync roots

---

docs/changes/5.2.7.md
nxdrive/dao/base.py
nxdrive/manager.py
nxdrive/options.py
nxdrive/updater/utils.py
setup.cfg
tests/functional/test_manager.py
tests/unit/test_updater.py

The updater will now ignore the broken update when fetching the last available version.

NXDRIVE-2534: Add the xxx_broken update option

---

docs/changes/5.3.0.md
nxdrive/gui/folders_dialog.py

NXDRIVE-2737 In Direct Transfer, handle Esc key on Max state to restore it to Normal state

NXDRIVE-2737: Fix Minimize/maximize issue on Direct Transfer screen

---

.github/workflows/alpha_cleanup.yml
.github/workflows/beta_to_prod.yml
.github/workflows/release.yml
tools/cleanup.sh
tools/deploy.sh
tools/release.sh
tools/upload.sh

This PR is raised to update lethe server configuration. This is required as Lethe server is migrated to another aws account under private network.

Update Lethe server configuration

---

docs/changes.md
docs/changes/5.4.1.md
nxdrive/__init__.py

NXDRIVE-2917: Release Beta 5.4.1

NXDRIVE-2917: Release Beta 5.4.1
